/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.butchery.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.client.event.RegisterColorHandlersEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.api.distmarker.Dist;

import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.Block;

import net.mcreator.butchery.block.*;
import net.mcreator.butchery.ButcheryMod;

import java.util.function.Function;

public class ButcheryModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(ButcheryMod.MODID);
	public static final DeferredBlock<Block> OAK_BUTCHERS_TABLE;
	public static final DeferredBlock<Block> ACACIA_BUTCHERS_TABLE;
	public static final DeferredBlock<Block> BIRCH_BUTCHERS_TABLE;
	public static final DeferredBlock<Block> CRIMSON_BUTCHERS_TABLE;
	public static final DeferredBlock<Block> DARK_OAK_BUTCHERS_TABLE;
	public static final DeferredBlock<Block> JUNGLE_BUTCHERS_TABLE;
	public static final DeferredBlock<Block> MANGROVE_BUTCHERS_TABLE;
	public static final DeferredBlock<Block> SPRUCE_BUTCHERS_TABLE;
	public static final DeferredBlock<Block> WARPED_BUTCHERS_TABLE;
	public static final DeferredBlock<Block> HOOK;
	public static final DeferredBlock<Block> METAL_BUTCHERS_TABLE;
	public static final DeferredBlock<Block> BLOOD_GRATE;
	public static final DeferredBlock<Block> BLOOD;
	public static final DeferredBlock<Block> MEAT_GRINDER;
	public static final DeferredBlock<Block> SKIN_RACK;
	public static final DeferredBlock<Block> SALT_BLOCK;
	public static final DeferredBlock<Block> SALT_FORMATION_TIP;
	public static final DeferredBlock<Block> SALT_FORMATION_BASE;
	public static final DeferredBlock<Block> SALT_FORMATION_MIDDLE;
	public static final DeferredBlock<Block> SALT_FORMATION_FRUSTUM;
	public static final DeferredBlock<Block> BASIN;
	public static final DeferredBlock<Block> BLOOD_PUDDLE;
	public static final DeferredBlock<Block> PIG_CARCASS;
	public static final DeferredBlock<Block> PIG_HEAD;
	public static final DeferredBlock<Block> DRAINED_PIG_CARCASS;
	public static final DeferredBlock<Block> DRAINED_COW_CARCASS;
	public static final DeferredBlock<Block> COW_CARCASS;
	public static final DeferredBlock<Block> COW_HEAD;
	public static final DeferredBlock<Block> SHEEP_CARCASS;
	public static final DeferredBlock<Block> DRAINED_SHEEP_CARCASS;
	public static final DeferredBlock<Block> SHEEP_HEAD;
	public static final DeferredBlock<Block> CHICKEN_CARCASS;
	public static final DeferredBlock<Block> DRAINED_CHICKEN_CARCASS;
	public static final DeferredBlock<Block> CHICKEN_HEAD;
	public static final DeferredBlock<Block> BAT_CARCASS;
	public static final DeferredBlock<Block> BAT_HEAD;
	public static final DeferredBlock<Block> DRAINED_BAT_CARCASS;
	public static final DeferredBlock<Block> DOLPHIN_CARCASS;
	public static final DeferredBlock<Block> DOLPHIN_HEAD;
	public static final DeferredBlock<Block> DRAINED_DOLPHIN_CARCASS;
	public static final DeferredBlock<Block> GLOW_SQUID_CARCASS;
	public static final DeferredBlock<Block> GLOW_SQUID_HEAD;
	public static final DeferredBlock<Block> SQUID_CARCASS;
	public static final DeferredBlock<Block> SQUID_HEAD;
	public static final DeferredBlock<Block> GOAT_CARCASS;
	public static final DeferredBlock<Block> GOAT_HEAD;
	public static final DeferredBlock<Block> DRAINED_GOAT_CARCASS;
	public static final DeferredBlock<Block> RED_MOOSHROOM_CARCASS;
	public static final DeferredBlock<Block> RED_MOOSHROOM_HEAD;
	public static final DeferredBlock<Block> DRAINED_RED_MOOSHROOM_CARCASS;
	public static final DeferredBlock<Block> BROWN_MOOSHROOM_CARCASS;
	public static final DeferredBlock<Block> DRAINED_BROWN_MOOSHROOM_CARCASS;
	public static final DeferredBlock<Block> BROWN_MOOSHROOM_HEAD;
	public static final DeferredBlock<Block> OCELOT_CARCASS;
	public static final DeferredBlock<Block> OCELOT_HEAD;
	public static final DeferredBlock<Block> DRAINED_OCELOT_CARCASS;
	public static final DeferredBlock<Block> CAMEL_CARCASS;
	public static final DeferredBlock<Block> DRAINED_CAMEL_CARCASS;
	public static final DeferredBlock<Block> CAVE_SPIDER_CARCASS;
	public static final DeferredBlock<Block> CAVE_SPIDER_HEAD;
	public static final DeferredBlock<Block> SPIDER_CARCASS;
	public static final DeferredBlock<Block> SPIDER_HEAD;
	public static final DeferredBlock<Block> CAMEL_HEAD;
	public static final DeferredBlock<Block> COD_CARCASS;
	public static final DeferredBlock<Block> SALMON_CARCASS;
	public static final DeferredBlock<Block> CREEPER_CARCASS;
	public static final DeferredBlock<Block> DRAINED_CREEPER_CARCASS;
	public static final DeferredBlock<Block> DONKEY_CARCASS;
	public static final DeferredBlock<Block> DRAINED_DONKEY_CARCASS;
	public static final DeferredBlock<Block> DONKEY_HEAD;
	public static final DeferredBlock<Block> MULE_CARCASS;
	public static final DeferredBlock<Block> MULE_HEAD;
	public static final DeferredBlock<Block> DRAINED_MULE_CARCASS;
	public static final DeferredBlock<Block> DROWNED_CORPSE;
	public static final DeferredBlock<Block> DROWNED_HEAD;
	public static final DeferredBlock<Block> DRAINED_DROWNED_CORPSE;
	public static final DeferredBlock<Block> DRAINED_HUSK_CORPSE;
	public static final DeferredBlock<Block> HUSK_CORPSE;
	public static final DeferredBlock<Block> HUSK_HEAD;
	public static final DeferredBlock<Block> ZOMBIE_CORPSE;
	public static final DeferredBlock<Block> DRAINED_ZOMBIE_CORPSE;
	public static final DeferredBlock<Block> EVOKER_CORPSE;
	public static final DeferredBlock<Block> EVOKER_HEAD;
	public static final DeferredBlock<Block> FOX_CARCASS;
	public static final DeferredBlock<Block> FOX_HEAD;
	public static final DeferredBlock<Block> DRAINED_FOX_CARCASS;
	public static final DeferredBlock<Block> SNOW_FOX_CARCASS;
	public static final DeferredBlock<Block> SNOW_FOX_HEAD;
	public static final DeferredBlock<Block> DRAINED_SNOWFOX_CARCASS;
	public static final DeferredBlock<Block> GUARDIAN_CARCASS;
	public static final DeferredBlock<Block> DRAINED_GUARDIAN_CARCASS;
	public static final DeferredBlock<Block> HOGLIN_CARCASS;
	public static final DeferredBlock<Block> HOGLIN_HEAD;
	public static final DeferredBlock<Block> DRAINED_HOGLIN_CARCASS;
	public static final DeferredBlock<Block> PANDA_CARCASS;
	public static final DeferredBlock<Block> PANDA_HEAD;
	public static final DeferredBlock<Block> DRAINED_PANDA_CARCASS;
	public static final DeferredBlock<Block> PIGLIN_CORPSE;
	public static final DeferredBlock<Block> DRAINED_PIGLIN_CORPSE;
	public static final DeferredBlock<Block> PIGLIN_BRUTE_CORPSE;
	public static final DeferredBlock<Block> PIGLIN_BRUTE_HEAD;
	public static final DeferredBlock<Block> DRAINED_PIGLIN_BRUTE_CORPSE;
	public static final DeferredBlock<Block> DRAINED_EVOKER_CORPSE;
	public static final DeferredBlock<Block> PILLAGER_CORPSE;
	public static final DeferredBlock<Block> PILLAGER_HEAD;
	public static final DeferredBlock<Block> DRAINED_PILLAGER_CORPSE;
	public static final DeferredBlock<Block> VINDICATOR_CORPSE;
	public static final DeferredBlock<Block> VINDICATOR_HEAD;
	public static final DeferredBlock<Block> DRAINED_VINDICATOR_CORPSE;
	public static final DeferredBlock<Block> POLAR_BEAR_CARCASS;
	public static final DeferredBlock<Block> POLAR_BEAR_HEAD;
	public static final DeferredBlock<Block> DRAINED_POLAR_BEAR_CARCASS;
	public static final DeferredBlock<Block> PUFFERFISH;
	public static final DeferredBlock<Block> RABBIT_CARCASS;
	public static final DeferredBlock<Block> RABBIT_HEAD;
	public static final DeferredBlock<Block> DRAINED_RABBIT_CARCASS;
	public static final DeferredBlock<Block> SHULKER_CARCASS;
	public static final DeferredBlock<Block> SILVERFISH_CARCASS;
	public static final DeferredBlock<Block> SKELETON_CORPSE;
	public static final DeferredBlock<Block> STRAY_CORPSE;
	public static final DeferredBlock<Block> STRAY_HEAD;
	public static final DeferredBlock<Block> MEDIUM_SLIME_CARCASS;
	public static final DeferredBlock<Block> SMALL_SLIME_CARCASS;
	public static final DeferredBlock<Block> MEDIUM_MAGMA_CUBE_CARCASS;
	public static final DeferredBlock<Block> MAGMA_CUBE_CARCASS;
	public static final DeferredBlock<Block> STRIDER_CARCASS;
	public static final DeferredBlock<Block> DRAINED_STRIDER_CARCASS;
	public static final DeferredBlock<Block> VILLAGER_CORPSE;
	public static final DeferredBlock<Block> VILLAGER_HEAD;
	public static final DeferredBlock<Block> DRAINED_VILLAGER;
	public static final DeferredBlock<Block> ZOMBIE_VILLAGER_CORPSE;
	public static final DeferredBlock<Block> ZOMBIE_VILLAGER_HEAD;
	public static final DeferredBlock<Block> DRAINED_ZOMBIE_VILLAGER;
	public static final DeferredBlock<Block> ZOMBIFIED_PIGLIN_CORPSE;
	public static final DeferredBlock<Block> DRAINED_ZOMBIFIED_PIGLIN_CORPSE;
	public static final DeferredBlock<Block> ZOMBIFIED_PIGLIN_HEAD;
	public static final DeferredBlock<Block> WITHER_SKELETON_CORPSE;
	public static final DeferredBlock<Block> TURTLE_CARCASS;
	public static final DeferredBlock<Block> TURTLE_HEAD;
	public static final DeferredBlock<Block> DRAINED_TURTLE_CARCASS;
	public static final DeferredBlock<Block> EMPTY_TURTLE_SHELL;
	public static final DeferredBlock<Block> METAL_TRAY;
	public static final DeferredBlock<Block> GRAY_FROG_CARCASS;
	public static final DeferredBlock<Block> DRAINED_GRAY_FROG_CARCASS;
	public static final DeferredBlock<Block> GREEN_FROG_CARCASS;
	public static final DeferredBlock<Block> DRAINED_GREEN_FROG_CARCASS;
	public static final DeferredBlock<Block> ORANGE_FROG_CARCASS;
	public static final DeferredBlock<Block> DRAINED_ORANGE_FROG_CARCASS;
	public static final DeferredBlock<Block> BROWN_LLAMA_CARCASS;
	public static final DeferredBlock<Block> DRAINED_BROWN_LLAMA_CARCASS;
	public static final DeferredBlock<Block> BROWN_LLAMA_HEAD;
	public static final DeferredBlock<Block> CREAMY_LLAMA_CARCASS;
	public static final DeferredBlock<Block> DRAINED_CREAMY_LLAMA_CARCASS;
	public static final DeferredBlock<Block> CREAMY_LLAMA_HEAD;
	public static final DeferredBlock<Block> GRAY_LLAMA_CARCASS;
	public static final DeferredBlock<Block> DRAINED_GRAY_LLAMA_CARCASS;
	public static final DeferredBlock<Block> GRAY_LLAMA_HEAD;
	public static final DeferredBlock<Block> DRAINED_WHITE_LLAMA_CARCASS;
	public static final DeferredBlock<Block> WHITE_LLAMA_HEAD;
	public static final DeferredBlock<Block> WHITE_LLAMA_CARCASS;
	public static final DeferredBlock<Block> FREEZER;
	public static final DeferredBlock<Block> TAXIDERMY_TABLE;
	public static final DeferredBlock<Block> BROWN_LLAMA_HEAD_MOUNT;
	public static final DeferredBlock<Block> CAMEL_HEAD_MOUNT;
	public static final DeferredBlock<Block> CAVE_SPIDER_HEAD_MOUNT;
	public static final DeferredBlock<Block> CHICKEN_HEAD_MOUNT;
	public static final DeferredBlock<Block> COW_HEAD_MOUNT;
	public static final DeferredBlock<Block> CREAMY_LLAMA_HEAD_MOUNT;
	public static final DeferredBlock<Block> CREEPER_HEAD_MOUNT;
	public static final DeferredBlock<Block> DOLPHIN_HEAD_MOUNT;
	public static final DeferredBlock<Block> DROWNED_HEAD_MOUNT;
	public static final DeferredBlock<Block> EMPTY_HEAD_MOUNT;
	public static final DeferredBlock<Block> ENDERMAN_HEAD_MOUNT;
	public static final DeferredBlock<Block> FOX_HEAD_MOUNT;
	public static final DeferredBlock<Block> GOAT_HEAD_MOUNT;
	public static final DeferredBlock<Block> GRAY_LLAMA_HEAD_MOUNT;
	public static final DeferredBlock<Block> HOGLIN_HEAD_MOUNT;
	public static final DeferredBlock<Block> HUSK_HEAD_MOUNT;
	public static final DeferredBlock<Block> LARGE_EMPTY_HEAD_MOUNT;
	public static final DeferredBlock<Block> PANDA_HEAD_MOUNT;
	public static final DeferredBlock<Block> PIG_HEAD_MOUNT;
	public static final DeferredBlock<Block> PILLAGER_HEAD_MOUNT;
	public static final DeferredBlock<Block> POLARBEAR_HEAD_MOUNT;
	public static final DeferredBlock<Block> SHEEP_HEAD_MOUNT;
	public static final DeferredBlock<Block> SKELETON_HEAD_MOUNT;
	public static final DeferredBlock<Block> SNOWY_FOX_HEAD_MOUNT;
	public static final DeferredBlock<Block> SPIDER_HEAD_MOUNT;
	public static final DeferredBlock<Block> VILLAGER_HEAD_MOUNT;
	public static final DeferredBlock<Block> WHITE_LLAMA_HEAD_MOUNT;
	public static final DeferredBlock<Block> ZOMBIE_HEAD_MOUNT;
	public static final DeferredBlock<Block> ZOMBIE_VILLAGER_HEAD_MOUNT;
	public static final DeferredBlock<Block> OCELOT_HEAD_MOUNT;
	public static final DeferredBlock<Block> CANOPY_BLACK;
	public static final DeferredBlock<Block> CANOPY_BLUE;
	public static final DeferredBlock<Block> CANOPY_BROWN;
	public static final DeferredBlock<Block> CANOPY_CYAN;
	public static final DeferredBlock<Block> CANOPY_GRAY;
	public static final DeferredBlock<Block> CANOPY_GREEN;
	public static final DeferredBlock<Block> CANOPY_LIGHT_BLUE;
	public static final DeferredBlock<Block> CANOPY_LIGHT_GRAY;
	public static final DeferredBlock<Block> CANOPY_LIME;
	public static final DeferredBlock<Block> CANOPY_MAGENTA;
	public static final DeferredBlock<Block> CANOPY_ORANGE;
	public static final DeferredBlock<Block> CANOPY_PINK;
	public static final DeferredBlock<Block> CANOPY_PURPLE;
	public static final DeferredBlock<Block> CANOPY_RED;
	public static final DeferredBlock<Block> CANOPY_YELLOW;
	public static final DeferredBlock<Block> FLOORSTANDING_SIGN;
	public static final DeferredBlock<Block> BUTCHER_STATUE;
	public static final DeferredBlock<Block> DIORITE_BRICK_SLAB;
	public static final DeferredBlock<Block> DIORITE_BRICK_WALL;
	public static final DeferredBlock<Block> DIORITE_BRICKS;
	public static final DeferredBlock<Block> DIORITE_BRICK_STAIRS;
	public static final DeferredBlock<Block> ROPE;
	public static final DeferredBlock<Block> SAND;
	public static final DeferredBlock<Block> ENDER_DRAGON_CARCASS;
	public static final DeferredBlock<Block> DRAGON_SCALE_BLOCK;
	public static final DeferredBlock<Block> ENDER_DRAGON_CARCASS_HEADLESS;
	public static final DeferredBlock<Block> ENDERDRAGONCUT_1;
	public static final DeferredBlock<Block> ENDERDRAGONCUT_2;
	public static final DeferredBlock<Block> ENDERDRAGONCUT_3;
	public static final DeferredBlock<Block> ENDERDRAGONCUT_4;
	public static final DeferredBlock<Block> ENDERDRAGONCUT_5;
	public static final DeferredBlock<Block> ENDERDRAGONCUT_6;
	public static final DeferredBlock<Block> ENDERDRAGONCUT_7;
	public static final DeferredBlock<Block> ENDERDRAGONCUT_8;
	public static final DeferredBlock<Block> ENDERDRAGONCUT_9;
	public static final DeferredBlock<Block> ENDERDRAGONCUT_10;
	public static final DeferredBlock<Block> ENDERDRAGONCUT_11;
	public static final DeferredBlock<Block> ENDERDRAGONCUT_12;
	public static final DeferredBlock<Block> ENDERDRAGONCUT_13;
	public static final DeferredBlock<Block> ENDERDRAGONCUT_14;
	public static final DeferredBlock<Block> WOODEN_SPIT_ROTISSERIE;
	public static final DeferredBlock<Block> POLARBEAR_RUG;
	public static final DeferredBlock<Block> GOAT_RUG;
	public static final DeferredBlock<Block> PANDA_RUG;
	public static final DeferredBlock<Block> CASH_REGISTER_BLOCK;
	public static final DeferredBlock<Block> ACACIA_BUTCHER_DISPLAY;
	public static final DeferredBlock<Block> BIRCH_BUTCHER_DISPLAY;
	public static final DeferredBlock<Block> CRIMSON_BUTCHER_DISPLAY;
	public static final DeferredBlock<Block> DARK_OAK_BUTCHER_DISPLAY;
	public static final DeferredBlock<Block> JUNGLE_BUTCHER_DISPLAY;
	public static final DeferredBlock<Block> OAK_BUTCHER_DISPLAY;
	public static final DeferredBlock<Block> SPRUCE_BUTCHER_DISPLAY;
	public static final DeferredBlock<Block> WARPED_BUTCHER_DISPLAY;
	public static final DeferredBlock<Block> ACACIA_COUNTER;
	public static final DeferredBlock<Block> BIRCH_COUNTER;
	public static final DeferredBlock<Block> CRIMSON_COUNTER;
	public static final DeferredBlock<Block> DARK_OAK_COUNTER;
	public static final DeferredBlock<Block> JUNGLE_COUNTER;
	public static final DeferredBlock<Block> OAK_COUNTER;
	public static final DeferredBlock<Block> SPRUCE_COUNTER;
	public static final DeferredBlock<Block> WARPED_COUNTER;
	public static final DeferredBlock<Block> BLOOD_SPLATTER;
	public static final DeferredBlock<Block> BONE_BARREL;
	public static final DeferredBlock<Block> COD_BARREL;
	public static final DeferredBlock<Block> SALMON_BARREL;
	public static final DeferredBlock<Block> PINK_AXOLOTL_CARCASS;
	public static final DeferredBlock<Block> DRAINED_PINK_AXOLOTL_CARCASS;
	public static final DeferredBlock<Block> BLUE_AXOLOTL_CARCASS;
	public static final DeferredBlock<Block> DRAINED_BLUE_AXOLOTL_CARCASS;
	public static final DeferredBlock<Block> BROWN_AXOLOTL_CARCASS;
	public static final DeferredBlock<Block> DRAINED_BROWN_AXOLOTL_CARCASS;
	public static final DeferredBlock<Block> CYAN_AXOLOTL_CARCASS;
	public static final DeferredBlock<Block> DRAINED_CYAN_AXOLOTL_CARCASS;
	public static final DeferredBlock<Block> GOLD_AXOLOTL_CARCASS;
	public static final DeferredBlock<Block> DRAINED_GOLD_AXOLOTL_CARCASS;
	public static final DeferredBlock<Block> PINK_AXOLOTL_HEAD;
	public static final DeferredBlock<Block> BLUE_AXOLOTL_HEAD;
	public static final DeferredBlock<Block> CYAN_AXOLOTL_HEAD;
	public static final DeferredBlock<Block> GOLD_AXOLOTL_HEAD;
	public static final DeferredBlock<Block> BROWN_AXOLOTL_HEAD;
	public static final DeferredBlock<Block> BLUE_AXOLOTL_HEAD_MOUNT;
	public static final DeferredBlock<Block> BROWN_AXOLOTL_HEAD_MOUNT;
	public static final DeferredBlock<Block> CYAN_AXOLOTL_HEAD_MOUNT;
	public static final DeferredBlock<Block> GOLD_AXOLOTL_HEAD_MOUNT;
	public static final DeferredBlock<Block> PINK_AXOLOTL_HEAD_MOUNT;
	public static final DeferredBlock<Block> BAT_HEAD_MOUNT;
	public static final DeferredBlock<Block> DONKEY_HEAD_MOUNT;
	public static final DeferredBlock<Block> MULE_HEAD_MOUNT;
	public static final DeferredBlock<Block> EVOKER_HEAD_MOUNT;
	public static final DeferredBlock<Block> VINDICATOR_HEAD_MOUNT;
	public static final DeferredBlock<Block> RED_MOOSHROOM_HEAD_MOUNT;
	public static final DeferredBlock<Block> BROWN_MOOSHROOM_HEAD_MOUNT;
	public static final DeferredBlock<Block> PIGLIN_HEAD_MOUNT;
	public static final DeferredBlock<Block> PIGLIN_BRUTE_HEAD_MOUNT;
	public static final DeferredBlock<Block> ZOMBIFIED_PIGLIN_HEAD_MOUNT;
	public static final DeferredBlock<Block> RABBIT_HEAD_MOUNT;
	public static final DeferredBlock<Block> STRAY_HEAD_MOUNT;
	public static final DeferredBlock<Block> TURTLE_HEAD_MOUNT;
	public static final DeferredBlock<Block> WITHER_SKELETON_HEAD_MOUNT;
	public static final DeferredBlock<Block> HANGING_ENDERMAN_CARCASS;
	public static final DeferredBlock<Block> ENDERMAN_CARCASS;
	public static final DeferredBlock<Block> DRAINED_ENDERMAN_CARCASS;
	public static final DeferredBlock<Block> ENDERMAN_HEAD;
	public static final DeferredBlock<Block> HANGING_DRAINED_ENDERMAN_CARCASS;
	public static final DeferredBlock<Block> ENDERMITE_CARCASS;
	public static final DeferredBlock<Block> ENDERMITE_HEAD_MOUNT;
	public static final DeferredBlock<Block> SILVERFISH_HEAD_MOUNT;
	public static final DeferredBlock<Block> ENDERMITE_HEAD;
	public static final DeferredBlock<Block> SILVERFISH_HEAD;
	public static final DeferredBlock<Block> SMALL_EMPTY_HEAD_MOUNT;
	public static final DeferredBlock<Block> PHANTOM_CARCASS;
	public static final DeferredBlock<Block> DRAINED_PHANTOM_CARCASS;
	public static final DeferredBlock<Block> PHANTOM_HEAD;
	public static final DeferredBlock<Block> PHANTOM_HEAD_MOUNT;
	public static final DeferredBlock<Block> ALL_BLACK_CAT_CARCASS;
	public static final DeferredBlock<Block> DRAINED_ALL_BLACK_CAT_CARCASS;
	public static final DeferredBlock<Block> BLACK_CAT_CARCASS;
	public static final DeferredBlock<Block> DRAINED_BLACK_CAT_CARCASS;
	public static final DeferredBlock<Block> BRITISH_SHORTHAIR_CAT_CARCASS;
	public static final DeferredBlock<Block> DRAINED_BRITISH_SHORTHAIR_CAT_CARCASS;
	public static final DeferredBlock<Block> CALICO_CAT_CARCASS;
	public static final DeferredBlock<Block> DRAINED_CALICO_CAT_CARCASS;
	public static final DeferredBlock<Block> JELLIE_CAT_CARCASS;
	public static final DeferredBlock<Block> DRAINED_JELLIE_CAT_CARCASS;
	public static final DeferredBlock<Block> PERSIAN_CAT_CARCASS;
	public static final DeferredBlock<Block> DRAINED_PERSIAN_CAT_CARCASS;
	public static final DeferredBlock<Block> RAGDOLL_CAT_CARCASS;
	public static final DeferredBlock<Block> DRAINED_RAGDOLL_CAT_CARCASS;
	public static final DeferredBlock<Block> RED_CAT_CARCASS;
	public static final DeferredBlock<Block> DRAINED_RED_CAT_CARCASS;
	public static final DeferredBlock<Block> SIAMESE_CAT_CARCASS;
	public static final DeferredBlock<Block> DRAINED_SIAMESE_CAT_CARCASS;
	public static final DeferredBlock<Block> TABBY_CAT_CARCASS;
	public static final DeferredBlock<Block> DRAINED_TABBY_CAT_CARCASS;
	public static final DeferredBlock<Block> WHITE_CAT_CARCASS;
	public static final DeferredBlock<Block> DRAINED_WHITE_CAT_CARCASS;
	public static final DeferredBlock<Block> BLACK_CAT_HEAD;
	public static final DeferredBlock<Block> ALL_BLACK_CAT_HEAD;
	public static final DeferredBlock<Block> TABBY_CAT_HEAD;
	public static final DeferredBlock<Block> RED_CAT_HEAD;
	public static final DeferredBlock<Block> SIAMESE_CAT_HEAD;
	public static final DeferredBlock<Block> SHORTHAIR_CAT_HEAD;
	public static final DeferredBlock<Block> RAGDOLL_CAT_HEAD;
	public static final DeferredBlock<Block> JELLIE_CAT_HEAD;
	public static final DeferredBlock<Block> WHITE_CAT_HEAD;
	public static final DeferredBlock<Block> PERSIAN_CAT_HEAD;
	public static final DeferredBlock<Block> CALICO_CAT_HEAD;
	public static final DeferredBlock<Block> CAT_CARCASS;
	public static final DeferredBlock<Block> ELDER_GUARDIAN_CARCASS;
	public static final DeferredBlock<Block> WITCH_CORPSE;
	public static final DeferredBlock<Block> DRAINED_WITCH_CORPSE;
	public static final DeferredBlock<Block> WITCH_HEAD;
	public static final DeferredBlock<Block> IRON_GOLEM;
	public static final DeferredBlock<Block> IRON_GOLEM_HEAD;
	public static final DeferredBlock<Block> IRON_GOLEM_ARMS;
	public static final DeferredBlock<Block> IRON_GOLEM_LEGS;
	public static final DeferredBlock<Block> IRON_GOLEM_BODY;
	public static final DeferredBlock<Block> REPAIRED_IRON_GOLEM_HEAD;
	public static final DeferredBlock<Block> REPAIRED_IRON_GOLEM_ARMS;
	public static final DeferredBlock<Block> REPAIRED_IRON_GOLEM_LEGS;
	public static final DeferredBlock<Block> REPAIRED_IRON_GOLEM_BODY;
	public static final DeferredBlock<Block> ALL_BLACK_CAT_HEAD_MOUNT;
	public static final DeferredBlock<Block> BLACK_CAT_HEAD_MOUNT;
	public static final DeferredBlock<Block> TABBY_CAT_HEAD_MOUNT;
	public static final DeferredBlock<Block> RED_CAT_HEAD_MOUNT;
	public static final DeferredBlock<Block> SIAMESE_CAT_HEAD_MOUNT;
	public static final DeferredBlock<Block> SHORTHAIR_CAT_HEAD_MOUNT;
	public static final DeferredBlock<Block> RAGDOLL_CAT_HEAD_MOUNT;
	public static final DeferredBlock<Block> JELLIE_CAT_HEAD_MOUNT;
	public static final DeferredBlock<Block> WHITE_CAT_HEAD_MOUNT;
	public static final DeferredBlock<Block> PERSIAN_CAT_HEAD_MOUNT;
	public static final DeferredBlock<Block> CALICO_CAT_HEAD_MOUNT;
	public static final DeferredBlock<Block> IRON_GOLEM_HEAD_MOUNT;
	public static final DeferredBlock<Block> REPAIRED_IRON_GOLEM_HEAD_MOUNT;
	public static final DeferredBlock<Block> WITCH_HEAD_MOUNT;
	public static final DeferredBlock<Block> WITHER_CARCASS;
	public static final DeferredBlock<Block> ZOGLIN_CARCASS;
	public static final DeferredBlock<Block> ZOGLIN_HEAD;
	public static final DeferredBlock<Block> DRAINED_ZOGLIN_CARCASS;
	public static final DeferredBlock<Block> ZOGLIN_HEAD_MOUNT;
	public static final DeferredBlock<Block> WOLF_CARCASS;
	public static final DeferredBlock<Block> WOLF_HEAD;
	public static final DeferredBlock<Block> DRAINED_WOLF_CARCASS;
	public static final DeferredBlock<Block> WOLF_HEAD_MOUNT;
	public static final DeferredBlock<Block> SKELETON_HORSE_CARCASS;
	public static final DeferredBlock<Block> SKELETON_HORSE_HEAD;
	public static final DeferredBlock<Block> SKELETON_HORSE_HEAD_MOUNT;
	public static final DeferredBlock<Block> WARDEN_CARCASS;
	public static final DeferredBlock<Block> WARDEN_HEAD;
	public static final DeferredBlock<Block> ZOMBIE_HORSE_CARCASS;
	public static final DeferredBlock<Block> ZOMBIE_HORSE_HEAD;
	public static final DeferredBlock<Block> DRAINED_ZOMBIE_HORSE_CARCASS;
	public static final DeferredBlock<Block> ZOMBIE_HORSE_HEAD_MOUNT;
	public static final DeferredBlock<Block> SPIKE_TRAP;
	public static final DeferredBlock<Block> BRAIN;
	public static final DeferredBlock<Block> RAW_SAUSAGES;
	public static final DeferredBlock<Block> COOKED_SAUSAGES;
	public static final DeferredBlock<Block> RAW_BLOOD_SAUSAGES;
	public static final DeferredBlock<Block> COOKED_BLOOD_SAUSAGES;
	public static final DeferredBlock<Block> BEE_CARCASS;
	public static final DeferredBlock<Block> BEE_HEAD;
	public static final DeferredBlock<Block> SNIFFER_CARCASS_BLOCK;
	public static final DeferredBlock<Block> DRAINED_SNIFFER_CARCASS_BLOCK;
	public static final DeferredBlock<Block> SNIFFER_HEAD;
	public static final DeferredBlock<Block> ENDER_DRAGON_HEAD_MOUNT;
	public static final DeferredBlock<Block> EMPTY_DRAGON_TRIMMED_HEAD_MOUNT;
	public static final DeferredBlock<Block> TRIMMED_ENDER_DRAGON_HEAD_MOUNT;
	public static final DeferredBlock<Block> REPAIRED_IRONGOLEM;
	public static final DeferredBlock<Block> REGULAR_BLACK_HORSE_CARCASS;
	public static final DeferredBlock<Block> BLACK_HORSE_HEAD;
	public static final DeferredBlock<Block> DRAINED_REGULAR_BLACK_HORSE_CARCASS;
	public static final DeferredBlock<Block> BROWN_HORSE_HEAD;
	public static final DeferredBlock<Block> REGULAR_BROWN_HORSE_CARCASS;
	public static final DeferredBlock<Block> DRAINED_REGULAR_BROWN_HORSE_CARCASS;
	public static final DeferredBlock<Block> CHESTNUT_HORSE_HEAD;
	public static final DeferredBlock<Block> REGULAR_CHESTNUT_HORSE_CARCASS;
	public static final DeferredBlock<Block> DRAINED_REGULAR_CHESTNUT_HORSE_CARCASS;
	public static final DeferredBlock<Block> CREAMY_HORSE_HEAD;
	public static final DeferredBlock<Block> REGULAR_CREAMY_HORSE_CARCASS;
	public static final DeferredBlock<Block> DRAINED_REGULAR_CREAMY_HORSE_CARCASS;
	public static final DeferredBlock<Block> DARK_BROWN_HORSE_HEAD;
	public static final DeferredBlock<Block> REGULAR_DARK_BROWN_HORSE_CARCASS;
	public static final DeferredBlock<Block> DRAINED_REGULAR_DARK_BROWN_HORSE_CARCASS;
	public static final DeferredBlock<Block> GRAY_HORSE_HEAD;
	public static final DeferredBlock<Block> REGULAR_GRAY_HORSE_CARCASS;
	public static final DeferredBlock<Block> WHITE_HORSE_HEAD;
	public static final DeferredBlock<Block> REGULAR_WHITE_HORSE_CARCASS;
	public static final DeferredBlock<Block> DRAINED_GRAY_HORSE_CARCASS;
	public static final DeferredBlock<Block> DRAINED_WHITE_HORSE_CARCASS;
	public static final DeferredBlock<Block> PLASTIC_SHEET;
	public static final DeferredBlock<Block> PLASTIC_SHEET_CORNER;
	public static final DeferredBlock<Block> CLING_FILM;
	public static final DeferredBlock<Block> PHOTOS;
	public static final DeferredBlock<Block> INFECTED_BLOOD;
	public static final DeferredBlock<Block> SULFUR_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_SULFUR_ORE;
	public static final DeferredBlock<Block> BLACK_HORSE_HEAD_MOUNT;
	public static final DeferredBlock<Block> BROWN_HORSE_HEAD_MOUNT;
	public static final DeferredBlock<Block> CHESTNUT_HORSE_HEAD_MOUNT;
	public static final DeferredBlock<Block> CREAMY_HORSE_HEAD_MOUNT;
	public static final DeferredBlock<Block> DARK_BROWN_HORSE_HEAD_MOUNT;
	public static final DeferredBlock<Block> GRAY_HORSE_HEAD_MOUNT;
	public static final DeferredBlock<Block> WHITE_HORSE_HEAD_MOUNT;
	public static final DeferredBlock<Block> PESTLE_AND_MORTAR;
	public static final DeferredBlock<Block> EMPTY_WARDEN_TRIMMED_HEAD_MOUNT;
	public static final DeferredBlock<Block> WARDEN_HEAD_MOUNT;
	public static final DeferredBlock<Block> TRIMMED_WARDEN_HEAD_MOUNT;
	public static final DeferredBlock<Block> AXOLOTL_SKELETON;
	public static final DeferredBlock<Block> BAT_SKELETON;
	public static final DeferredBlock<Block> MOOSHROOM_SKELETON;
	public static final DeferredBlock<Block> CAMEL_SKELETON;
	public static final DeferredBlock<Block> CAT_SKELETON;
	public static final DeferredBlock<Block> CHICKEN_SKELETON;
	public static final DeferredBlock<Block> FISH_SKELETON;
	public static final DeferredBlock<Block> COW_SKELETON;
	public static final DeferredBlock<Block> CREEPER_SKELETON;
	public static final DeferredBlock<Block> DOLPHIN_SKELETON;
	public static final DeferredBlock<Block> DONKEY_SKELETON;
	public static final DeferredBlock<Block> SKELETON;
	public static final DeferredBlock<Block> FOX_SKELETON;
	public static final DeferredBlock<Block> GOAT_SKELETON;
	public static final DeferredBlock<Block> HOGLIN_SKELETON;
	public static final DeferredBlock<Block> LLAMA_SKELETON;
	public static final DeferredBlock<Block> MULE_SKELETON;
	public static final DeferredBlock<Block> OCELOT_SKELETON;
	public static final DeferredBlock<Block> PANDA_SKELETON;
	public static final DeferredBlock<Block> PHANTOM_SKELETON;
	public static final DeferredBlock<Block> PIG_SKELETON;
	public static final DeferredBlock<Block> PIGLIN_SKELETON;
	public static final DeferredBlock<Block> POLARBEAR_SKELETON;
	public static final DeferredBlock<Block> SHEEP_SKELETON;
	public static final DeferredBlock<Block> WOLF_SKELETON;
	public static final DeferredBlock<Block> PLAYERCORPSE;
	public static final DeferredBlock<Block> DRAINEDPLAYERCORPSE;
	public static final DeferredBlock<Block> JAR;
	public static final DeferredBlock<Block> RAVAGER_HEAD;
	public static final DeferredBlock<Block> RAVAGER;
	public static final DeferredBlock<Block> RAVAGER_HEAD_MOUNT;
	static {
		OAK_BUTCHERS_TABLE = register("oak_butchers_table", OakbutcherstableBlock::new);
		ACACIA_BUTCHERS_TABLE = register("acacia_butchers_table", AcaciabutcherstableBlock::new);
		BIRCH_BUTCHERS_TABLE = register("birch_butchers_table", BirchbutcherstableBlock::new);
		CRIMSON_BUTCHERS_TABLE = register("crimson_butchers_table", CrimsonbutcherstableBlock::new);
		DARK_OAK_BUTCHERS_TABLE = register("dark_oak_butchers_table", DarkoakbutcherstableBlock::new);
		JUNGLE_BUTCHERS_TABLE = register("jungle_butchers_table", JunglebutcherstableBlock::new);
		MANGROVE_BUTCHERS_TABLE = register("mangrove_butchers_table", MangrovebutcherstableBlock::new);
		SPRUCE_BUTCHERS_TABLE = register("spruce_butchers_table", SprucebutcherstableBlock::new);
		WARPED_BUTCHERS_TABLE = register("warped_butchers_table", WarpedbutcherstableBlock::new);
		HOOK = register("hook", HookBlock::new);
		METAL_BUTCHERS_TABLE = register("metal_butchers_table", MetalbutcherstableBlock::new);
		BLOOD_GRATE = register("blood_grate", BloodgrateBlock::new);
		BLOOD = register("blood", BloodBlock::new);
		MEAT_GRINDER = register("meat_grinder", MeatgrinderBlock::new);
		SKIN_RACK = register("skin_rack", SkinrackBlock::new);
		SALT_BLOCK = register("salt_block", SaltblockBlock::new);
		SALT_FORMATION_TIP = register("salt_formation_tip", SaltformationtipBlock::new);
		SALT_FORMATION_BASE = register("salt_formation_base", SaltformationbaseBlock::new);
		SALT_FORMATION_MIDDLE = register("salt_formation_middle", SaltformationmiddleBlock::new);
		SALT_FORMATION_FRUSTUM = register("salt_formation_frustum", SaltformationfrustumBlock::new);
		BASIN = register("basin", BasinBlock::new);
		BLOOD_PUDDLE = register("blood_puddle", BloodpuddleBlock::new);
		PIG_CARCASS = register("pig_carcass", PigcarcassBlock::new);
		PIG_HEAD = register("pig_head", PigheadBlock::new);
		DRAINED_PIG_CARCASS = register("drained_pig_carcass", DrainedpigcarcassBlock::new);
		DRAINED_COW_CARCASS = register("drained_cow_carcass", DrainedcowcarcassBlock::new);
		COW_CARCASS = register("cow_carcass", CowcarcassBlock::new);
		COW_HEAD = register("cow_head", CowheadBlock::new);
		SHEEP_CARCASS = register("sheep_carcass", SheepcarcassBlock::new);
		DRAINED_SHEEP_CARCASS = register("drained_sheep_carcass", DrainedSheepcarcassBlock::new);
		SHEEP_HEAD = register("sheep_head", SheepheadBlock::new);
		CHICKEN_CARCASS = register("chicken_carcass", ChickencarcassBlock::new);
		DRAINED_CHICKEN_CARCASS = register("drained_chicken_carcass", DrainedchickencarcassBlock::new);
		CHICKEN_HEAD = register("chicken_head", ChickenheadBlock::new);
		BAT_CARCASS = register("bat_carcass", BatcarcassBlock::new);
		BAT_HEAD = register("bat_head", BatheadBlock::new);
		DRAINED_BAT_CARCASS = register("drained_bat_carcass", DrainedbatcarcassBlock::new);
		DOLPHIN_CARCASS = register("dolphin_carcass", DolphincarcassBlock::new);
		DOLPHIN_HEAD = register("dolphin_head", DolphinheadBlock::new);
		DRAINED_DOLPHIN_CARCASS = register("drained_dolphin_carcass", DraineddolphincarcassBlock::new);
		GLOW_SQUID_CARCASS = register("glow_squid_carcass", GlowsquidcarcassBlock::new);
		GLOW_SQUID_HEAD = register("glow_squid_head", GlowsquidheadBlock::new);
		SQUID_CARCASS = register("squid_carcass", SquidcarcassBlock::new);
		SQUID_HEAD = register("squid_head", SquidheadBlock::new);
		GOAT_CARCASS = register("goat_carcass", GoatcarcassBlock::new);
		GOAT_HEAD = register("goat_head", GoatheadBlock::new);
		DRAINED_GOAT_CARCASS = register("drained_goat_carcass", DrainedgoatcarcassBlock::new);
		RED_MOOSHROOM_CARCASS = register("red_mooshroom_carcass", RedmooshroomcarcassBlock::new);
		RED_MOOSHROOM_HEAD = register("red_mooshroom_head", RedmooshroomheadBlock::new);
		DRAINED_RED_MOOSHROOM_CARCASS = register("drained_red_mooshroom_carcass", DrainedredmooshroomcarcassBlock::new);
		BROWN_MOOSHROOM_CARCASS = register("brown_mooshroom_carcass", BrownmooshroomcarcassBlock::new);
		DRAINED_BROWN_MOOSHROOM_CARCASS = register("drained_brown_mooshroom_carcass", DrainedbrownmooshroomcarcassBlock::new);
		BROWN_MOOSHROOM_HEAD = register("brown_mooshroom_head", BrownmooshroomheadBlock::new);
		OCELOT_CARCASS = register("ocelot_carcass", OcelotcarcassBlock::new);
		OCELOT_HEAD = register("ocelot_head", OcelotheadBlock::new);
		DRAINED_OCELOT_CARCASS = register("drained_ocelot_carcass", DrainedocelotcarcassBlock::new);
		CAMEL_CARCASS = register("camel_carcass", CamelcarcassBlock::new);
		DRAINED_CAMEL_CARCASS = register("drained_camel_carcass", DrainedcamelcarcassBlock::new);
		CAVE_SPIDER_CARCASS = register("cave_spider_carcass", CavespidercarcassBlock::new);
		CAVE_SPIDER_HEAD = register("cave_spider_head", CavespiderheadBlock::new);
		SPIDER_CARCASS = register("spider_carcass", SpidercarcassBlock::new);
		SPIDER_HEAD = register("spider_head", SpiderheadBlock::new);
		CAMEL_HEAD = register("camel_head", CamelheadBlock::new);
		COD_CARCASS = register("cod_carcass", CodcarcassBlock::new);
		SALMON_CARCASS = register("salmon_carcass", SalmoncarcassBlock::new);
		CREEPER_CARCASS = register("creeper_carcass", CreepercarcassBlock::new);
		DRAINED_CREEPER_CARCASS = register("drained_creeper_carcass", DrainedcreepercarcassBlock::new);
		DONKEY_CARCASS = register("donkey_carcass", DonkeycarcassBlock::new);
		DRAINED_DONKEY_CARCASS = register("drained_donkey_carcass", DraineddonkeycarcassBlock::new);
		DONKEY_HEAD = register("donkey_head", DonkeyheadBlock::new);
		MULE_CARCASS = register("mule_carcass", MulecarcassBlock::new);
		MULE_HEAD = register("mule_head", MuleheadBlock::new);
		DRAINED_MULE_CARCASS = register("drained_mule_carcass", DrainedmulecarcassBlock::new);
		DROWNED_CORPSE = register("drowned_corpse", DrownedcorpseBlock::new);
		DROWNED_HEAD = register("drowned_head", DrownedheadBlock::new);
		DRAINED_DROWNED_CORPSE = register("drained_drowned_corpse", DraineddrownedcorpseBlock::new);
		DRAINED_HUSK_CORPSE = register("drained_husk_corpse", DrainedhuskcorpseBlock::new);
		HUSK_CORPSE = register("husk_corpse", HuskcorpseBlock::new);
		HUSK_HEAD = register("husk_head", HuskheadBlock::new);
		ZOMBIE_CORPSE = register("zombie_corpse", ZombiecorpseBlock::new);
		DRAINED_ZOMBIE_CORPSE = register("drained_zombie_corpse", DrainedzombiecorpseBlock::new);
		EVOKER_CORPSE = register("evoker_corpse", EvokercorpseBlock::new);
		EVOKER_HEAD = register("evoker_head", EvokerheadBlock::new);
		FOX_CARCASS = register("fox_carcass", FoxcarcassBlock::new);
		FOX_HEAD = register("fox_head", FoxheadBlock::new);
		DRAINED_FOX_CARCASS = register("drained_fox_carcass", DrainedfoxcarcassBlock::new);
		SNOW_FOX_CARCASS = register("snow_fox_carcass", SnowfoxcarcassBlock::new);
		SNOW_FOX_HEAD = register("snow_fox_head", SnowfoxheadBlock::new);
		DRAINED_SNOWFOX_CARCASS = register("drained_snowfox_carcass", DrainedSnowfoxcarcassBlock::new);
		GUARDIAN_CARCASS = register("guardian_carcass", GuardiancarcassBlock::new);
		DRAINED_GUARDIAN_CARCASS = register("drained_guardian_carcass", DrainedguardiancarcassBlock::new);
		HOGLIN_CARCASS = register("hoglin_carcass", HoglincarcassBlock::new);
		HOGLIN_HEAD = register("hoglin_head", HoglinheadBlock::new);
		DRAINED_HOGLIN_CARCASS = register("drained_hoglin_carcass", DrainedhoglincarcassBlock::new);
		PANDA_CARCASS = register("panda_carcass", PandacarcassBlock::new);
		PANDA_HEAD = register("panda_head", PandaheadBlock::new);
		DRAINED_PANDA_CARCASS = register("drained_panda_carcass", DrainedpandacarcassBlock::new);
		PIGLIN_CORPSE = register("piglin_corpse", PiglincorpseBlock::new);
		DRAINED_PIGLIN_CORPSE = register("drained_piglin_corpse", DrainedpiglincorpseBlock::new);
		PIGLIN_BRUTE_CORPSE = register("piglin_brute_corpse", PiglinbrutecorpseBlock::new);
		PIGLIN_BRUTE_HEAD = register("piglin_brute_head", PiglinbruteheadBlock::new);
		DRAINED_PIGLIN_BRUTE_CORPSE = register("drained_piglin_brute_corpse", DrainedPiglinbrutecorpseBlock::new);
		DRAINED_EVOKER_CORPSE = register("drained_evoker_corpse", DrainedevokercorpseBlock::new);
		PILLAGER_CORPSE = register("pillager_corpse", PillagercorpseBlock::new);
		PILLAGER_HEAD = register("pillager_head", PillagerheadBlock::new);
		DRAINED_PILLAGER_CORPSE = register("drained_pillager_corpse", DrainedPillagercorpseBlock::new);
		VINDICATOR_CORPSE = register("vindicator_corpse", VindicatorcorpseBlock::new);
		VINDICATOR_HEAD = register("vindicator_head", VindicatorheadBlock::new);
		DRAINED_VINDICATOR_CORPSE = register("drained_vindicator_corpse", DrainedVindicatorcorpseBlock::new);
		POLAR_BEAR_CARCASS = register("polar_bear_carcass", PolarbearcarcassBlock::new);
		POLAR_BEAR_HEAD = register("polar_bear_head", PolarbearheadBlock::new);
		DRAINED_POLAR_BEAR_CARCASS = register("drained_polar_bear_carcass", DrainedPolarbearcarcassBlock::new);
		PUFFERFISH = register("pufferfish", PufferfishBlock::new);
		RABBIT_CARCASS = register("rabbit_carcass", RabbitcarcassBlock::new);
		RABBIT_HEAD = register("rabbit_head", RabbitheadBlock::new);
		DRAINED_RABBIT_CARCASS = register("drained_rabbit_carcass", DrainedrabbitcarcassBlock::new);
		SHULKER_CARCASS = register("shulker_carcass", ShulkercarcassBlock::new);
		SILVERFISH_CARCASS = register("silverfish_carcass", SilverfishcarcassBlock::new);
		SKELETON_CORPSE = register("skeleton_corpse", SkeletoncorpseBlock::new);
		STRAY_CORPSE = register("stray_corpse", StraycorpseBlock::new);
		STRAY_HEAD = register("stray_head", StrayheadBlock::new);
		MEDIUM_SLIME_CARCASS = register("medium_slime_carcass", MediumslimecarcassBlock::new);
		SMALL_SLIME_CARCASS = register("small_slime_carcass", SmallslimecarcassBlock::new);
		MEDIUM_MAGMA_CUBE_CARCASS = register("medium_magma_cube_carcass", MediummagmacubecarcassBlock::new);
		MAGMA_CUBE_CARCASS = register("magma_cube_carcass", MagmacubecarcassBlock::new);
		STRIDER_CARCASS = register("strider_carcass", StridercarcassBlock::new);
		DRAINED_STRIDER_CARCASS = register("drained_strider_carcass", DrainedstridercarcassBlock::new);
		VILLAGER_CORPSE = register("villager_corpse", VillagercorpseBlock::new);
		VILLAGER_HEAD = register("villager_head", VillagerheadBlock::new);
		DRAINED_VILLAGER = register("drained_villager", DrainedvillagerBlock::new);
		ZOMBIE_VILLAGER_CORPSE = register("zombie_villager_corpse", ZombievillagercorpseBlock::new);
		ZOMBIE_VILLAGER_HEAD = register("zombie_villager_head", ZombievillagerheadBlock::new);
		DRAINED_ZOMBIE_VILLAGER = register("drained_zombie_villager", DrainedzombievillagerBlock::new);
		ZOMBIFIED_PIGLIN_CORPSE = register("zombified_piglin_corpse", ZombiepiglincorpseBlock::new);
		DRAINED_ZOMBIFIED_PIGLIN_CORPSE = register("drained_zombified_piglin_corpse", DrainedZombiepiglincorpseBlock::new);
		ZOMBIFIED_PIGLIN_HEAD = register("zombified_piglin_head", ZombiepiglinheadBlock::new);
		WITHER_SKELETON_CORPSE = register("wither_skeleton_corpse", WitherskeletoncorpseBlock::new);
		TURTLE_CARCASS = register("turtle_carcass", TurtlecarcassBlock::new);
		TURTLE_HEAD = register("turtle_head", TurtleheadBlock::new);
		DRAINED_TURTLE_CARCASS = register("drained_turtle_carcass", DrainedTurtlecarcassBlock::new);
		EMPTY_TURTLE_SHELL = register("empty_turtle_shell", EmptyturtleshellBlock::new);
		METAL_TRAY = register("metal_tray", MetaltrayBlock::new);
		GRAY_FROG_CARCASS = register("gray_frog_carcass", GrayfrogcarcassBlock::new);
		DRAINED_GRAY_FROG_CARCASS = register("drained_gray_frog_carcass", DrainedgrayfrogcarcassBlock::new);
		GREEN_FROG_CARCASS = register("green_frog_carcass", GreenfrogcarcassBlock::new);
		DRAINED_GREEN_FROG_CARCASS = register("drained_green_frog_carcass", DrainedgreenfrogcarcassBlock::new);
		ORANGE_FROG_CARCASS = register("orange_frog_carcass", OrangefrogcarcassBlock::new);
		DRAINED_ORANGE_FROG_CARCASS = register("drained_orange_frog_carcass", DrainedorangefrogcarcassBlock::new);
		BROWN_LLAMA_CARCASS = register("brown_llama_carcass", BrownllamacarcassBlock::new);
		DRAINED_BROWN_LLAMA_CARCASS = register("drained_brown_llama_carcass", DrainedbrownllamacarcassBlock::new);
		BROWN_LLAMA_HEAD = register("brown_llama_head", BrownllamaheadBlock::new);
		CREAMY_LLAMA_CARCASS = register("creamy_llama_carcass", CreamyllamacarcassBlock::new);
		DRAINED_CREAMY_LLAMA_CARCASS = register("drained_creamy_llama_carcass", DrainedCreamyllamacarcassBlock::new);
		CREAMY_LLAMA_HEAD = register("creamy_llama_head", CreamyllamaheadBlock::new);
		GRAY_LLAMA_CARCASS = register("gray_llama_carcass", GrayllamacarcassBlock::new);
		DRAINED_GRAY_LLAMA_CARCASS = register("drained_gray_llama_carcass", DrainedGrayllamacarcassBlock::new);
		GRAY_LLAMA_HEAD = register("gray_llama_head", GrayllamaheadBlock::new);
		DRAINED_WHITE_LLAMA_CARCASS = register("drained_white_llama_carcass", DrainedWhitellamacarcassBlock::new);
		WHITE_LLAMA_HEAD = register("white_llama_head", WhitellamaheadBlock::new);
		WHITE_LLAMA_CARCASS = register("white_llama_carcass", WhiteLlamaCarcassBlock::new);
		FREEZER = register("freezer", FreezerBlock::new);
		TAXIDERMY_TABLE = register("taxidermy_table", TaxidermytableBlock::new);
		BROWN_LLAMA_HEAD_MOUNT = register("brown_llama_head_mount", BrownllamaheadmountBlock::new);
		CAMEL_HEAD_MOUNT = register("camel_head_mount", CamelheadmountBlock::new);
		CAVE_SPIDER_HEAD_MOUNT = register("cave_spider_head_mount", CavespiderheadmountBlock::new);
		CHICKEN_HEAD_MOUNT = register("chicken_head_mount", ChickenheadmountBlock::new);
		COW_HEAD_MOUNT = register("cow_head_mount", CowheadmountBlock::new);
		CREAMY_LLAMA_HEAD_MOUNT = register("creamy_llama_head_mount", CreamyllamaheadmountBlock::new);
		CREEPER_HEAD_MOUNT = register("creeper_head_mount", CreeperheadmountBlock::new);
		DOLPHIN_HEAD_MOUNT = register("dolphin_head_mount", DolphinheadmountBlock::new);
		DROWNED_HEAD_MOUNT = register("drowned_head_mount", DrownedheadmountBlock::new);
		EMPTY_HEAD_MOUNT = register("empty_head_mount", EmptyheadmountBlock::new);
		ENDERMAN_HEAD_MOUNT = register("enderman_head_mount", EndermanheadmountBlock::new);
		FOX_HEAD_MOUNT = register("fox_head_mount", FoxHeadMountBlock::new);
		GOAT_HEAD_MOUNT = register("goat_head_mount", GoatHeadMountBlock::new);
		GRAY_LLAMA_HEAD_MOUNT = register("gray_llama_head_mount", GrayllamaheadmountBlock::new);
		HOGLIN_HEAD_MOUNT = register("hoglin_head_mount", HoglinheadmountBlock::new);
		HUSK_HEAD_MOUNT = register("husk_head_mount", HuskheadmountBlock::new);
		LARGE_EMPTY_HEAD_MOUNT = register("large_empty_head_mount", LargeemptyheadmountBlock::new);
		PANDA_HEAD_MOUNT = register("panda_head_mount", PandaHeadMountBlock::new);
		PIG_HEAD_MOUNT = register("pig_head_mount", PigHeadMountBlock::new);
		PILLAGER_HEAD_MOUNT = register("pillager_head_mount", PillagerheadmountBlock::new);
		POLARBEAR_HEAD_MOUNT = register("polarbear_head_mount", PolarbearHeadMountBlock::new);
		SHEEP_HEAD_MOUNT = register("sheep_head_mount", SheepHeadMountBlock::new);
		SKELETON_HEAD_MOUNT = register("skeleton_head_mount", SkeletonheadmountBlock::new);
		SNOWY_FOX_HEAD_MOUNT = register("snowy_fox_head_mount", SnowyfoxheadmountBlock::new);
		SPIDER_HEAD_MOUNT = register("spider_head_mount", SpiderheadmountBlock::new);
		VILLAGER_HEAD_MOUNT = register("villager_head_mount", VillagerHeadMountBlock::new);
		WHITE_LLAMA_HEAD_MOUNT = register("white_llama_head_mount", WhitellamaheadmountBlock::new);
		ZOMBIE_HEAD_MOUNT = register("zombie_head_mount", ZombieheadmountBlock::new);
		ZOMBIE_VILLAGER_HEAD_MOUNT = register("zombie_villager_head_mount", ZombievillagerheadmountBlock::new);
		OCELOT_HEAD_MOUNT = register("ocelot_head_mount", OcelotheadmountBlock::new);
		CANOPY_BLACK = register("canopy_black", CanopyblackBlock::new);
		CANOPY_BLUE = register("canopy_blue", CanopyblueBlock::new);
		CANOPY_BROWN = register("canopy_brown", CanopybrownBlock::new);
		CANOPY_CYAN = register("canopy_cyan", CanopycyanBlock::new);
		CANOPY_GRAY = register("canopy_gray", CanopygrayBlock::new);
		CANOPY_GREEN = register("canopy_green", CanopygreenBlock::new);
		CANOPY_LIGHT_BLUE = register("canopy_light_blue", CanopylightblueBlock::new);
		CANOPY_LIGHT_GRAY = register("canopy_light_gray", CanopylightgrayBlock::new);
		CANOPY_LIME = register("canopy_lime", CanopylimeBlock::new);
		CANOPY_MAGENTA = register("canopy_magenta", CanopymagentaBlock::new);
		CANOPY_ORANGE = register("canopy_orange", CanopyorangeBlock::new);
		CANOPY_PINK = register("canopy_pink", CanopypinkBlock::new);
		CANOPY_PURPLE = register("canopy_purple", CanopypurpleBlock::new);
		CANOPY_RED = register("canopy_red", CanopyredBlock::new);
		CANOPY_YELLOW = register("canopy_yellow", CanopyyellowBlock::new);
		FLOORSTANDING_SIGN = register("floorstanding_sign", FloorstandingSignBlock::new);
		BUTCHER_STATUE = register("butcher_statue", ButcherstatueBlock::new);
		DIORITE_BRICK_SLAB = register("diorite_brick_slab", DioriteBrickSlabBlock::new);
		DIORITE_BRICK_WALL = register("diorite_brick_wall", DioriteBrickwallBlock::new);
		DIORITE_BRICKS = register("diorite_bricks", DioritebricksBlock::new);
		DIORITE_BRICK_STAIRS = register("diorite_brick_stairs", DioritebrickstairsBlock::new);
		ROPE = register("rope", RopeBlock::new);
		SAND = register("sand", SandBlock::new);
		ENDER_DRAGON_CARCASS = register("ender_dragon_carcass", EnderdragoncarcassBlock::new);
		DRAGON_SCALE_BLOCK = register("dragon_scale_block", DragonscaleblockBlock::new);
		ENDER_DRAGON_CARCASS_HEADLESS = register("ender_dragon_carcass_headless", EnderdragoncarcassheadlessBlock::new);
		ENDERDRAGONCUT_1 = register("enderdragoncut_1", Enderdragoncut1Block::new);
		ENDERDRAGONCUT_2 = register("enderdragoncut_2", Enderdragoncut2Block::new);
		ENDERDRAGONCUT_3 = register("enderdragoncut_3", Enderdragoncut3Block::new);
		ENDERDRAGONCUT_4 = register("enderdragoncut_4", Enderdragoncut4Block::new);
		ENDERDRAGONCUT_5 = register("enderdragoncut_5", Enderdragoncut5Block::new);
		ENDERDRAGONCUT_6 = register("enderdragoncut_6", Enderdragoncut6Block::new);
		ENDERDRAGONCUT_7 = register("enderdragoncut_7", Enderdragoncut7Block::new);
		ENDERDRAGONCUT_8 = register("enderdragoncut_8", Enderdragoncut8Block::new);
		ENDERDRAGONCUT_9 = register("enderdragoncut_9", Enderdragoncut9Block::new);
		ENDERDRAGONCUT_10 = register("enderdragoncut_10", Enderdragoncut10Block::new);
		ENDERDRAGONCUT_11 = register("enderdragoncut_11", Enderdragoncut11Block::new);
		ENDERDRAGONCUT_12 = register("enderdragoncut_12", Enderdragoncut12Block::new);
		ENDERDRAGONCUT_13 = register("enderdragoncut_13", Enderdragoncut13Block::new);
		ENDERDRAGONCUT_14 = register("enderdragoncut_14", Enderdragoncut14Block::new);
		WOODEN_SPIT_ROTISSERIE = register("wooden_spit_rotisserie", WoodenspitrotisserieBlock::new);
		POLARBEAR_RUG = register("polarbear_rug", BearrugBlock::new);
		GOAT_RUG = register("goat_rug", GoatrugBlock::new);
		PANDA_RUG = register("panda_rug", PandarugBlock::new);
		CASH_REGISTER_BLOCK = register("cash_register_block", CashregisterblockBlock::new);
		ACACIA_BUTCHER_DISPLAY = register("acacia_butcher_display", AcaciabutcherdisplayBlock::new);
		BIRCH_BUTCHER_DISPLAY = register("birch_butcher_display", BirchbutcherdisplayBlock::new);
		CRIMSON_BUTCHER_DISPLAY = register("crimson_butcher_display", CrimsonbutcherdisplayBlock::new);
		DARK_OAK_BUTCHER_DISPLAY = register("dark_oak_butcher_display", DarkoakbutcherdisplayBlock::new);
		JUNGLE_BUTCHER_DISPLAY = register("jungle_butcher_display", JunglebutcherdisplayBlock::new);
		OAK_BUTCHER_DISPLAY = register("oak_butcher_display", OakbutcherdisplayBlock::new);
		SPRUCE_BUTCHER_DISPLAY = register("spruce_butcher_display", SpruceButcherdisplayBlock::new);
		WARPED_BUTCHER_DISPLAY = register("warped_butcher_display", WarpedbutcherdisplayBlock::new);
		ACACIA_COUNTER = register("acacia_counter", AcaciacounterBlock::new);
		BIRCH_COUNTER = register("birch_counter", BirchcounterBlock::new);
		CRIMSON_COUNTER = register("crimson_counter", CrimsoncounterBlock::new);
		DARK_OAK_COUNTER = register("dark_oak_counter", DarkoakcounterBlock::new);
		JUNGLE_COUNTER = register("jungle_counter", JunglecounterBlock::new);
		OAK_COUNTER = register("oak_counter", OakcounterBlock::new);
		SPRUCE_COUNTER = register("spruce_counter", SprucecounterBlock::new);
		WARPED_COUNTER = register("warped_counter", WarpedcounterBlock::new);
		BLOOD_SPLATTER = register("blood_splatter", BloodsplatterBlock::new);
		BONE_BARREL = register("bone_barrel", BonebarrelBlock::new);
		COD_BARREL = register("cod_barrel", CodbarrelBlock::new);
		SALMON_BARREL = register("salmon_barrel", SalmonbarrelBlock::new);
		PINK_AXOLOTL_CARCASS = register("pink_axolotl_carcass", PinkaxolotlcarcassBlock::new);
		DRAINED_PINK_AXOLOTL_CARCASS = register("drained_pink_axolotl_carcass", DrainedpinkaxolotlcarcassBlock::new);
		BLUE_AXOLOTL_CARCASS = register("blue_axolotl_carcass", BlueaxolotlcarcassBlock::new);
		DRAINED_BLUE_AXOLOTL_CARCASS = register("drained_blue_axolotl_carcass", DrainedBlueaxolotlcarcassBlock::new);
		BROWN_AXOLOTL_CARCASS = register("brown_axolotl_carcass", BrownaxolotlcarcassBlock::new);
		DRAINED_BROWN_AXOLOTL_CARCASS = register("drained_brown_axolotl_carcass", DrainedBrownaxolotlcarcassBlock::new);
		CYAN_AXOLOTL_CARCASS = register("cyan_axolotl_carcass", CyanaxolotlcarcassBlock::new);
		DRAINED_CYAN_AXOLOTL_CARCASS = register("drained_cyan_axolotl_carcass", DrainedCyanaxolotlcarcassBlock::new);
		GOLD_AXOLOTL_CARCASS = register("gold_axolotl_carcass", GoldaxolotlcarcassBlock::new);
		DRAINED_GOLD_AXOLOTL_CARCASS = register("drained_gold_axolotl_carcass", DrainedGoldaxolotlcarcassBlock::new);
		PINK_AXOLOTL_HEAD = register("pink_axolotl_head", PinkaxolotlheadBlock::new);
		BLUE_AXOLOTL_HEAD = register("blue_axolotl_head", BlueaxolotlheadBlock::new);
		CYAN_AXOLOTL_HEAD = register("cyan_axolotl_head", CyanaxolotlheadBlock::new);
		GOLD_AXOLOTL_HEAD = register("gold_axolotl_head", GOLDaxolotlheadBlock::new);
		BROWN_AXOLOTL_HEAD = register("brown_axolotl_head", BrownaxolotlheadBlock::new);
		BLUE_AXOLOTL_HEAD_MOUNT = register("blue_axolotl_head_mount", BlueaxolotlheadmountBlock::new);
		BROWN_AXOLOTL_HEAD_MOUNT = register("brown_axolotl_head_mount", BrownaxolotlheadmountBlock::new);
		CYAN_AXOLOTL_HEAD_MOUNT = register("cyan_axolotl_head_mount", CyanaxolotlheadmountBlock::new);
		GOLD_AXOLOTL_HEAD_MOUNT = register("gold_axolotl_head_mount", GoldaxolotlheadmountBlock::new);
		PINK_AXOLOTL_HEAD_MOUNT = register("pink_axolotl_head_mount", PinkaxolotlheadmountBlock::new);
		BAT_HEAD_MOUNT = register("bat_head_mount", BatheadmountBlock::new);
		DONKEY_HEAD_MOUNT = register("donkey_head_mount", DonkeyheadmountBlock::new);
		MULE_HEAD_MOUNT = register("mule_head_mount", MuleheadmountBlock::new);
		EVOKER_HEAD_MOUNT = register("evoker_head_mount", EvokerHeadMountBlock::new);
		VINDICATOR_HEAD_MOUNT = register("vindicator_head_mount", VindicatorHeadMountBlock::new);
		RED_MOOSHROOM_HEAD_MOUNT = register("red_mooshroom_head_mount", RedMooshroomheadmountBlock::new);
		BROWN_MOOSHROOM_HEAD_MOUNT = register("brown_mooshroom_head_mount", BrownMooshroomheadmountBlock::new);
		PIGLIN_HEAD_MOUNT = register("piglin_head_mount", PiglinHeadMountBlock::new);
		PIGLIN_BRUTE_HEAD_MOUNT = register("piglin_brute_head_mount", PiglinbruteHeadMountBlock::new);
		ZOMBIFIED_PIGLIN_HEAD_MOUNT = register("zombified_piglin_head_mount", ZombifiedPiglinHeadMountBlock::new);
		RABBIT_HEAD_MOUNT = register("rabbit_head_mount", RabbitHeadMountBlock::new);
		STRAY_HEAD_MOUNT = register("stray_head_mount", StrayheadmountBlock::new);
		TURTLE_HEAD_MOUNT = register("turtle_head_mount", TurtleheadmountBlock::new);
		WITHER_SKELETON_HEAD_MOUNT = register("wither_skeleton_head_mount", WitherskeletonheadmountBlock::new);
		HANGING_ENDERMAN_CARCASS = register("hanging_enderman_carcass", HangingendermancarcassBlock::new);
		ENDERMAN_CARCASS = register("enderman_carcass", EndermancarcassBlock::new);
		DRAINED_ENDERMAN_CARCASS = register("drained_enderman_carcass", DrainedendermancarcassBlock::new);
		ENDERMAN_HEAD = register("enderman_head", EndermanheadBlock::new);
		HANGING_DRAINED_ENDERMAN_CARCASS = register("hanging_drained_enderman_carcass", HangingdrainedendermancarcassBlock::new);
		ENDERMITE_CARCASS = register("endermite_carcass", EndermiteBlock::new);
		ENDERMITE_HEAD_MOUNT = register("endermite_head_mount", EndermiteheadmountBlock::new);
		SILVERFISH_HEAD_MOUNT = register("silverfish_head_mount", SilverfishheadmountBlock::new);
		ENDERMITE_HEAD = register("endermite_head", EndermiteheadBlock::new);
		SILVERFISH_HEAD = register("silverfish_head", SilverfishheadBlock::new);
		SMALL_EMPTY_HEAD_MOUNT = register("small_empty_head_mount", SmallemptyheadmountBlock::new);
		PHANTOM_CARCASS = register("phantom_carcass", PhantomcarcassBlock::new);
		DRAINED_PHANTOM_CARCASS = register("drained_phantom_carcass", DrainedphantomcarcassBlock::new);
		PHANTOM_HEAD = register("phantom_head", PhantomheadBlock::new);
		PHANTOM_HEAD_MOUNT = register("phantom_head_mount", PhantomheadmountBlock::new);
		ALL_BLACK_CAT_CARCASS = register("all_black_cat_carcass", AllblackcatcarcassBlock::new);
		DRAINED_ALL_BLACK_CAT_CARCASS = register("drained_all_black_cat_carcass", DrainedallblackcatcarcassBlock::new);
		BLACK_CAT_CARCASS = register("black_cat_carcass", BlackcatcarcassBlock::new);
		DRAINED_BLACK_CAT_CARCASS = register("drained_black_cat_carcass", DrainedblackcatcarcassBlock::new);
		BRITISH_SHORTHAIR_CAT_CARCASS = register("british_shorthair_cat_carcass", BritishshorthaircatcarcassBlock::new);
		DRAINED_BRITISH_SHORTHAIR_CAT_CARCASS = register("drained_british_shorthair_cat_carcass", DrainedBritishshorthaircatcarcassBlock::new);
		CALICO_CAT_CARCASS = register("calico_cat_carcass", CalicocatcarcassBlock::new);
		DRAINED_CALICO_CAT_CARCASS = register("drained_calico_cat_carcass", DrainedCalicocatcarcassBlock::new);
		JELLIE_CAT_CARCASS = register("jellie_cat_carcass", JelliecatcarcassBlock::new);
		DRAINED_JELLIE_CAT_CARCASS = register("drained_jellie_cat_carcass", DrainedJelliecatcarcassBlock::new);
		PERSIAN_CAT_CARCASS = register("persian_cat_carcass", PersiancatcarcassBlock::new);
		DRAINED_PERSIAN_CAT_CARCASS = register("drained_persian_cat_carcass", DrainedPersiancatcarcassBlock::new);
		RAGDOLL_CAT_CARCASS = register("ragdoll_cat_carcass", RagdollcatcarcassBlock::new);
		DRAINED_RAGDOLL_CAT_CARCASS = register("drained_ragdoll_cat_carcass", DrainedRagdollcatcarcassBlock::new);
		RED_CAT_CARCASS = register("red_cat_carcass", RedcatcarcassBlock::new);
		DRAINED_RED_CAT_CARCASS = register("drained_red_cat_carcass", DrainedRedcatcarcassBlock::new);
		SIAMESE_CAT_CARCASS = register("siamese_cat_carcass", SiamesecatcarcassBlock::new);
		DRAINED_SIAMESE_CAT_CARCASS = register("drained_siamese_cat_carcass", DrainedSiamesecatcarcassBlock::new);
		TABBY_CAT_CARCASS = register("tabby_cat_carcass", TabbycatcarcassBlock::new);
		DRAINED_TABBY_CAT_CARCASS = register("drained_tabby_cat_carcass", DrainedTabbycatcarcassBlock::new);
		WHITE_CAT_CARCASS = register("white_cat_carcass", WhitecatcarcassBlock::new);
		DRAINED_WHITE_CAT_CARCASS = register("drained_white_cat_carcass", DrainedWhitecatcarcassBlock::new);
		BLACK_CAT_HEAD = register("black_cat_head", BlackcatheadBlock::new);
		ALL_BLACK_CAT_HEAD = register("all_black_cat_head", AllblackcatheadBlock::new);
		TABBY_CAT_HEAD = register("tabby_cat_head", TabbycatheadBlock::new);
		RED_CAT_HEAD = register("red_cat_head", RedcatheadBlock::new);
		SIAMESE_CAT_HEAD = register("siamese_cat_head", SiamesecatheadBlock::new);
		SHORTHAIR_CAT_HEAD = register("shorthair_cat_head", ShorthaircatheadBlock::new);
		RAGDOLL_CAT_HEAD = register("ragdoll_cat_head", RagdollcatheadBlock::new);
		JELLIE_CAT_HEAD = register("jellie_cat_head", JelliecatheadBlock::new);
		WHITE_CAT_HEAD = register("white_cat_head", WhitecatheadBlock::new);
		PERSIAN_CAT_HEAD = register("persian_cat_head", PersiancatheadBlock::new);
		CALICO_CAT_HEAD = register("calico_cat_head", CalicocatheadBlock::new);
		CAT_CARCASS = register("cat_carcass", CatcarcassBlock::new);
		ELDER_GUARDIAN_CARCASS = register("elder_guardian_carcass", ElderguardiancarcassBlock::new);
		WITCH_CORPSE = register("witch_corpse", WitchcorpseBlock::new);
		DRAINED_WITCH_CORPSE = register("drained_witch_corpse", DrainedwitchcorpseBlock::new);
		WITCH_HEAD = register("witch_head", WitchheadBlock::new);
		IRON_GOLEM = register("iron_golem", IrongolemBlock::new);
		IRON_GOLEM_HEAD = register("iron_golem_head", IrongolemheadBlock::new);
		IRON_GOLEM_ARMS = register("iron_golem_arms", IrongolemarmsBlock::new);
		IRON_GOLEM_LEGS = register("iron_golem_legs", IrongolemlegsBlock::new);
		IRON_GOLEM_BODY = register("iron_golem_body", IrongolembodyBlock::new);
		REPAIRED_IRON_GOLEM_HEAD = register("repaired_iron_golem_head", RepairedIrongolemheadBlock::new);
		REPAIRED_IRON_GOLEM_ARMS = register("repaired_iron_golem_arms", RepairedIrongolemarmsBlock::new);
		REPAIRED_IRON_GOLEM_LEGS = register("repaired_iron_golem_legs", RepairedIrongolemlegsBlock::new);
		REPAIRED_IRON_GOLEM_BODY = register("repaired_iron_golem_body", RepairedIrongolembodyBlock::new);
		ALL_BLACK_CAT_HEAD_MOUNT = register("all_black_cat_head_mount", AllblackcatheadmountBlock::new);
		BLACK_CAT_HEAD_MOUNT = register("black_cat_head_mount", BlackcatheadmountBlock::new);
		TABBY_CAT_HEAD_MOUNT = register("tabby_cat_head_mount", TabbycatheadmountBlock::new);
		RED_CAT_HEAD_MOUNT = register("red_cat_head_mount", RedcatheadmountBlock::new);
		SIAMESE_CAT_HEAD_MOUNT = register("siamese_cat_head_mount", SiamesecatheadmountBlock::new);
		SHORTHAIR_CAT_HEAD_MOUNT = register("shorthair_cat_head_mount", ShorthaircatheadmountBlock::new);
		RAGDOLL_CAT_HEAD_MOUNT = register("ragdoll_cat_head_mount", RagdollcatheadmountBlock::new);
		JELLIE_CAT_HEAD_MOUNT = register("jellie_cat_head_mount", JelliecatheadmountBlock::new);
		WHITE_CAT_HEAD_MOUNT = register("white_cat_head_mount", WhitecatheadmountBlock::new);
		PERSIAN_CAT_HEAD_MOUNT = register("persian_cat_head_mount", PersiancatheadmountBlock::new);
		CALICO_CAT_HEAD_MOUNT = register("calico_cat_head_mount", CalicocatheadmountBlock::new);
		IRON_GOLEM_HEAD_MOUNT = register("iron_golem_head_mount", IrongolemheadmountBlock::new);
		REPAIRED_IRON_GOLEM_HEAD_MOUNT = register("repaired_iron_golem_head_mount", RepairedirongolemheadmountBlock::new);
		WITCH_HEAD_MOUNT = register("witch_head_mount", WitchheadmountBlock::new);
		WITHER_CARCASS = register("wither_carcass", WithercarcassBlock::new);
		ZOGLIN_CARCASS = register("zoglin_carcass", ZoglincarcassBlock::new);
		ZOGLIN_HEAD = register("zoglin_head", ZoglinheadBlock::new);
		DRAINED_ZOGLIN_CARCASS = register("drained_zoglin_carcass", DrainedzoglincarcassBlock::new);
		ZOGLIN_HEAD_MOUNT = register("zoglin_head_mount", ZoglinheadmountBlock::new);
		WOLF_CARCASS = register("wolf_carcass", WolfcarcassBlock::new);
		WOLF_HEAD = register("wolf_head", WolfheadBlock::new);
		DRAINED_WOLF_CARCASS = register("drained_wolf_carcass", DrainedWolfcarcassBlock::new);
		WOLF_HEAD_MOUNT = register("wolf_head_mount", WolfheadmountBlock::new);
		SKELETON_HORSE_CARCASS = register("skeleton_horse_carcass", SkeletonhorsecarcassBlock::new);
		SKELETON_HORSE_HEAD = register("skeleton_horse_head", SkeletonhorseheadBlock::new);
		SKELETON_HORSE_HEAD_MOUNT = register("skeleton_horse_head_mount", SkeletonhorseheadmountBlock::new);
		WARDEN_CARCASS = register("warden_carcass", WardencarcassBlock::new);
		WARDEN_HEAD = register("warden_head", WardenheadBlock::new);
		ZOMBIE_HORSE_CARCASS = register("zombie_horse_carcass", ZombiehorsecarcassBlock::new);
		ZOMBIE_HORSE_HEAD = register("zombie_horse_head", ZombiehorseheadBlock::new);
		DRAINED_ZOMBIE_HORSE_CARCASS = register("drained_zombie_horse_carcass", DrainedZombiehorsecarcassBlock::new);
		ZOMBIE_HORSE_HEAD_MOUNT = register("zombie_horse_head_mount", ZombiehorseheadmountBlock::new);
		SPIKE_TRAP = register("spike_trap", SpiketrapBlock::new);
		BRAIN = register("brain", BrainBlock::new);
		RAW_SAUSAGES = register("raw_sausages", RawsausagesBlock::new);
		COOKED_SAUSAGES = register("cooked_sausages", CookedsausagesBlock::new);
		RAW_BLOOD_SAUSAGES = register("raw_blood_sausages", RawbloodsausagesBlock::new);
		COOKED_BLOOD_SAUSAGES = register("cooked_blood_sausages", CookedbloodsausagesBlock::new);
		BEE_CARCASS = register("bee_carcass", BeecarcassBlock::new);
		BEE_HEAD = register("bee_head", BeeheadBlock::new);
		SNIFFER_CARCASS_BLOCK = register("sniffer_carcass_block", SniffercarcassblockBlock::new);
		DRAINED_SNIFFER_CARCASS_BLOCK = register("drained_sniffer_carcass_block", DrainedsniffercarcassblockBlock::new);
		SNIFFER_HEAD = register("sniffer_head", SnifferheadBlock::new);
		ENDER_DRAGON_HEAD_MOUNT = register("ender_dragon_head_mount", EnderDragonHeadMountBlock::new);
		EMPTY_DRAGON_TRIMMED_HEAD_MOUNT = register("empty_dragon_trimmed_head_mount", EmptydragontrimmedheadmountBlock::new);
		TRIMMED_ENDER_DRAGON_HEAD_MOUNT = register("trimmed_ender_dragon_head_mount", TrimmedEnderDragonHeadMountBlock::new);
		REPAIRED_IRONGOLEM = register("repaired_irongolem", RepairedIrongolemBlock::new);
		REGULAR_BLACK_HORSE_CARCASS = register("regular_black_horse_carcass", RegularblackhorsecarcassBlock::new);
		BLACK_HORSE_HEAD = register("black_horse_head", BlackhorseheadBlock::new);
		DRAINED_REGULAR_BLACK_HORSE_CARCASS = register("drained_regular_black_horse_carcass", DrainedRegularblackhorsecarcassBlock::new);
		BROWN_HORSE_HEAD = register("brown_horse_head", BrownhorseheadBlock::new);
		REGULAR_BROWN_HORSE_CARCASS = register("regular_brown_horse_carcass", RegularBrownhorsecarcassBlock::new);
		DRAINED_REGULAR_BROWN_HORSE_CARCASS = register("drained_regular_brown_horse_carcass", DrainedRegularBrownhorsecarcassBlock::new);
		CHESTNUT_HORSE_HEAD = register("chestnut_horse_head", ChestnuthorseheadBlock::new);
		REGULAR_CHESTNUT_HORSE_CARCASS = register("regular_chestnut_horse_carcass", RegularChestnuthorsecarcassBlock::new);
		DRAINED_REGULAR_CHESTNUT_HORSE_CARCASS = register("drained_regular_chestnut_horse_carcass", DrainedRegularChestnuthorsecarcassBlock::new);
		CREAMY_HORSE_HEAD = register("creamy_horse_head", CreamyhorseheadBlock::new);
		REGULAR_CREAMY_HORSE_CARCASS = register("regular_creamy_horse_carcass", RegularCreamyhorsecarcassBlock::new);
		DRAINED_REGULAR_CREAMY_HORSE_CARCASS = register("drained_regular_creamy_horse_carcass", DrainedRegularCreamyhorsecarcassBlock::new);
		DARK_BROWN_HORSE_HEAD = register("dark_brown_horse_head", DarkbrownhorseheadBlock::new);
		REGULAR_DARK_BROWN_HORSE_CARCASS = register("regular_dark_brown_horse_carcass", RegularDarkbrownhorsecarcassBlock::new);
		DRAINED_REGULAR_DARK_BROWN_HORSE_CARCASS = register("drained_regular_dark_brown_horse_carcass", DrainedRegularDarkbrownhorsecarcassBlock::new);
		GRAY_HORSE_HEAD = register("gray_horse_head", GrayhorseheadBlock::new);
		REGULAR_GRAY_HORSE_CARCASS = register("regular_gray_horse_carcass", RegularGrayhorsecarcassBlock::new);
		WHITE_HORSE_HEAD = register("white_horse_head", WhitehorseheadBlock::new);
		REGULAR_WHITE_HORSE_CARCASS = register("regular_white_horse_carcass", RegularWhitehorsecarcassBlock::new);
		DRAINED_GRAY_HORSE_CARCASS = register("drained_gray_horse_carcass", DrainedGrayhorsecarcassBlock::new);
		DRAINED_WHITE_HORSE_CARCASS = register("drained_white_horse_carcass", DrainedWhitehorsecarcassBlock::new);
		PLASTIC_SHEET = register("plastic_sheet", PlasticsheetBlock::new);
		PLASTIC_SHEET_CORNER = register("plastic_sheet_corner", PlasticsheetcornerBlock::new);
		CLING_FILM = register("cling_film", ClingfilmBlock::new);
		PHOTOS = register("photos", PhotosBlock::new);
		INFECTED_BLOOD = register("infected_blood", InfectedBloodBlock::new);
		SULFUR_ORE = register("sulfur_ore", SulfuroreBlock::new);
		DEEPSLATE_SULFUR_ORE = register("deepslate_sulfur_ore", DeepslatesulfuroreBlock::new);
		BLACK_HORSE_HEAD_MOUNT = register("black_horse_head_mount", BlackhorseheadmountBlock::new);
		BROWN_HORSE_HEAD_MOUNT = register("brown_horse_head_mount", BrownhorseheadmountBlock::new);
		CHESTNUT_HORSE_HEAD_MOUNT = register("chestnut_horse_head_mount", ChestnuthorseheadmountBlock::new);
		CREAMY_HORSE_HEAD_MOUNT = register("creamy_horse_head_mount", CreamyhorseheadmountBlock::new);
		DARK_BROWN_HORSE_HEAD_MOUNT = register("dark_brown_horse_head_mount", DarkbrownhorseheadmountBlock::new);
		GRAY_HORSE_HEAD_MOUNT = register("gray_horse_head_mount", GrayhorseheadmountBlock::new);
		WHITE_HORSE_HEAD_MOUNT = register("white_horse_head_mount", WhitehorseheadmountBlock::new);
		PESTLE_AND_MORTAR = register("pestle_and_mortar", PestleandmortarBlock::new);
		EMPTY_WARDEN_TRIMMED_HEAD_MOUNT = register("empty_warden_trimmed_head_mount", EmptywardentrimmedheadmountBlock::new);
		WARDEN_HEAD_MOUNT = register("warden_head_mount", WardenHeadMountBlock::new);
		TRIMMED_WARDEN_HEAD_MOUNT = register("trimmed_warden_head_mount", TrimmedwardenHeadMountBlock::new);
		AXOLOTL_SKELETON = register("axolotl_skeleton", AxolotlskeletonBlock::new);
		BAT_SKELETON = register("bat_skeleton", BatskeletonBlock::new);
		MOOSHROOM_SKELETON = register("mooshroom_skeleton", MooshroomskeletonBlock::new);
		CAMEL_SKELETON = register("camel_skeleton", CamelskeletonBlock::new);
		CAT_SKELETON = register("cat_skeleton", CatskeletonBlock::new);
		CHICKEN_SKELETON = register("chicken_skeleton", ChickenskeletonBlock::new);
		FISH_SKELETON = register("fish_skeleton", FishskeletonBlock::new);
		COW_SKELETON = register("cow_skeleton", CowskeletonBlock::new);
		CREEPER_SKELETON = register("creeper_skeleton", CreeperskeletonBlock::new);
		DOLPHIN_SKELETON = register("dolphin_skeleton", DolphinskeletonBlock::new);
		DONKEY_SKELETON = register("donkey_skeleton", DonkeyskeletonBlock::new);
		SKELETON = register("skeleton", SkeletonBlock::new);
		FOX_SKELETON = register("fox_skeleton", FoxskeletonBlock::new);
		GOAT_SKELETON = register("goat_skeleton", GoatskeletonBlock::new);
		HOGLIN_SKELETON = register("hoglin_skeleton", HoglinskeletonBlock::new);
		LLAMA_SKELETON = register("llama_skeleton", LlamaskeletonBlock::new);
		MULE_SKELETON = register("mule_skeleton", MuleskeletonBlock::new);
		OCELOT_SKELETON = register("ocelot_skeleton", OcelotskeletonBlock::new);
		PANDA_SKELETON = register("panda_skeleton", PandaskeletonBlock::new);
		PHANTOM_SKELETON = register("phantom_skeleton", PhantomskeletonBlock::new);
		PIG_SKELETON = register("pig_skeleton", PigskeletonBlock::new);
		PIGLIN_SKELETON = register("piglin_skeleton", PiglinskeletonBlock::new);
		POLARBEAR_SKELETON = register("polarbear_skeleton", PolarbearskeletonBlock::new);
		SHEEP_SKELETON = register("sheep_skeleton", SheepskeletonBlock::new);
		WOLF_SKELETON = register("wolf_skeleton", WolfskeletonBlock::new);
		PLAYERCORPSE = register("playercorpse", PlayercorpseBlock::new);
		DRAINEDPLAYERCORPSE = register("drainedplayercorpse", DrainedplayercorpseBlock::new);
		JAR = register("jar", JarBlock::new);
		RAVAGER_HEAD = register("ravager_head", RavagerheadBlock::new);
		RAVAGER = register("ravager", RavagerBlock::new);
		RAVAGER_HEAD_MOUNT = register("ravager_head_mount", RavagerHeadMountBlock::new);
	}

	// Start of user code block custom blocks
	// End of user code block custom blocks
	private static <B extends Block> DeferredBlock<B> register(String name, Function<BlockBehaviour.Properties, ? extends B> supplier) {
		return REGISTRY.registerBlock(name, supplier);
	}

	@EventBusSubscriber(Dist.CLIENT)
	public static class BlocksClientSideHandler {
		@SubscribeEvent
		public static void blockColorLoad(RegisterColorHandlersEvent.Block event) {
			BasinBlock.blockColorLoad(event);
		}
	}
}