package net.mcreator.butchery.configuration;

import net.neoforged.neoforge.common.ModConfigSpec;

public class ButcheryconfigConfiguration {
	public static final ModConfigSpec.Builder BUILDER = new ModConfigSpec.Builder();
	public static final ModConfigSpec SPEC;

	public static final ModConfigSpec.ConfigValue<Boolean> FIRST_JOIN_BOOK;
	public static final ModConfigSpec.ConfigValue<Boolean> SHOW_HINTS;
	public static final ModConfigSpec.ConfigValue<Boolean> SPECIFIC_TOOLS;
	public static final ModConfigSpec.ConfigValue<Boolean> INSTANT_BLEED;
	public static final ModConfigSpec.ConfigValue<Boolean> ORGANS;
	public static final ModConfigSpec.ConfigValue<Boolean> WEIGHTED_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> LOOTING_ENCHANT;
	public static final ModConfigSpec.ConfigValue<Boolean> SULFUR_ORE;
	public static final ModConfigSpec.ConfigValue<Boolean> SALT_GENERATION;
	public static final ModConfigSpec.ConfigValue<Boolean> BLOOD_PUDDLE;
	public static final ModConfigSpec.ConfigValue<Boolean> BLOOD_SPREAD;
	public static final ModConfigSpec.ConfigValue<Boolean> AXOLOTL_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> BAT_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> BEE_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> BMOOSHROOM_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> CAMEL_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> CAT_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> CAVE_SPIDER_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> CHICKEN_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> COD_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> COW_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> CREEPER_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> DOLPHIN_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> DONKEY_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> DROWNED_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> ELDER_GUARDIAN_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> EVOKER_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> END_DRAGON_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> ENDERMAN_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> ENDERMITE_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> FOX_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> FROG_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> GLOW_SQUID_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> GOAT_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> GUARDIAN_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> HOGLIN_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> HORSE_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> HUSK_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> IRON_GOLEM_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> LLAMA_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> MAGMA_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> MULE_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> OCELOT_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> PANDA_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> PIG_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> PIGLIN_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> PIGLIN_BRUTE_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> PILLAGER_CORPSE;
	public static final ModConfigSpec.ConfigValue<Boolean> POLAR_BEAR_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> PLAYER_CORPSE;
	public static final ModConfigSpec.ConfigValue<Boolean> PUFFERFISH_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> PHANTOM_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> RAVAGER_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> RABBIT_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> RMOOSHROOM_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> SALMON_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> SHEEP_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> SHULKER_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> SILVERFISH_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> SKELETON_CORPSE;
	public static final ModConfigSpec.ConfigValue<Boolean> SKELETON_HORSE_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> SLIME_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> SNIFFER_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> SPIDER_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> SQUID_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> STRAY_CORPSE;
	public static final ModConfigSpec.ConfigValue<Boolean> STRIDER_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> TURTLE_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> VILLAGER_CORPSE;
	public static final ModConfigSpec.ConfigValue<Boolean> VINDICATOR_CORPSE;
	public static final ModConfigSpec.ConfigValue<Boolean> WARDEN_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> WITCH_CORPSE;
	public static final ModConfigSpec.ConfigValue<Boolean> WITHER_SKELETON_CORPSE;
	public static final ModConfigSpec.ConfigValue<Boolean> WITHER_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> WOLF_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> ZOGLIN_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> ZOMBIE_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> ZOMBIE_HORSE_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> ZOMBIE_VILLAGER_CORPSE;
	public static final ModConfigSpec.ConfigValue<Boolean> ZOMBIFIED_PIGLIN_CORPSE;
	public static final ModConfigSpec.ConfigValue<Boolean> FARMERS_DELIGHT;
	public static final ModConfigSpec.ConfigValue<Boolean> VAMPIRISM_HEART;
	public static final ModConfigSpec.ConfigValue<Boolean> VDELIGHT_EYE;
	public static final ModConfigSpec.ConfigValue<String> COIN_LOOTTABLE;
	static {
		BUILDER.push("general");
		FIRST_JOIN_BOOK = BUILDER.comment("Give the butchers guide on first join.").define("first_join_book", true);
		SHOW_HINTS = BUILDER.comment("Show GUI hints when looking at carcasses.").define("show_hints", true);
		SPECIFIC_TOOLS = BUILDER.comment("Enable to have carcasses drop with ONLY cleavers. Disable to have carcasses drop no matter what kills the mob.").define("only_cleavers_drop_carcasses", true);
		INSTANT_BLEED = BUILDER.comment("Instantly bleed carcasses.").define("instant_bleeding", false);
		ORGANS = BUILDER.comment("Enable organ drops").define("organs", true);
		WEIGHTED_CARCASS = BUILDER.comment("Enable carcass weight (slowness effect when carcasses are in your inventory)").define("weighted_carcasses", true);
		LOOTING_ENCHANT = BUILDER.comment("Enable looting when butchering carcasses").define("looting_enchantment", true);
		SULFUR_ORE = BUILDER.comment("Enable sulfur ore generation").define("sulfur_ore_generation", true);
		SALT_GENERATION = BUILDER.comment("Enable salt generation").define("salt_generation", true);
		BLOOD_PUDDLE = BUILDER.comment("Enable blood puddles dropping when no blood grate is below a carcass.").define("blood_puddle", true);
		BLOOD_SPREAD = BUILDER.comment("Enable blood spread").define("blood_spread", true);
		BUILDER.pop();
		BUILDER.push("mobs");
		AXOLOTL_CARCASS = BUILDER.comment("Enable Axolotl Carcass").define("axolotl", true);
		BAT_CARCASS = BUILDER.comment("Enable Bat Carcasses").define("bat_carcass", true);
		BEE_CARCASS = BUILDER.comment("Enable Bee Carcasses").define("bee_carcass", true);
		BMOOSHROOM_CARCASS = BUILDER.comment("Enable Brown Mooshroom Carcasses").define("brown_mooshroom", true);
		CAMEL_CARCASS = BUILDER.comment("Enable Camel Carcasses").define("camel", true);
		CAT_CARCASS = BUILDER.comment("Enable Cat Carcasses").define("cat", true);
		CAVE_SPIDER_CARCASS = BUILDER.comment("Enable Cave Spider Carcasses").define("cave_spider", true);
		CHICKEN_CARCASS = BUILDER.comment("Enable Chicken Carcasses").define("chicken_carcass", true);
		COD_CARCASS = BUILDER.comment("Enable Cod Carcasses").define("cod", true);
		COW_CARCASS = BUILDER.comment("Enable Cow Carcasses").define("cow_carcass", true);
		CREEPER_CARCASS = BUILDER.comment("Enable Creeper Carcasses").define("creeper", true);
		DOLPHIN_CARCASS = BUILDER.comment("Enable Dolphin Carcasses").define("dolphin_carcass", true);
		DONKEY_CARCASS = BUILDER.comment("Enable Donkey Carcasses").define("donkey", true);
		DROWNED_CARCASS = BUILDER.comment("Enable Drowned Corpses").define("drowned", true);
		ELDER_GUARDIAN_CARCASS = BUILDER.comment("Enable Elder Guardian Carcass").define("elder_guardian", true);
		EVOKER_CARCASS = BUILDER.comment("Enable Evoker Corpses").define("evoker", true);
		END_DRAGON_CARCASS = BUILDER.comment("Enable Ender Dragon Carcass").define("ender_dragon", true);
		ENDERMAN_CARCASS = BUILDER.comment("Enable Enderman Corpses").define("enderman", true);
		ENDERMITE_CARCASS = BUILDER.comment("Enable Endermite Carcass").define("endermite", true);
		FOX_CARCASS = BUILDER.comment("Enable Fox Carcasses").define("fox", true);
		FROG_CARCASS = BUILDER.comment("Enable Frog Carcass").define("frog", true);
		GLOW_SQUID_CARCASS = BUILDER.comment("Enable Glow Squid Carcasses").define("glow_squid_carcass", true);
		GOAT_CARCASS = BUILDER.comment("Enable Goat Carcasses").define("goat_carcass", true);
		GUARDIAN_CARCASS = BUILDER.comment("Enable Guardian Carcasses").define("guardian", true);
		HOGLIN_CARCASS = BUILDER.comment("Enable Hoglin Carcasses").define("hoglin", true);
		HORSE_CARCASS = BUILDER.comment("Enable Horse Carcasses").define("horse", true);
		HUSK_CARCASS = BUILDER.comment("Enable Husk Corpses").define("husk", true);
		IRON_GOLEM_CARCASS = BUILDER.comment("Enable Iron Golem Corpses").define("iron_golem", true);
		LLAMA_CARCASS = BUILDER.comment("Enable Llama Carcass").define("llama", true);
		MAGMA_CARCASS = BUILDER.comment("Enable Magma Cube Carcass").define("magma_cube", true);
		MULE_CARCASS = BUILDER.comment("Enable Mule Carcasses").define("mule", true);
		OCELOT_CARCASS = BUILDER.comment("Enable Ocelot Carcasses").define("ocelot", true);
		PANDA_CARCASS = BUILDER.comment("Enable Panda Carcasses").define("panda", true);
		PIG_CARCASS = BUILDER.comment("Enable Pig Carcasses").define("pig_carcass", true);
		PIGLIN_CARCASS = BUILDER.comment("Enable Piglin Corpses").define("piglin", true);
		PIGLIN_BRUTE_CARCASS = BUILDER.comment("Enable Piglin Brute Corpses").define("piglin_brute", true);
		PILLAGER_CORPSE = BUILDER.comment("Enable Pillager Corpses").define("pillager", true);
		POLAR_BEAR_CARCASS = BUILDER.comment("Enable Polar Bear Carcass").define("polar_bear", true);
		PLAYER_CORPSE = BUILDER.comment("Enable Player Corpses").define("player", true);
		PUFFERFISH_CARCASS = BUILDER.comment("Enable Pufferfish Carcass").define("pufferfish", true);
		PHANTOM_CARCASS = BUILDER.comment("Enable Phantom Carcass").define("phantom", true);
		RAVAGER_CARCASS = BUILDER.comment("Enable Ravager Carcass").define("ravager", true);
		RABBIT_CARCASS = BUILDER.comment("Enable Rabbit Carcass").define("rabbit", true);
		RMOOSHROOM_CARCASS = BUILDER.comment("Enable Red Mooshroom Carcasses").define("red_mooshroom", true);
		SALMON_CARCASS = BUILDER.comment("Enable Salmon Carcasses").define("salmon", true);
		SHEEP_CARCASS = BUILDER.comment("Enable Sheep Carcasses").define("sheep_carcass", true);
		SHULKER_CARCASS = BUILDER.comment("Enable Shulker Carcass").define("shulker", true);
		SILVERFISH_CARCASS = BUILDER.comment("Enable Silverfish Carcass").define("silverfish", true);
		SKELETON_CORPSE = BUILDER.comment("Enable Skeleton Carcass").define("skeleton", true);
		SKELETON_HORSE_CARCASS = BUILDER.comment("Enable Skeleton Horse Carcass").define("skeleton_horse", true);
		SLIME_CARCASS = BUILDER.comment("Enable Slime Carcass").define("slime", true);
		SNIFFER_CARCASS = BUILDER.comment("Enable Sniffer Carcass").define("sniffer", true);
		SPIDER_CARCASS = BUILDER.comment("Enable Spider Carcasses").define("spider_carcass", true);
		SQUID_CARCASS = BUILDER.comment("Enable Squid Carcasses").define("squid_carcass", true);
		STRAY_CORPSE = BUILDER.comment("Enable Stray Carcass").define("stray", true);
		STRIDER_CARCASS = BUILDER.comment("Enable Strider Carcass").define("strider", true);
		TURTLE_CARCASS = BUILDER.comment("Enable Turtle Carcass").define("turtle", true);
		VILLAGER_CORPSE = BUILDER.comment("Enable Villager Corpses").define("villager", true);
		VINDICATOR_CORPSE = BUILDER.comment("Enable Vindicator Corpses").define("vindicator", true);
		WARDEN_CARCASS = BUILDER.comment("Enable Warden Corpses").define("warden", true);
		WITCH_CORPSE = BUILDER.comment("Enable Witch Corpses").define("witch", true);
		WITHER_SKELETON_CORPSE = BUILDER.comment("Enable Wither Skeleton Corpses").define("wither_skeleton", true);
		WITHER_CARCASS = BUILDER.comment("Enable Wither Corpses").define("wither", true);
		WOLF_CARCASS = BUILDER.comment("Enable Wolf Corpses").define("wolf", true);
		ZOGLIN_CARCASS = BUILDER.comment("Enable Zoglin Corpses").define("zoglin", true);
		ZOMBIE_CARCASS = BUILDER.comment("Enable Zombie Corpses").define("zombie", true);
		ZOMBIE_HORSE_CARCASS = BUILDER.comment("Enable Zombie Horse Corpses").define("zombie_horse", true);
		ZOMBIE_VILLAGER_CORPSE = BUILDER.comment("Enable Zombie Villager Corpses").define("zombie_villager", true);
		ZOMBIFIED_PIGLIN_CORPSE = BUILDER.comment("Enable Zombified Piglin Corpses").define("zombified_piglin", true);
		BUILDER.pop();
		BUILDER.push("farmers_delight_compatibility");
		FARMERS_DELIGHT = BUILDER.comment("Enable Farmers Delight Compatibility").define("farmers_delight", false);
		BUILDER.pop();
		BUILDER.push("vampirism_compatibility");
		VAMPIRISM_HEART = BUILDER.comment("Replaces heart drops with vampirisms hearts").define("vampirism_heart", false);
		VDELIGHT_EYE = BUILDER.comment("Replaces eye drops with vampirisms eyes").define("vampires_delight_eye", false);
		BUILDER.pop();
		BUILDER.push("butchers_coin_reward");
		COIN_LOOTTABLE = BUILDER.comment("The loottable that the butchery coin rewards from.").define("loottable", "minecraft:chests/end_city_treasure");
		BUILDER.pop();

		SPEC = BUILDER.build();
	}

}