package net.mcreator.butchery.configuration;

import net.neoforged.neoforge.common.ModConfigSpec;

public class ButcheryconfigConfiguration {
	public static final ModConfigSpec.Builder BUILDER = new ModConfigSpec.Builder();
	public static final ModConfigSpec SPEC;

	public static final ModConfigSpec.ConfigValue<Boolean> FIRST_JOIN_BOOK;
	public static final ModConfigSpec.ConfigValue<Boolean> SHOW_HINTS;
	public static final ModConfigSpec.ConfigValue<Boolean> SPECIFIC_TOOLS;
	public static final ModConfigSpec.ConfigValue<Boolean> INSTANT_BLEED;
	public static final ModConfigSpec.ConfigValue<Boolean> ORGANS;
	public static final ModConfigSpec.ConfigValue<Boolean> WEIGHTED_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> LOOTING_ENCHANT;
	public static final ModConfigSpec.ConfigValue<Boolean> SULFUR_ORE;
	public static final ModConfigSpec.ConfigValue<Boolean> SALT_GENERATION;
	public static final ModConfigSpec.ConfigValue<Boolean> BLOOD_PUDDLE;
	public static final ModConfigSpec.ConfigValue<Boolean> BLOOD_SPREAD;
	public static final ModConfigSpec.ConfigValue<Boolean> AXOLOTL_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> BAT_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> BEE_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> BMOOSHROOM_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> CAMEL_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> CAT_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> CAVE_SPIDER_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> CHICKEN_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> COD_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> COW_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> CREEPER_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> DOLPHIN_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> DONKEY_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> DROWNED_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> ELDER_GUARDIAN_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> EVOKER_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> END_DRAGON_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> ENDERMAN_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> ENDERMITE_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> FOX_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> FROG_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> GLOW_SQUID_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> GOAT_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> GUARDIAN_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> HOGLIN_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> HORSE_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> HUSK_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> IRON_GOLEM_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> LLAMA_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> MAGMA_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> MULE_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> OCELOT_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> PANDA_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> PIG_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> PIGLIN_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> PIGLIN_BRUTE_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> PILLAGER_CORPSE;
	public static final ModConfigSpec.ConfigValue<Boolean> POLAR_BEAR_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> PLAYER_CORPSE;
	public static final ModConfigSpec.ConfigValue<Boolean> PUFFERFISH_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> PHANTOM_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> RAVAGER_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> RABBIT_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> RMOOSHROOM_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> SALMON_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> SHEEP_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> SHULKER_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> SILVERFISH_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> SKELETON_CORPSE;
	public static final ModConfigSpec.ConfigValue<Boolean> SKELETON_HORSE_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> SLIME_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> SNIFFER_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> SPIDER_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> SQUID_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> STRAY_CORPSE;
	public static final ModConfigSpec.ConfigValue<Boolean> STRIDER_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> TURTLE_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> VILLAGER_CORPSE;
	public static final ModConfigSpec.ConfigValue<Boolean> VINDICATOR_CORPSE;
	public static final ModConfigSpec.ConfigValue<Boolean> WARDEN_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> WITCH_CORPSE;
	public static final ModConfigSpec.ConfigValue<Boolean> WITHER_SKELETON_CORPSE;
	public static final ModConfigSpec.ConfigValue<Boolean> WITHER_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> WOLF_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> ZOGLIN_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> ZOMBIE_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> ZOMBIE_HORSE_CARCASS;
	public static final ModConfigSpec.ConfigValue<Boolean> ZOMBIE_VILLAGER_CORPSE;
	public static final ModConfigSpec.ConfigValue<Boolean> ZOMBIFIED_PIGLIN_CORPSE;
	public static final ModConfigSpec.ConfigValue<Boolean> FARMERS_DELIGHT;
	public static final ModConfigSpec.ConfigValue<Boolean> VAMPIRISM_HEART;
	public static final ModConfigSpec.ConfigValue<Boolean> VDELIGHT_EYE;
	public static final ModConfigSpec.ConfigValue<String> COIN_LOOTTABLE;
	static {
		BUILDER.push("General");
		FIRST_JOIN_BOOK = BUILDER.comment("Give the butchers guide on first join.").define("First Join Book", true);
		SHOW_HINTS = BUILDER.comment("Show GUI hints when looking at carcasses.").define("Show Hints", true);
		SPECIFIC_TOOLS = BUILDER.comment("Enable to have carcasses drop with ONLY cleavers. Disable to have carcasses drop no matter what kills the mob.").define("Only Cleavers Drop Carcasses", true);
		INSTANT_BLEED = BUILDER.comment("Instantly bleed carcasses.").define("Instant Bleeding", false);
		ORGANS = BUILDER.comment("Enable organ drops").define("Organs", true);
		WEIGHTED_CARCASS = BUILDER.comment("Enable carcass weight (slowness effect when carcasses are in your inventory)").define("Weighted Carcasses", true);
		LOOTING_ENCHANT = BUILDER.comment("Enable looting when butchering carcasses").define("Looting Enchantment", true);
		SULFUR_ORE = BUILDER.comment("Enable sulfur ore generation").define("Sulfur Ore Generation", true);
		SALT_GENERATION = BUILDER.comment("Enable salt generation").define("Salt Generation", true);
		BLOOD_PUDDLE = BUILDER.comment("Enable blood puddles dropping when no blood grate is below a carcass.").define("Blood Puddle", true);
		BLOOD_SPREAD = BUILDER.comment("Enable blood spread").define("Blood Spread", true);
		BUILDER.pop();
		BUILDER.push("Mobs");
		AXOLOTL_CARCASS = BUILDER.comment("Enable Axolotl Carcass").define("Axolotl", true);
		BAT_CARCASS = BUILDER.comment("Enable Bat Carcasses").define("Bat Carcass", true);
		BEE_CARCASS = BUILDER.comment("Enable Bee Carcasses").define("Bee Carcass", true);
		BMOOSHROOM_CARCASS = BUILDER.comment("Enable Brown Mooshroom Carcasses").define("Brown Mooshroom", true);
		CAMEL_CARCASS = BUILDER.comment("Enable Camel Carcasses").define("Camel", true);
		CAT_CARCASS = BUILDER.comment("Enable Cat Carcasses").define("Cat", true);
		CAVE_SPIDER_CARCASS = BUILDER.comment("Enable Cave Spider Carcasses").define("Cave Spider", true);
		CHICKEN_CARCASS = BUILDER.comment("Enable Chicken Carcasses").define("Chicken Carcass", true);
		COD_CARCASS = BUILDER.comment("Enable Cod Carcasses").define("Cod", true);
		COW_CARCASS = BUILDER.comment("Enable Cow Carcasses").define("Cow Carcass", true);
		CREEPER_CARCASS = BUILDER.comment("Enable Creeper Carcasses").define("Creeper", true);
		DOLPHIN_CARCASS = BUILDER.comment("Enable Dolphin Carcasses").define("Dolphin Carcass", true);
		DONKEY_CARCASS = BUILDER.comment("Enable Donkey Carcasses").define("Donkey", true);
		DROWNED_CARCASS = BUILDER.comment("Enable Drowned Corpses").define("Drowned", true);
		ELDER_GUARDIAN_CARCASS = BUILDER.comment("Enable Elder Guardian Carcass").define("Elder Guardian", true);
		EVOKER_CARCASS = BUILDER.comment("Enable Evoker Corpses").define("Evoker", true);
		END_DRAGON_CARCASS = BUILDER.comment("Enable Ender Dragon Carcass").define("Ender Dragon", true);
		ENDERMAN_CARCASS = BUILDER.comment("Enable Enderman Corpses").define("Enderman", true);
		ENDERMITE_CARCASS = BUILDER.comment("Enable Endermite Carcass").define("Endermite", true);
		FOX_CARCASS = BUILDER.comment("Enable Fox Carcasses").define("Fox", true);
		FROG_CARCASS = BUILDER.comment("Enable Frog Carcass").define("Frog", true);
		GLOW_SQUID_CARCASS = BUILDER.comment("Enable Glow Squid Carcasses").define("Glow Squid Carcass", true);
		GOAT_CARCASS = BUILDER.comment("Enable Goat Carcasses").define("Goat Carcass", true);
		GUARDIAN_CARCASS = BUILDER.comment("Enable Guardian Carcasses").define("Guardian", true);
		HOGLIN_CARCASS = BUILDER.comment("Enable Hoglin Carcasses").define("Hoglin", true);
		HORSE_CARCASS = BUILDER.comment("Enable Horse Carcasses").define("Horse", true);
		HUSK_CARCASS = BUILDER.comment("Enable Husk Corpses").define("Husk", true);
		IRON_GOLEM_CARCASS = BUILDER.comment("Enable Iron Golem Corpses").define("Iron Golem", true);
		LLAMA_CARCASS = BUILDER.comment("Enable Llama Carcass").define("Llama", true);
		MAGMA_CARCASS = BUILDER.comment("Enable Magma Cube Carcass").define("Magma Cube", true);
		MULE_CARCASS = BUILDER.comment("Enable Mule Carcasses").define("Mule", true);
		OCELOT_CARCASS = BUILDER.comment("Enable Ocelot Carcasses").define("Ocelot", true);
		PANDA_CARCASS = BUILDER.comment("Enable Panda Carcasses").define("Panda", true);
		PIG_CARCASS = BUILDER.comment("Enable Pig Carcasses").define("Pig Carcass", true);
		PIGLIN_CARCASS = BUILDER.comment("Enable Piglin Corpses").define("Piglin", true);
		PIGLIN_BRUTE_CARCASS = BUILDER.comment("Enable Piglin Brute Corpses").define("Piglin Brute", true);
		PILLAGER_CORPSE = BUILDER.comment("Enable Pillager Corpses").define("Pillager", true);
		POLAR_BEAR_CARCASS = BUILDER.comment("Enable Polar Bear Carcass").define("Polar Bear", true);
		PLAYER_CORPSE = BUILDER.comment("Enable Player Corpses").define("Player", true);
		PUFFERFISH_CARCASS = BUILDER.comment("Enable Pufferfish Carcass").define("Pufferfish", true);
		PHANTOM_CARCASS = BUILDER.comment("Enable Phantom Carcass").define("Phantom", true);
		RAVAGER_CARCASS = BUILDER.comment("Enable Ravager Carcass").define("Ravager", true);
		RABBIT_CARCASS = BUILDER.comment("Enable Rabbit Carcass").define("Rabbit", true);
		RMOOSHROOM_CARCASS = BUILDER.comment("Enable Red Mooshroom Carcasses").define("Red Mooshroom", true);
		SALMON_CARCASS = BUILDER.comment("Enable Salmon Carcasses").define("Salmon", true);
		SHEEP_CARCASS = BUILDER.comment("Enable Sheep Carcasses").define("Sheep Carcass", true);
		SHULKER_CARCASS = BUILDER.comment("Enable Shulker Carcass").define("Shulker", true);
		SILVERFISH_CARCASS = BUILDER.comment("Enable Silverfish Carcass").define("Silverfish", true);
		SKELETON_CORPSE = BUILDER.comment("Enable Skeleton Carcass").define("Skeleton", true);
		SKELETON_HORSE_CARCASS = BUILDER.comment("Enable Skeleton Horse Carcass").define("Skeleton Horse", true);
		SLIME_CARCASS = BUILDER.comment("Enable Slime Carcass").define("Slime", true);
		SNIFFER_CARCASS = BUILDER.comment("Enable Sniffer Carcass").define("Sniffer", true);
		SPIDER_CARCASS = BUILDER.comment("Enable Spider Carcasses").define("Spider Carcass", true);
		SQUID_CARCASS = BUILDER.comment("Enable Squid Carcasses").define("Squid Carcass", true);
		STRAY_CORPSE = BUILDER.comment("Enable Stray Carcass").define("Stray", true);
		STRIDER_CARCASS = BUILDER.comment("Enable Strider Carcass").define("Strider", true);
		TURTLE_CARCASS = BUILDER.comment("Enable Turtle Carcass").define("Turtle", true);
		VILLAGER_CORPSE = BUILDER.comment("Enable Villager Corpses").define("Villager", true);
		VINDICATOR_CORPSE = BUILDER.comment("Enable Vindicator Corpses").define("Vindicator", true);
		WARDEN_CARCASS = BUILDER.comment("Enable Warden Corpses").define("Warden", true);
		WITCH_CORPSE = BUILDER.comment("Enable Witch Corpses").define("Witch", true);
		WITHER_SKELETON_CORPSE = BUILDER.comment("Enable Wither Skeleton Corpses").define("Wither Skeleton", true);
		WITHER_CARCASS = BUILDER.comment("Enable Wither Corpses").define("Wither", true);
		WOLF_CARCASS = BUILDER.comment("Enable Wolf Corpses").define("Wolf", true);
		ZOGLIN_CARCASS = BUILDER.comment("Enable Zoglin Corpses").define("Zoglin", true);
		ZOMBIE_CARCASS = BUILDER.comment("Enable Zombie Corpses").define("Zombie", true);
		ZOMBIE_HORSE_CARCASS = BUILDER.comment("Enable Zombie Horse Corpses").define("Zombie Horse", true);
		ZOMBIE_VILLAGER_CORPSE = BUILDER.comment("Enable Zombie Villager Corpses").define("Zombie Villager", true);
		ZOMBIFIED_PIGLIN_CORPSE = BUILDER.comment("Enable Zombified Piglin Corpses").define("Zombified Piglin", true);
		BUILDER.pop();
		BUILDER.push("Farmers Delight Compatibility");
		FARMERS_DELIGHT = BUILDER.comment("Enable Farmers Delight Compatibility").define("Farmers Delight", false);
		BUILDER.pop();
		BUILDER.push("Vampirism Compatibility");
		VAMPIRISM_HEART = BUILDER.comment("Replaces heart drops with vampirisms hearts").define("Vampirism Heart", false);
		VDELIGHT_EYE = BUILDER.comment("Replaces eye drops with vampirisms eyes").define("Vampires Delight Eye", false);
		BUILDER.pop();
		BUILDER.push("Butchers Coin Reward");
		COIN_LOOTTABLE = BUILDER.comment("The loottable that the butchery coin rewards from.").define("Loottable", "minecraft:chests/end_city_treasure");
		BUILDER.pop();

		SPEC = BUILDER.build();
	}

}