/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.butchery.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.client.event.RegisterColorHandlersEvent;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;

import net.mcreator.butchery.block.ZombifiedPiglinHeadMountBlock;
import net.mcreator.butchery.block.ZombievillagerheadmountBlock;
import net.mcreator.butchery.block.ZombievillagerheadBlock;
import net.mcreator.butchery.block.ZombievillagercorpseBlock;
import net.mcreator.butchery.block.ZombiepiglinheadBlock;
import net.mcreator.butchery.block.ZombiepiglincorpseBlock;
import net.mcreator.butchery.block.ZombiehorseheadmountBlock;
import net.mcreator.butchery.block.ZombiehorseheadBlock;
import net.mcreator.butchery.block.ZombiehorsecarcassBlock;
import net.mcreator.butchery.block.ZombieheadmountBlock;
import net.mcreator.butchery.block.ZombiecorpseBlock;
import net.mcreator.butchery.block.ZoglinheadmountBlock;
import net.mcreator.butchery.block.ZoglinheadBlock;
import net.mcreator.butchery.block.ZoglincarcassBlock;
import net.mcreator.butchery.block.WoodenspitrotisserieBlock;
import net.mcreator.butchery.block.WolfskeletonBlock;
import net.mcreator.butchery.block.WolfheadmountBlock;
import net.mcreator.butchery.block.WolfheadBlock;
import net.mcreator.butchery.block.WolfcarcassBlock;
import net.mcreator.butchery.block.WitherskeletonheadmountBlock;
import net.mcreator.butchery.block.WitherskeletoncorpseBlock;
import net.mcreator.butchery.block.WithercarcassBlock;
import net.mcreator.butchery.block.WitchheadmountBlock;
import net.mcreator.butchery.block.WitchheadBlock;
import net.mcreator.butchery.block.WitchcorpseBlock;
import net.mcreator.butchery.block.WhitellamaheadmountBlock;
import net.mcreator.butchery.block.WhitellamaheadBlock;
import net.mcreator.butchery.block.WhitehorseheadmountBlock;
import net.mcreator.butchery.block.WhitehorseheadBlock;
import net.mcreator.butchery.block.WhitecatheadmountBlock;
import net.mcreator.butchery.block.WhitecatheadBlock;
import net.mcreator.butchery.block.WhitecatcarcassBlock;
import net.mcreator.butchery.block.WhiteLlamaCarcassBlock;
import net.mcreator.butchery.block.WarpedcounterBlock;
import net.mcreator.butchery.block.WarpedbutcherstableBlock;
import net.mcreator.butchery.block.WarpedbutcherdisplayBlock;
import net.mcreator.butchery.block.WardenheadBlock;
import net.mcreator.butchery.block.WardencarcassBlock;
import net.mcreator.butchery.block.WardenHeadMountBlock;
import net.mcreator.butchery.block.VindicatorheadBlock;
import net.mcreator.butchery.block.VindicatorcorpseBlock;
import net.mcreator.butchery.block.VindicatorHeadMountBlock;
import net.mcreator.butchery.block.VillagerheadBlock;
import net.mcreator.butchery.block.VillagercorpseBlock;
import net.mcreator.butchery.block.VillagerHeadMountBlock;
import net.mcreator.butchery.block.TurtleheadmountBlock;
import net.mcreator.butchery.block.TurtleheadBlock;
import net.mcreator.butchery.block.TurtlecarcassBlock;
import net.mcreator.butchery.block.TrimmedwardenHeadMountBlock;
import net.mcreator.butchery.block.TrimmedEnderDragonHeadMountBlock;
import net.mcreator.butchery.block.TaxidermytableBlock;
import net.mcreator.butchery.block.TabbycatheadmountBlock;
import net.mcreator.butchery.block.TabbycatheadBlock;
import net.mcreator.butchery.block.TabbycatcarcassBlock;
import net.mcreator.butchery.block.SulfuroreBlock;
import net.mcreator.butchery.block.StridercarcassBlock;
import net.mcreator.butchery.block.StrayheadmountBlock;
import net.mcreator.butchery.block.StrayheadBlock;
import net.mcreator.butchery.block.StraycorpseBlock;
import net.mcreator.butchery.block.SquidheadBlock;
import net.mcreator.butchery.block.SquidcarcassBlock;
import net.mcreator.butchery.block.SprucecounterBlock;
import net.mcreator.butchery.block.SprucebutcherstableBlock;
import net.mcreator.butchery.block.SpruceButcherdisplayBlock;
import net.mcreator.butchery.block.SpiketrapBlock;
import net.mcreator.butchery.block.SpiderheadmountBlock;
import net.mcreator.butchery.block.SpiderheadBlock;
import net.mcreator.butchery.block.SpidercarcassBlock;
import net.mcreator.butchery.block.SnowyfoxheadmountBlock;
import net.mcreator.butchery.block.SnowfoxheadBlock;
import net.mcreator.butchery.block.SnowfoxcarcassBlock;
import net.mcreator.butchery.block.SnifferheadBlock;
import net.mcreator.butchery.block.SniffercarcassblockBlock;
import net.mcreator.butchery.block.SmallslimecarcassBlock;
import net.mcreator.butchery.block.SmallemptyheadmountBlock;
import net.mcreator.butchery.block.SkinrackBlock;
import net.mcreator.butchery.block.SkeletonhorseheadmountBlock;
import net.mcreator.butchery.block.SkeletonhorseheadBlock;
import net.mcreator.butchery.block.SkeletonhorsecarcassBlock;
import net.mcreator.butchery.block.SkeletonheadmountBlock;
import net.mcreator.butchery.block.SkeletoncorpseBlock;
import net.mcreator.butchery.block.SkeletonBlock;
import net.mcreator.butchery.block.SilverfishheadmountBlock;
import net.mcreator.butchery.block.SilverfishheadBlock;
import net.mcreator.butchery.block.SilverfishcarcassBlock;
import net.mcreator.butchery.block.SiamesecatheadmountBlock;
import net.mcreator.butchery.block.SiamesecatheadBlock;
import net.mcreator.butchery.block.SiamesecatcarcassBlock;
import net.mcreator.butchery.block.ShulkercarcassBlock;
import net.mcreator.butchery.block.ShorthaircatheadmountBlock;
import net.mcreator.butchery.block.ShorthaircatheadBlock;
import net.mcreator.butchery.block.SheepskeletonBlock;
import net.mcreator.butchery.block.SheepheadBlock;
import net.mcreator.butchery.block.SheepcarcassBlock;
import net.mcreator.butchery.block.SheepHeadMountBlock;
import net.mcreator.butchery.block.SandBlock;
import net.mcreator.butchery.block.SaltformationtipBlock;
import net.mcreator.butchery.block.SaltformationmiddleBlock;
import net.mcreator.butchery.block.SaltformationfrustumBlock;
import net.mcreator.butchery.block.SaltformationbaseBlock;
import net.mcreator.butchery.block.SaltblockBlock;
import net.mcreator.butchery.block.SalmoncarcassBlock;
import net.mcreator.butchery.block.SalmonbarrelBlock;
import net.mcreator.butchery.block.RopeBlock;
import net.mcreator.butchery.block.RepairedirongolemheadmountBlock;
import net.mcreator.butchery.block.RepairedIrongolemlegsBlock;
import net.mcreator.butchery.block.RepairedIrongolemheadBlock;
import net.mcreator.butchery.block.RepairedIrongolembodyBlock;
import net.mcreator.butchery.block.RepairedIrongolemarmsBlock;
import net.mcreator.butchery.block.RepairedIrongolemBlock;
import net.mcreator.butchery.block.RegularblackhorsecarcassBlock;
import net.mcreator.butchery.block.RegularWhitehorsecarcassBlock;
import net.mcreator.butchery.block.RegularGrayhorsecarcassBlock;
import net.mcreator.butchery.block.RegularDarkbrownhorsecarcassBlock;
import net.mcreator.butchery.block.RegularCreamyhorsecarcassBlock;
import net.mcreator.butchery.block.RegularChestnuthorsecarcassBlock;
import net.mcreator.butchery.block.RegularBrownhorsecarcassBlock;
import net.mcreator.butchery.block.RedmooshroomheadBlock;
import net.mcreator.butchery.block.RedmooshroomcarcassBlock;
import net.mcreator.butchery.block.RedcatheadmountBlock;
import net.mcreator.butchery.block.RedcatheadBlock;
import net.mcreator.butchery.block.RedcatcarcassBlock;
import net.mcreator.butchery.block.RedMooshroomheadmountBlock;
import net.mcreator.butchery.block.RawsausagesBlock;
import net.mcreator.butchery.block.RawbloodsausagesBlock;
import net.mcreator.butchery.block.RavagerheadBlock;
import net.mcreator.butchery.block.RavagerHeadMountBlock;
import net.mcreator.butchery.block.RavagerBlock;
import net.mcreator.butchery.block.RagdollcatheadmountBlock;
import net.mcreator.butchery.block.RagdollcatheadBlock;
import net.mcreator.butchery.block.RagdollcatcarcassBlock;
import net.mcreator.butchery.block.RabbitheadBlock;
import net.mcreator.butchery.block.RabbitcarcassBlock;
import net.mcreator.butchery.block.RabbitHeadMountBlock;
import net.mcreator.butchery.block.PufferfishBlock;
import net.mcreator.butchery.block.PolarbearskeletonBlock;
import net.mcreator.butchery.block.PolarbearheadBlock;
import net.mcreator.butchery.block.PolarbearcarcassBlock;
import net.mcreator.butchery.block.PolarbearHeadMountBlock;
import net.mcreator.butchery.block.PlayercorpseBlock;
import net.mcreator.butchery.block.PlasticsheetcornerBlock;
import net.mcreator.butchery.block.PlasticsheetBlock;
import net.mcreator.butchery.block.PinkaxolotlheadmountBlock;
import net.mcreator.butchery.block.PinkaxolotlheadBlock;
import net.mcreator.butchery.block.PinkaxolotlcarcassBlock;
import net.mcreator.butchery.block.PillagerheadmountBlock;
import net.mcreator.butchery.block.PillagerheadBlock;
import net.mcreator.butchery.block.PillagercorpseBlock;
import net.mcreator.butchery.block.PigskeletonBlock;
import net.mcreator.butchery.block.PiglinskeletonBlock;
import net.mcreator.butchery.block.PiglincorpseBlock;
import net.mcreator.butchery.block.PiglinbruteheadBlock;
import net.mcreator.butchery.block.PiglinbrutecorpseBlock;
import net.mcreator.butchery.block.PiglinbruteHeadMountBlock;
import net.mcreator.butchery.block.PiglinHeadMountBlock;
import net.mcreator.butchery.block.PigheadBlock;
import net.mcreator.butchery.block.PigcarcassBlock;
import net.mcreator.butchery.block.PigHeadMountBlock;
import net.mcreator.butchery.block.PhotosBlock;
import net.mcreator.butchery.block.PhantomskeletonBlock;
import net.mcreator.butchery.block.PhantomheadmountBlock;
import net.mcreator.butchery.block.PhantomheadBlock;
import net.mcreator.butchery.block.PhantomcarcassBlock;
import net.mcreator.butchery.block.PestleandmortarBlock;
import net.mcreator.butchery.block.PersiancatheadmountBlock;
import net.mcreator.butchery.block.PersiancatheadBlock;
import net.mcreator.butchery.block.PersiancatcarcassBlock;
import net.mcreator.butchery.block.PandaskeletonBlock;
import net.mcreator.butchery.block.PandarugBlock;
import net.mcreator.butchery.block.PandaheadBlock;
import net.mcreator.butchery.block.PandacarcassBlock;
import net.mcreator.butchery.block.PandaHeadMountBlock;
import net.mcreator.butchery.block.OrangefrogcarcassBlock;
import net.mcreator.butchery.block.OcelotskeletonBlock;
import net.mcreator.butchery.block.OcelotheadmountBlock;
import net.mcreator.butchery.block.OcelotheadBlock;
import net.mcreator.butchery.block.OcelotcarcassBlock;
import net.mcreator.butchery.block.OakcounterBlock;
import net.mcreator.butchery.block.OakbutcherstableBlock;
import net.mcreator.butchery.block.OakbutcherdisplayBlock;
import net.mcreator.butchery.block.MuleskeletonBlock;
import net.mcreator.butchery.block.MuleheadmountBlock;
import net.mcreator.butchery.block.MuleheadBlock;
import net.mcreator.butchery.block.MulecarcassBlock;
import net.mcreator.butchery.block.MooshroomskeletonBlock;
import net.mcreator.butchery.block.MetaltrayBlock;
import net.mcreator.butchery.block.MetalbutcherstableBlock;
import net.mcreator.butchery.block.MediumslimecarcassBlock;
import net.mcreator.butchery.block.MediummagmacubecarcassBlock;
import net.mcreator.butchery.block.MeatgrinderBlock;
import net.mcreator.butchery.block.MangrovebutcherstableBlock;
import net.mcreator.butchery.block.MagmacubecarcassBlock;
import net.mcreator.butchery.block.LlamaskeletonBlock;
import net.mcreator.butchery.block.LargeemptyheadmountBlock;
import net.mcreator.butchery.block.JunglecounterBlock;
import net.mcreator.butchery.block.JunglebutcherstableBlock;
import net.mcreator.butchery.block.JunglebutcherdisplayBlock;
import net.mcreator.butchery.block.JelliecatheadmountBlock;
import net.mcreator.butchery.block.JelliecatheadBlock;
import net.mcreator.butchery.block.JelliecatcarcassBlock;
import net.mcreator.butchery.block.JarBlock;
import net.mcreator.butchery.block.IrongolemlegsBlock;
import net.mcreator.butchery.block.IrongolemheadmountBlock;
import net.mcreator.butchery.block.IrongolemheadBlock;
import net.mcreator.butchery.block.IrongolembodyBlock;
import net.mcreator.butchery.block.IrongolemarmsBlock;
import net.mcreator.butchery.block.IrongolemBlock;
import net.mcreator.butchery.block.InfectedBloodBlock;
import net.mcreator.butchery.block.HuskheadmountBlock;
import net.mcreator.butchery.block.HuskheadBlock;
import net.mcreator.butchery.block.HuskcorpseBlock;
import net.mcreator.butchery.block.HookBlock;
import net.mcreator.butchery.block.HoglinskeletonBlock;
import net.mcreator.butchery.block.HoglinheadmountBlock;
import net.mcreator.butchery.block.HoglinheadBlock;
import net.mcreator.butchery.block.HoglincarcassBlock;
import net.mcreator.butchery.block.HangingendermancarcassBlock;
import net.mcreator.butchery.block.HangingdrainedendermancarcassBlock;
import net.mcreator.butchery.block.GuardiancarcassBlock;
import net.mcreator.butchery.block.GreenfrogcarcassBlock;
import net.mcreator.butchery.block.GrayllamaheadmountBlock;
import net.mcreator.butchery.block.GrayllamaheadBlock;
import net.mcreator.butchery.block.GrayllamacarcassBlock;
import net.mcreator.butchery.block.GrayhorseheadmountBlock;
import net.mcreator.butchery.block.GrayhorseheadBlock;
import net.mcreator.butchery.block.GrayfrogcarcassBlock;
import net.mcreator.butchery.block.GoldaxolotlheadmountBlock;
import net.mcreator.butchery.block.GoldaxolotlcarcassBlock;
import net.mcreator.butchery.block.GoatskeletonBlock;
import net.mcreator.butchery.block.GoatrugBlock;
import net.mcreator.butchery.block.GoatheadBlock;
import net.mcreator.butchery.block.GoatcarcassBlock;
import net.mcreator.butchery.block.GoatHeadMountBlock;
import net.mcreator.butchery.block.GlowsquidheadBlock;
import net.mcreator.butchery.block.GlowsquidcarcassBlock;
import net.mcreator.butchery.block.GOLDaxolotlheadBlock;
import net.mcreator.butchery.block.FreezerBlock;
import net.mcreator.butchery.block.FoxskeletonBlock;
import net.mcreator.butchery.block.FoxheadBlock;
import net.mcreator.butchery.block.FoxcarcassBlock;
import net.mcreator.butchery.block.FoxHeadMountBlock;
import net.mcreator.butchery.block.FloorstandingSignBlock;
import net.mcreator.butchery.block.FishskeletonBlock;
import net.mcreator.butchery.block.EvokerheadBlock;
import net.mcreator.butchery.block.EvokercorpseBlock;
import net.mcreator.butchery.block.EvokerHeadMountBlock;
import net.mcreator.butchery.block.EndermiteheadmountBlock;
import net.mcreator.butchery.block.EndermiteheadBlock;
import net.mcreator.butchery.block.EndermiteBlock;
import net.mcreator.butchery.block.EndermanheadmountBlock;
import net.mcreator.butchery.block.EndermanheadBlock;
import net.mcreator.butchery.block.EndermancarcassBlock;
import net.mcreator.butchery.block.Enderdragoncut9Block;
import net.mcreator.butchery.block.Enderdragoncut8Block;
import net.mcreator.butchery.block.Enderdragoncut7Block;
import net.mcreator.butchery.block.Enderdragoncut6Block;
import net.mcreator.butchery.block.Enderdragoncut5Block;
import net.mcreator.butchery.block.Enderdragoncut4Block;
import net.mcreator.butchery.block.Enderdragoncut3Block;
import net.mcreator.butchery.block.Enderdragoncut2Block;
import net.mcreator.butchery.block.Enderdragoncut1Block;
import net.mcreator.butchery.block.Enderdragoncut14Block;
import net.mcreator.butchery.block.Enderdragoncut13Block;
import net.mcreator.butchery.block.Enderdragoncut12Block;
import net.mcreator.butchery.block.Enderdragoncut11Block;
import net.mcreator.butchery.block.Enderdragoncut10Block;
import net.mcreator.butchery.block.EnderdragoncarcassheadlessBlock;
import net.mcreator.butchery.block.EnderdragoncarcassBlock;
import net.mcreator.butchery.block.EnderDragonHeadMountBlock;
import net.mcreator.butchery.block.EmptywardentrimmedheadmountBlock;
import net.mcreator.butchery.block.EmptyturtleshellBlock;
import net.mcreator.butchery.block.EmptyheadmountBlock;
import net.mcreator.butchery.block.EmptydragontrimmedheadmountBlock;
import net.mcreator.butchery.block.ElderguardiancarcassBlock;
import net.mcreator.butchery.block.DrownedheadmountBlock;
import net.mcreator.butchery.block.DrownedheadBlock;
import net.mcreator.butchery.block.DrownedcorpseBlock;
import net.mcreator.butchery.block.DrainedzombievillagerBlock;
import net.mcreator.butchery.block.DrainedzombiecorpseBlock;
import net.mcreator.butchery.block.DrainedzoglincarcassBlock;
import net.mcreator.butchery.block.DrainedwitchcorpseBlock;
import net.mcreator.butchery.block.DrainedvillagerBlock;
import net.mcreator.butchery.block.DrainedstridercarcassBlock;
import net.mcreator.butchery.block.DrainedsniffercarcassblockBlock;
import net.mcreator.butchery.block.DrainedredmooshroomcarcassBlock;
import net.mcreator.butchery.block.DrainedrabbitcarcassBlock;
import net.mcreator.butchery.block.DrainedplayercorpseBlock;
import net.mcreator.butchery.block.DrainedpinkaxolotlcarcassBlock;
import net.mcreator.butchery.block.DrainedpiglincorpseBlock;
import net.mcreator.butchery.block.DrainedpigcarcassBlock;
import net.mcreator.butchery.block.DrainedphantomcarcassBlock;
import net.mcreator.butchery.block.DrainedpandacarcassBlock;
import net.mcreator.butchery.block.DrainedorangefrogcarcassBlock;
import net.mcreator.butchery.block.DrainedocelotcarcassBlock;
import net.mcreator.butchery.block.DrainedmulecarcassBlock;
import net.mcreator.butchery.block.DrainedhuskcorpseBlock;
import net.mcreator.butchery.block.DrainedhoglincarcassBlock;
import net.mcreator.butchery.block.DrainedguardiancarcassBlock;
import net.mcreator.butchery.block.DrainedgreenfrogcarcassBlock;
import net.mcreator.butchery.block.DrainedgrayfrogcarcassBlock;
import net.mcreator.butchery.block.DrainedgoatcarcassBlock;
import net.mcreator.butchery.block.DrainedfoxcarcassBlock;
import net.mcreator.butchery.block.DrainedevokercorpseBlock;
import net.mcreator.butchery.block.DrainedendermancarcassBlock;
import net.mcreator.butchery.block.DraineddrownedcorpseBlock;
import net.mcreator.butchery.block.DraineddonkeycarcassBlock;
import net.mcreator.butchery.block.DraineddolphincarcassBlock;
import net.mcreator.butchery.block.DrainedcreepercarcassBlock;
import net.mcreator.butchery.block.DrainedcowcarcassBlock;
import net.mcreator.butchery.block.DrainedchickencarcassBlock;
import net.mcreator.butchery.block.DrainedcamelcarcassBlock;
import net.mcreator.butchery.block.DrainedbrownmooshroomcarcassBlock;
import net.mcreator.butchery.block.DrainedbrownllamacarcassBlock;
import net.mcreator.butchery.block.DrainedblackcatcarcassBlock;
import net.mcreator.butchery.block.DrainedbatcarcassBlock;
import net.mcreator.butchery.block.DrainedallblackcatcarcassBlock;
import net.mcreator.butchery.block.DrainedZombiepiglincorpseBlock;
import net.mcreator.butchery.block.DrainedZombiehorsecarcassBlock;
import net.mcreator.butchery.block.DrainedWolfcarcassBlock;
import net.mcreator.butchery.block.DrainedWhitellamacarcassBlock;
import net.mcreator.butchery.block.DrainedWhitehorsecarcassBlock;
import net.mcreator.butchery.block.DrainedWhitecatcarcassBlock;
import net.mcreator.butchery.block.DrainedVindicatorcorpseBlock;
import net.mcreator.butchery.block.DrainedTurtlecarcassBlock;
import net.mcreator.butchery.block.DrainedTabbycatcarcassBlock;
import net.mcreator.butchery.block.DrainedSnowfoxcarcassBlock;
import net.mcreator.butchery.block.DrainedSiamesecatcarcassBlock;
import net.mcreator.butchery.block.DrainedSheepcarcassBlock;
import net.mcreator.butchery.block.DrainedRegularblackhorsecarcassBlock;
import net.mcreator.butchery.block.DrainedRegularDarkbrownhorsecarcassBlock;
import net.mcreator.butchery.block.DrainedRegularCreamyhorsecarcassBlock;
import net.mcreator.butchery.block.DrainedRegularChestnuthorsecarcassBlock;
import net.mcreator.butchery.block.DrainedRegularBrownhorsecarcassBlock;
import net.mcreator.butchery.block.DrainedRedcatcarcassBlock;
import net.mcreator.butchery.block.DrainedRagdollcatcarcassBlock;
import net.mcreator.butchery.block.DrainedPolarbearcarcassBlock;
import net.mcreator.butchery.block.DrainedPillagercorpseBlock;
import net.mcreator.butchery.block.DrainedPiglinbrutecorpseBlock;
import net.mcreator.butchery.block.DrainedPersiancatcarcassBlock;
import net.mcreator.butchery.block.DrainedJelliecatcarcassBlock;
import net.mcreator.butchery.block.DrainedGrayllamacarcassBlock;
import net.mcreator.butchery.block.DrainedGrayhorsecarcassBlock;
import net.mcreator.butchery.block.DrainedGoldaxolotlcarcassBlock;
import net.mcreator.butchery.block.DrainedCyanaxolotlcarcassBlock;
import net.mcreator.butchery.block.DrainedCreamyllamacarcassBlock;
import net.mcreator.butchery.block.DrainedCalicocatcarcassBlock;
import net.mcreator.butchery.block.DrainedBrownaxolotlcarcassBlock;
import net.mcreator.butchery.block.DrainedBritishshorthaircatcarcassBlock;
import net.mcreator.butchery.block.DrainedBlueaxolotlcarcassBlock;
import net.mcreator.butchery.block.DragonscaleblockBlock;
import net.mcreator.butchery.block.DonkeyskeletonBlock;
import net.mcreator.butchery.block.DonkeyheadmountBlock;
import net.mcreator.butchery.block.DonkeyheadBlock;
import net.mcreator.butchery.block.DonkeycarcassBlock;
import net.mcreator.butchery.block.DolphinskeletonBlock;
import net.mcreator.butchery.block.DolphinheadmountBlock;
import net.mcreator.butchery.block.DolphinheadBlock;
import net.mcreator.butchery.block.DolphincarcassBlock;
import net.mcreator.butchery.block.DioritebrickstairsBlock;
import net.mcreator.butchery.block.DioritebricksBlock;
import net.mcreator.butchery.block.DioriteBrickwallBlock;
import net.mcreator.butchery.block.DioriteBrickSlabBlock;
import net.mcreator.butchery.block.DeepslatesulfuroreBlock;
import net.mcreator.butchery.block.DarkoakcounterBlock;
import net.mcreator.butchery.block.DarkoakbutcherstableBlock;
import net.mcreator.butchery.block.DarkoakbutcherdisplayBlock;
import net.mcreator.butchery.block.DarkbrownhorseheadmountBlock;
import net.mcreator.butchery.block.DarkbrownhorseheadBlock;
import net.mcreator.butchery.block.CyanaxolotlheadmountBlock;
import net.mcreator.butchery.block.CyanaxolotlheadBlock;
import net.mcreator.butchery.block.CyanaxolotlcarcassBlock;
import net.mcreator.butchery.block.CrimsoncounterBlock;
import net.mcreator.butchery.block.CrimsonbutcherstableBlock;
import net.mcreator.butchery.block.CrimsonbutcherdisplayBlock;
import net.mcreator.butchery.block.CreeperskeletonBlock;
import net.mcreator.butchery.block.CreeperheadmountBlock;
import net.mcreator.butchery.block.CreepercarcassBlock;
import net.mcreator.butchery.block.CreamyllamaheadmountBlock;
import net.mcreator.butchery.block.CreamyllamaheadBlock;
import net.mcreator.butchery.block.CreamyllamacarcassBlock;
import net.mcreator.butchery.block.CreamyhorseheadmountBlock;
import net.mcreator.butchery.block.CreamyhorseheadBlock;
import net.mcreator.butchery.block.CowskeletonBlock;
import net.mcreator.butchery.block.CowheadmountBlock;
import net.mcreator.butchery.block.CowheadBlock;
import net.mcreator.butchery.block.CowcarcassBlock;
import net.mcreator.butchery.block.CookedsausagesBlock;
import net.mcreator.butchery.block.CookedbloodsausagesBlock;
import net.mcreator.butchery.block.CodcarcassBlock;
import net.mcreator.butchery.block.CodbarrelBlock;
import net.mcreator.butchery.block.ClingfilmBlock;
import net.mcreator.butchery.block.ChickenskeletonBlock;
import net.mcreator.butchery.block.ChickenheadmountBlock;
import net.mcreator.butchery.block.ChickenheadBlock;
import net.mcreator.butchery.block.ChickencarcassBlock;
import net.mcreator.butchery.block.ChestnuthorseheadmountBlock;
import net.mcreator.butchery.block.ChestnuthorseheadBlock;
import net.mcreator.butchery.block.CavespiderheadmountBlock;
import net.mcreator.butchery.block.CavespiderheadBlock;
import net.mcreator.butchery.block.CavespidercarcassBlock;
import net.mcreator.butchery.block.CatskeletonBlock;
import net.mcreator.butchery.block.CatcarcassBlock;
import net.mcreator.butchery.block.CashregisterblockBlock;
import net.mcreator.butchery.block.CanopyyellowBlock;
import net.mcreator.butchery.block.CanopyredBlock;
import net.mcreator.butchery.block.CanopypurpleBlock;
import net.mcreator.butchery.block.CanopypinkBlock;
import net.mcreator.butchery.block.CanopyorangeBlock;
import net.mcreator.butchery.block.CanopymagentaBlock;
import net.mcreator.butchery.block.CanopylimeBlock;
import net.mcreator.butchery.block.CanopylightgrayBlock;
import net.mcreator.butchery.block.CanopylightblueBlock;
import net.mcreator.butchery.block.CanopygreenBlock;
import net.mcreator.butchery.block.CanopygrayBlock;
import net.mcreator.butchery.block.CanopycyanBlock;
import net.mcreator.butchery.block.CanopybrownBlock;
import net.mcreator.butchery.block.CanopyblueBlock;
import net.mcreator.butchery.block.CanopyblackBlock;
import net.mcreator.butchery.block.CamelskeletonBlock;
import net.mcreator.butchery.block.CamelheadmountBlock;
import net.mcreator.butchery.block.CamelheadBlock;
import net.mcreator.butchery.block.CamelcarcassBlock;
import net.mcreator.butchery.block.CalicocatheadmountBlock;
import net.mcreator.butchery.block.CalicocatheadBlock;
import net.mcreator.butchery.block.CalicocatcarcassBlock;
import net.mcreator.butchery.block.ButcherstatueBlock;
import net.mcreator.butchery.block.BrownmooshroomheadBlock;
import net.mcreator.butchery.block.BrownmooshroomcarcassBlock;
import net.mcreator.butchery.block.BrownllamaheadmountBlock;
import net.mcreator.butchery.block.BrownllamaheadBlock;
import net.mcreator.butchery.block.BrownllamacarcassBlock;
import net.mcreator.butchery.block.BrownhorseheadmountBlock;
import net.mcreator.butchery.block.BrownhorseheadBlock;
import net.mcreator.butchery.block.BrownaxolotlheadmountBlock;
import net.mcreator.butchery.block.BrownaxolotlheadBlock;
import net.mcreator.butchery.block.BrownaxolotlcarcassBlock;
import net.mcreator.butchery.block.BrownMooshroomheadmountBlock;
import net.mcreator.butchery.block.BritishshorthaircatcarcassBlock;
import net.mcreator.butchery.block.BrainBlock;
import net.mcreator.butchery.block.BonebarrelBlock;
import net.mcreator.butchery.block.BlueaxolotlheadmountBlock;
import net.mcreator.butchery.block.BlueaxolotlheadBlock;
import net.mcreator.butchery.block.BlueaxolotlcarcassBlock;
import net.mcreator.butchery.block.BloodsplatterBlock;
import net.mcreator.butchery.block.BloodpuddleBlock;
import net.mcreator.butchery.block.BloodgrateBlock;
import net.mcreator.butchery.block.BloodBlock;
import net.mcreator.butchery.block.BlackhorseheadmountBlock;
import net.mcreator.butchery.block.BlackhorseheadBlock;
import net.mcreator.butchery.block.BlackcatheadmountBlock;
import net.mcreator.butchery.block.BlackcatheadBlock;
import net.mcreator.butchery.block.BlackcatcarcassBlock;
import net.mcreator.butchery.block.BirchcounterBlock;
import net.mcreator.butchery.block.BirchbutcherstableBlock;
import net.mcreator.butchery.block.BirchbutcherdisplayBlock;
import net.mcreator.butchery.block.BeeheadBlock;
import net.mcreator.butchery.block.BeecarcassBlock;
import net.mcreator.butchery.block.BearrugBlock;
import net.mcreator.butchery.block.BatskeletonBlock;
import net.mcreator.butchery.block.BatheadmountBlock;
import net.mcreator.butchery.block.BatheadBlock;
import net.mcreator.butchery.block.BatcarcassBlock;
import net.mcreator.butchery.block.BasinBlock;
import net.mcreator.butchery.block.AxolotlskeletonBlock;
import net.mcreator.butchery.block.AllblackcatheadmountBlock;
import net.mcreator.butchery.block.AllblackcatheadBlock;
import net.mcreator.butchery.block.AllblackcatcarcassBlock;
import net.mcreator.butchery.block.AcaciacounterBlock;
import net.mcreator.butchery.block.AcaciabutcherstableBlock;
import net.mcreator.butchery.block.AcaciabutcherdisplayBlock;
import net.mcreator.butchery.ButcheryMod;

public class ButcheryModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, ButcheryMod.MODID);
	public static final RegistryObject<Block> OAK_BUTCHERS_TABLE = REGISTRY.register("oak_butchers_table", () -> new OakbutcherstableBlock());
	public static final RegistryObject<Block> ACACIA_BUTCHERS_TABLE = REGISTRY.register("acacia_butchers_table", () -> new AcaciabutcherstableBlock());
	public static final RegistryObject<Block> BIRCH_BUTCHERS_TABLE = REGISTRY.register("birch_butchers_table", () -> new BirchbutcherstableBlock());
	public static final RegistryObject<Block> CRIMSON_BUTCHERS_TABLE = REGISTRY.register("crimson_butchers_table", () -> new CrimsonbutcherstableBlock());
	public static final RegistryObject<Block> DARK_OAK_BUTCHERS_TABLE = REGISTRY.register("dark_oak_butchers_table", () -> new DarkoakbutcherstableBlock());
	public static final RegistryObject<Block> JUNGLE_BUTCHERS_TABLE = REGISTRY.register("jungle_butchers_table", () -> new JunglebutcherstableBlock());
	public static final RegistryObject<Block> MANGROVE_BUTCHERS_TABLE = REGISTRY.register("mangrove_butchers_table", () -> new MangrovebutcherstableBlock());
	public static final RegistryObject<Block> SPRUCE_BUTCHERS_TABLE = REGISTRY.register("spruce_butchers_table", () -> new SprucebutcherstableBlock());
	public static final RegistryObject<Block> WARPED_BUTCHERS_TABLE = REGISTRY.register("warped_butchers_table", () -> new WarpedbutcherstableBlock());
	public static final RegistryObject<Block> HOOK = REGISTRY.register("hook", () -> new HookBlock());
	public static final RegistryObject<Block> METAL_BUTCHERS_TABLE = REGISTRY.register("metal_butchers_table", () -> new MetalbutcherstableBlock());
	public static final RegistryObject<Block> BLOOD_GRATE = REGISTRY.register("blood_grate", () -> new BloodgrateBlock());
	public static final RegistryObject<Block> BLOOD = REGISTRY.register("blood", () -> new BloodBlock());
	public static final RegistryObject<Block> MEAT_GRINDER = REGISTRY.register("meat_grinder", () -> new MeatgrinderBlock());
	public static final RegistryObject<Block> SKIN_RACK = REGISTRY.register("skin_rack", () -> new SkinrackBlock());
	public static final RegistryObject<Block> SALT_BLOCK = REGISTRY.register("salt_block", () -> new SaltblockBlock());
	public static final RegistryObject<Block> SALT_FORMATION_TIP = REGISTRY.register("salt_formation_tip", () -> new SaltformationtipBlock());
	public static final RegistryObject<Block> SALT_FORMATION_BASE = REGISTRY.register("salt_formation_base", () -> new SaltformationbaseBlock());
	public static final RegistryObject<Block> SALT_FORMATION_MIDDLE = REGISTRY.register("salt_formation_middle", () -> new SaltformationmiddleBlock());
	public static final RegistryObject<Block> SALT_FORMATION_FRUSTUM = REGISTRY.register("salt_formation_frustum", () -> new SaltformationfrustumBlock());
	public static final RegistryObject<Block> BASIN = REGISTRY.register("basin", () -> new BasinBlock());
	public static final RegistryObject<Block> BLOOD_PUDDLE = REGISTRY.register("blood_puddle", () -> new BloodpuddleBlock());
	public static final RegistryObject<Block> PIG_CARCASS = REGISTRY.register("pig_carcass", () -> new PigcarcassBlock());
	public static final RegistryObject<Block> PIG_HEAD = REGISTRY.register("pig_head", () -> new PigheadBlock());
	public static final RegistryObject<Block> DRAINED_PIG_CARCASS = REGISTRY.register("drained_pig_carcass", () -> new DrainedpigcarcassBlock());
	public static final RegistryObject<Block> DRAINED_COW_CARCASS = REGISTRY.register("drained_cow_carcass", () -> new DrainedcowcarcassBlock());
	public static final RegistryObject<Block> COW_CARCASS = REGISTRY.register("cow_carcass", () -> new CowcarcassBlock());
	public static final RegistryObject<Block> COW_HEAD = REGISTRY.register("cow_head", () -> new CowheadBlock());
	public static final RegistryObject<Block> SHEEP_CARCASS = REGISTRY.register("sheep_carcass", () -> new SheepcarcassBlock());
	public static final RegistryObject<Block> DRAINED_SHEEP_CARCASS = REGISTRY.register("drained_sheep_carcass", () -> new DrainedSheepcarcassBlock());
	public static final RegistryObject<Block> SHEEP_HEAD = REGISTRY.register("sheep_head", () -> new SheepheadBlock());
	public static final RegistryObject<Block> CHICKEN_CARCASS = REGISTRY.register("chicken_carcass", () -> new ChickencarcassBlock());
	public static final RegistryObject<Block> DRAINED_CHICKEN_CARCASS = REGISTRY.register("drained_chicken_carcass", () -> new DrainedchickencarcassBlock());
	public static final RegistryObject<Block> CHICKEN_HEAD = REGISTRY.register("chicken_head", () -> new ChickenheadBlock());
	public static final RegistryObject<Block> BAT_CARCASS = REGISTRY.register("bat_carcass", () -> new BatcarcassBlock());
	public static final RegistryObject<Block> BAT_HEAD = REGISTRY.register("bat_head", () -> new BatheadBlock());
	public static final RegistryObject<Block> DRAINED_BAT_CARCASS = REGISTRY.register("drained_bat_carcass", () -> new DrainedbatcarcassBlock());
	public static final RegistryObject<Block> DOLPHIN_CARCASS = REGISTRY.register("dolphin_carcass", () -> new DolphincarcassBlock());
	public static final RegistryObject<Block> DOLPHIN_HEAD = REGISTRY.register("dolphin_head", () -> new DolphinheadBlock());
	public static final RegistryObject<Block> DRAINED_DOLPHIN_CARCASS = REGISTRY.register("drained_dolphin_carcass", () -> new DraineddolphincarcassBlock());
	public static final RegistryObject<Block> GLOW_SQUID_CARCASS = REGISTRY.register("glow_squid_carcass", () -> new GlowsquidcarcassBlock());
	public static final RegistryObject<Block> GLOW_SQUID_HEAD = REGISTRY.register("glow_squid_head", () -> new GlowsquidheadBlock());
	public static final RegistryObject<Block> SQUID_CARCASS = REGISTRY.register("squid_carcass", () -> new SquidcarcassBlock());
	public static final RegistryObject<Block> SQUID_HEAD = REGISTRY.register("squid_head", () -> new SquidheadBlock());
	public static final RegistryObject<Block> GOAT_CARCASS = REGISTRY.register("goat_carcass", () -> new GoatcarcassBlock());
	public static final RegistryObject<Block> GOAT_HEAD = REGISTRY.register("goat_head", () -> new GoatheadBlock());
	public static final RegistryObject<Block> DRAINED_GOAT_CARCASS = REGISTRY.register("drained_goat_carcass", () -> new DrainedgoatcarcassBlock());
	public static final RegistryObject<Block> RED_MOOSHROOM_CARCASS = REGISTRY.register("red_mooshroom_carcass", () -> new RedmooshroomcarcassBlock());
	public static final RegistryObject<Block> RED_MOOSHROOM_HEAD = REGISTRY.register("red_mooshroom_head", () -> new RedmooshroomheadBlock());
	public static final RegistryObject<Block> DRAINED_RED_MOOSHROOM_CARCASS = REGISTRY.register("drained_red_mooshroom_carcass", () -> new DrainedredmooshroomcarcassBlock());
	public static final RegistryObject<Block> BROWN_MOOSHROOM_CARCASS = REGISTRY.register("brown_mooshroom_carcass", () -> new BrownmooshroomcarcassBlock());
	public static final RegistryObject<Block> DRAINED_BROWN_MOOSHROOM_CARCASS = REGISTRY.register("drained_brown_mooshroom_carcass", () -> new DrainedbrownmooshroomcarcassBlock());
	public static final RegistryObject<Block> BROWN_MOOSHROOM_HEAD = REGISTRY.register("brown_mooshroom_head", () -> new BrownmooshroomheadBlock());
	public static final RegistryObject<Block> OCELOT_CARCASS = REGISTRY.register("ocelot_carcass", () -> new OcelotcarcassBlock());
	public static final RegistryObject<Block> OCELOT_HEAD = REGISTRY.register("ocelot_head", () -> new OcelotheadBlock());
	public static final RegistryObject<Block> DRAINED_OCELOT_CARCASS = REGISTRY.register("drained_ocelot_carcass", () -> new DrainedocelotcarcassBlock());
	public static final RegistryObject<Block> CAMEL_CARCASS = REGISTRY.register("camel_carcass", () -> new CamelcarcassBlock());
	public static final RegistryObject<Block> DRAINED_CAMEL_CARCASS = REGISTRY.register("drained_camel_carcass", () -> new DrainedcamelcarcassBlock());
	public static final RegistryObject<Block> CAVE_SPIDER_CARCASS = REGISTRY.register("cave_spider_carcass", () -> new CavespidercarcassBlock());
	public static final RegistryObject<Block> CAVE_SPIDER_HEAD = REGISTRY.register("cave_spider_head", () -> new CavespiderheadBlock());
	public static final RegistryObject<Block> SPIDER_CARCASS = REGISTRY.register("spider_carcass", () -> new SpidercarcassBlock());
	public static final RegistryObject<Block> SPIDER_HEAD = REGISTRY.register("spider_head", () -> new SpiderheadBlock());
	public static final RegistryObject<Block> CAMEL_HEAD = REGISTRY.register("camel_head", () -> new CamelheadBlock());
	public static final RegistryObject<Block> COD_CARCASS = REGISTRY.register("cod_carcass", () -> new CodcarcassBlock());
	public static final RegistryObject<Block> SALMON_CARCASS = REGISTRY.register("salmon_carcass", () -> new SalmoncarcassBlock());
	public static final RegistryObject<Block> CREEPER_CARCASS = REGISTRY.register("creeper_carcass", () -> new CreepercarcassBlock());
	public static final RegistryObject<Block> DRAINED_CREEPER_CARCASS = REGISTRY.register("drained_creeper_carcass", () -> new DrainedcreepercarcassBlock());
	public static final RegistryObject<Block> DONKEY_CARCASS = REGISTRY.register("donkey_carcass", () -> new DonkeycarcassBlock());
	public static final RegistryObject<Block> DRAINED_DONKEY_CARCASS = REGISTRY.register("drained_donkey_carcass", () -> new DraineddonkeycarcassBlock());
	public static final RegistryObject<Block> DONKEY_HEAD = REGISTRY.register("donkey_head", () -> new DonkeyheadBlock());
	public static final RegistryObject<Block> MULE_CARCASS = REGISTRY.register("mule_carcass", () -> new MulecarcassBlock());
	public static final RegistryObject<Block> MULE_HEAD = REGISTRY.register("mule_head", () -> new MuleheadBlock());
	public static final RegistryObject<Block> DRAINED_MULE_CARCASS = REGISTRY.register("drained_mule_carcass", () -> new DrainedmulecarcassBlock());
	public static final RegistryObject<Block> DROWNED_CORPSE = REGISTRY.register("drowned_corpse", () -> new DrownedcorpseBlock());
	public static final RegistryObject<Block> DROWNED_HEAD = REGISTRY.register("drowned_head", () -> new DrownedheadBlock());
	public static final RegistryObject<Block> DRAINED_DROWNED_CORPSE = REGISTRY.register("drained_drowned_corpse", () -> new DraineddrownedcorpseBlock());
	public static final RegistryObject<Block> DRAINED_HUSK_CORPSE = REGISTRY.register("drained_husk_corpse", () -> new DrainedhuskcorpseBlock());
	public static final RegistryObject<Block> HUSK_CORPSE = REGISTRY.register("husk_corpse", () -> new HuskcorpseBlock());
	public static final RegistryObject<Block> HUSK_HEAD = REGISTRY.register("husk_head", () -> new HuskheadBlock());
	public static final RegistryObject<Block> ZOMBIE_CORPSE = REGISTRY.register("zombie_corpse", () -> new ZombiecorpseBlock());
	public static final RegistryObject<Block> DRAINED_ZOMBIE_CORPSE = REGISTRY.register("drained_zombie_corpse", () -> new DrainedzombiecorpseBlock());
	public static final RegistryObject<Block> EVOKER_CORPSE = REGISTRY.register("evoker_corpse", () -> new EvokercorpseBlock());
	public static final RegistryObject<Block> EVOKER_HEAD = REGISTRY.register("evoker_head", () -> new EvokerheadBlock());
	public static final RegistryObject<Block> FOX_CARCASS = REGISTRY.register("fox_carcass", () -> new FoxcarcassBlock());
	public static final RegistryObject<Block> FOX_HEAD = REGISTRY.register("fox_head", () -> new FoxheadBlock());
	public static final RegistryObject<Block> DRAINED_FOX_CARCASS = REGISTRY.register("drained_fox_carcass", () -> new DrainedfoxcarcassBlock());
	public static final RegistryObject<Block> SNOW_FOX_CARCASS = REGISTRY.register("snow_fox_carcass", () -> new SnowfoxcarcassBlock());
	public static final RegistryObject<Block> SNOW_FOX_HEAD = REGISTRY.register("snow_fox_head", () -> new SnowfoxheadBlock());
	public static final RegistryObject<Block> DRAINED_SNOWFOX_CARCASS = REGISTRY.register("drained_snowfox_carcass", () -> new DrainedSnowfoxcarcassBlock());
	public static final RegistryObject<Block> GUARDIAN_CARCASS = REGISTRY.register("guardian_carcass", () -> new GuardiancarcassBlock());
	public static final RegistryObject<Block> DRAINED_GUARDIAN_CARCASS = REGISTRY.register("drained_guardian_carcass", () -> new DrainedguardiancarcassBlock());
	public static final RegistryObject<Block> HOGLIN_CARCASS = REGISTRY.register("hoglin_carcass", () -> new HoglincarcassBlock());
	public static final RegistryObject<Block> HOGLIN_HEAD = REGISTRY.register("hoglin_head", () -> new HoglinheadBlock());
	public static final RegistryObject<Block> DRAINED_HOGLIN_CARCASS = REGISTRY.register("drained_hoglin_carcass", () -> new DrainedhoglincarcassBlock());
	public static final RegistryObject<Block> PANDA_CARCASS = REGISTRY.register("panda_carcass", () -> new PandacarcassBlock());
	public static final RegistryObject<Block> PANDA_HEAD = REGISTRY.register("panda_head", () -> new PandaheadBlock());
	public static final RegistryObject<Block> DRAINED_PANDA_CARCASS = REGISTRY.register("drained_panda_carcass", () -> new DrainedpandacarcassBlock());
	public static final RegistryObject<Block> PIGLIN_CORPSE = REGISTRY.register("piglin_corpse", () -> new PiglincorpseBlock());
	public static final RegistryObject<Block> DRAINED_PIGLIN_CORPSE = REGISTRY.register("drained_piglin_corpse", () -> new DrainedpiglincorpseBlock());
	public static final RegistryObject<Block> PIGLIN_BRUTE_CORPSE = REGISTRY.register("piglin_brute_corpse", () -> new PiglinbrutecorpseBlock());
	public static final RegistryObject<Block> PIGLIN_BRUTE_HEAD = REGISTRY.register("piglin_brute_head", () -> new PiglinbruteheadBlock());
	public static final RegistryObject<Block> DRAINED_PIGLIN_BRUTE_CORPSE = REGISTRY.register("drained_piglin_brute_corpse", () -> new DrainedPiglinbrutecorpseBlock());
	public static final RegistryObject<Block> DRAINED_EVOKER_CORPSE = REGISTRY.register("drained_evoker_corpse", () -> new DrainedevokercorpseBlock());
	public static final RegistryObject<Block> PILLAGER_CORPSE = REGISTRY.register("pillager_corpse", () -> new PillagercorpseBlock());
	public static final RegistryObject<Block> PILLAGER_HEAD = REGISTRY.register("pillager_head", () -> new PillagerheadBlock());
	public static final RegistryObject<Block> DRAINED_PILLAGER_CORPSE = REGISTRY.register("drained_pillager_corpse", () -> new DrainedPillagercorpseBlock());
	public static final RegistryObject<Block> VINDICATOR_CORPSE = REGISTRY.register("vindicator_corpse", () -> new VindicatorcorpseBlock());
	public static final RegistryObject<Block> VINDICATOR_HEAD = REGISTRY.register("vindicator_head", () -> new VindicatorheadBlock());
	public static final RegistryObject<Block> DRAINED_VINDICATOR_CORPSE = REGISTRY.register("drained_vindicator_corpse", () -> new DrainedVindicatorcorpseBlock());
	public static final RegistryObject<Block> POLAR_BEAR_CARCASS = REGISTRY.register("polar_bear_carcass", () -> new PolarbearcarcassBlock());
	public static final RegistryObject<Block> POLAR_BEAR_HEAD = REGISTRY.register("polar_bear_head", () -> new PolarbearheadBlock());
	public static final RegistryObject<Block> DRAINED_POLAR_BEAR_CARCASS = REGISTRY.register("drained_polar_bear_carcass", () -> new DrainedPolarbearcarcassBlock());
	public static final RegistryObject<Block> PUFFERFISH = REGISTRY.register("pufferfish", () -> new PufferfishBlock());
	public static final RegistryObject<Block> RABBIT_CARCASS = REGISTRY.register("rabbit_carcass", () -> new RabbitcarcassBlock());
	public static final RegistryObject<Block> RABBIT_HEAD = REGISTRY.register("rabbit_head", () -> new RabbitheadBlock());
	public static final RegistryObject<Block> DRAINED_RABBIT_CARCASS = REGISTRY.register("drained_rabbit_carcass", () -> new DrainedrabbitcarcassBlock());
	public static final RegistryObject<Block> SHULKER_CARCASS = REGISTRY.register("shulker_carcass", () -> new ShulkercarcassBlock());
	public static final RegistryObject<Block> SILVERFISH_CARCASS = REGISTRY.register("silverfish_carcass", () -> new SilverfishcarcassBlock());
	public static final RegistryObject<Block> SKELETON_CORPSE = REGISTRY.register("skeleton_corpse", () -> new SkeletoncorpseBlock());
	public static final RegistryObject<Block> STRAY_CORPSE = REGISTRY.register("stray_corpse", () -> new StraycorpseBlock());
	public static final RegistryObject<Block> STRAY_HEAD = REGISTRY.register("stray_head", () -> new StrayheadBlock());
	public static final RegistryObject<Block> MEDIUM_SLIME_CARCASS = REGISTRY.register("medium_slime_carcass", () -> new MediumslimecarcassBlock());
	public static final RegistryObject<Block> SMALL_SLIME_CARCASS = REGISTRY.register("small_slime_carcass", () -> new SmallslimecarcassBlock());
	public static final RegistryObject<Block> MEDIUM_MAGMA_CUBE_CARCASS = REGISTRY.register("medium_magma_cube_carcass", () -> new MediummagmacubecarcassBlock());
	public static final RegistryObject<Block> MAGMA_CUBE_CARCASS = REGISTRY.register("magma_cube_carcass", () -> new MagmacubecarcassBlock());
	public static final RegistryObject<Block> STRIDER_CARCASS = REGISTRY.register("strider_carcass", () -> new StridercarcassBlock());
	public static final RegistryObject<Block> DRAINED_STRIDER_CARCASS = REGISTRY.register("drained_strider_carcass", () -> new DrainedstridercarcassBlock());
	public static final RegistryObject<Block> VILLAGER_CORPSE = REGISTRY.register("villager_corpse", () -> new VillagercorpseBlock());
	public static final RegistryObject<Block> VILLAGER_HEAD = REGISTRY.register("villager_head", () -> new VillagerheadBlock());
	public static final RegistryObject<Block> DRAINED_VILLAGER = REGISTRY.register("drained_villager", () -> new DrainedvillagerBlock());
	public static final RegistryObject<Block> ZOMBIE_VILLAGER_CORPSE = REGISTRY.register("zombie_villager_corpse", () -> new ZombievillagercorpseBlock());
	public static final RegistryObject<Block> ZOMBIE_VILLAGER_HEAD = REGISTRY.register("zombie_villager_head", () -> new ZombievillagerheadBlock());
	public static final RegistryObject<Block> DRAINED_ZOMBIE_VILLAGER = REGISTRY.register("drained_zombie_villager", () -> new DrainedzombievillagerBlock());
	public static final RegistryObject<Block> ZOMBIFIED_PIGLIN_CORPSE = REGISTRY.register("zombified_piglin_corpse", () -> new ZombiepiglincorpseBlock());
	public static final RegistryObject<Block> DRAINED_ZOMBIFIED_PIGLIN_CORPSE = REGISTRY.register("drained_zombified_piglin_corpse", () -> new DrainedZombiepiglincorpseBlock());
	public static final RegistryObject<Block> ZOMBIFIED_PIGLIN_HEAD = REGISTRY.register("zombified_piglin_head", () -> new ZombiepiglinheadBlock());
	public static final RegistryObject<Block> WITHER_SKELETON_CORPSE = REGISTRY.register("wither_skeleton_corpse", () -> new WitherskeletoncorpseBlock());
	public static final RegistryObject<Block> TURTLE_CARCASS = REGISTRY.register("turtle_carcass", () -> new TurtlecarcassBlock());
	public static final RegistryObject<Block> TURTLE_HEAD = REGISTRY.register("turtle_head", () -> new TurtleheadBlock());
	public static final RegistryObject<Block> DRAINED_TURTLE_CARCASS = REGISTRY.register("drained_turtle_carcass", () -> new DrainedTurtlecarcassBlock());
	public static final RegistryObject<Block> EMPTY_TURTLE_SHELL = REGISTRY.register("empty_turtle_shell", () -> new EmptyturtleshellBlock());
	public static final RegistryObject<Block> METAL_TRAY = REGISTRY.register("metal_tray", () -> new MetaltrayBlock());
	public static final RegistryObject<Block> GRAY_FROG_CARCASS = REGISTRY.register("gray_frog_carcass", () -> new GrayfrogcarcassBlock());
	public static final RegistryObject<Block> DRAINED_GRAY_FROG_CARCASS = REGISTRY.register("drained_gray_frog_carcass", () -> new DrainedgrayfrogcarcassBlock());
	public static final RegistryObject<Block> GREEN_FROG_CARCASS = REGISTRY.register("green_frog_carcass", () -> new GreenfrogcarcassBlock());
	public static final RegistryObject<Block> DRAINED_GREEN_FROG_CARCASS = REGISTRY.register("drained_green_frog_carcass", () -> new DrainedgreenfrogcarcassBlock());
	public static final RegistryObject<Block> ORANGE_FROG_CARCASS = REGISTRY.register("orange_frog_carcass", () -> new OrangefrogcarcassBlock());
	public static final RegistryObject<Block> DRAINED_ORANGE_FROG_CARCASS = REGISTRY.register("drained_orange_frog_carcass", () -> new DrainedorangefrogcarcassBlock());
	public static final RegistryObject<Block> BROWN_LLAMA_CARCASS = REGISTRY.register("brown_llama_carcass", () -> new BrownllamacarcassBlock());
	public static final RegistryObject<Block> DRAINED_BROWN_LLAMA_CARCASS = REGISTRY.register("drained_brown_llama_carcass", () -> new DrainedbrownllamacarcassBlock());
	public static final RegistryObject<Block> BROWN_LLAMA_HEAD = REGISTRY.register("brown_llama_head", () -> new BrownllamaheadBlock());
	public static final RegistryObject<Block> CREAMY_LLAMA_CARCASS = REGISTRY.register("creamy_llama_carcass", () -> new CreamyllamacarcassBlock());
	public static final RegistryObject<Block> DRAINED_CREAMY_LLAMA_CARCASS = REGISTRY.register("drained_creamy_llama_carcass", () -> new DrainedCreamyllamacarcassBlock());
	public static final RegistryObject<Block> CREAMY_LLAMA_HEAD = REGISTRY.register("creamy_llama_head", () -> new CreamyllamaheadBlock());
	public static final RegistryObject<Block> GRAY_LLAMA_CARCASS = REGISTRY.register("gray_llama_carcass", () -> new GrayllamacarcassBlock());
	public static final RegistryObject<Block> DRAINED_GRAY_LLAMA_CARCASS = REGISTRY.register("drained_gray_llama_carcass", () -> new DrainedGrayllamacarcassBlock());
	public static final RegistryObject<Block> GRAY_LLAMA_HEAD = REGISTRY.register("gray_llama_head", () -> new GrayllamaheadBlock());
	public static final RegistryObject<Block> DRAINED_WHITE_LLAMA_CARCASS = REGISTRY.register("drained_white_llama_carcass", () -> new DrainedWhitellamacarcassBlock());
	public static final RegistryObject<Block> WHITE_LLAMA_HEAD = REGISTRY.register("white_llama_head", () -> new WhitellamaheadBlock());
	public static final RegistryObject<Block> WHITE_LLAMA_CARCASS = REGISTRY.register("white_llama_carcass", () -> new WhiteLlamaCarcassBlock());
	public static final RegistryObject<Block> FREEZER = REGISTRY.register("freezer", () -> new FreezerBlock());
	public static final RegistryObject<Block> TAXIDERMY_TABLE = REGISTRY.register("taxidermy_table", () -> new TaxidermytableBlock());
	public static final RegistryObject<Block> BROWN_LLAMA_HEAD_MOUNT = REGISTRY.register("brown_llama_head_mount", () -> new BrownllamaheadmountBlock());
	public static final RegistryObject<Block> CAMEL_HEAD_MOUNT = REGISTRY.register("camel_head_mount", () -> new CamelheadmountBlock());
	public static final RegistryObject<Block> CAVE_SPIDER_HEAD_MOUNT = REGISTRY.register("cave_spider_head_mount", () -> new CavespiderheadmountBlock());
	public static final RegistryObject<Block> CHICKEN_HEAD_MOUNT = REGISTRY.register("chicken_head_mount", () -> new ChickenheadmountBlock());
	public static final RegistryObject<Block> COW_HEAD_MOUNT = REGISTRY.register("cow_head_mount", () -> new CowheadmountBlock());
	public static final RegistryObject<Block> CREAMY_LLAMA_HEAD_MOUNT = REGISTRY.register("creamy_llama_head_mount", () -> new CreamyllamaheadmountBlock());
	public static final RegistryObject<Block> CREEPER_HEAD_MOUNT = REGISTRY.register("creeper_head_mount", () -> new CreeperheadmountBlock());
	public static final RegistryObject<Block> DOLPHIN_HEAD_MOUNT = REGISTRY.register("dolphin_head_mount", () -> new DolphinheadmountBlock());
	public static final RegistryObject<Block> DROWNED_HEAD_MOUNT = REGISTRY.register("drowned_head_mount", () -> new DrownedheadmountBlock());
	public static final RegistryObject<Block> EMPTY_HEAD_MOUNT = REGISTRY.register("empty_head_mount", () -> new EmptyheadmountBlock());
	public static final RegistryObject<Block> ENDERMAN_HEAD_MOUNT = REGISTRY.register("enderman_head_mount", () -> new EndermanheadmountBlock());
	public static final RegistryObject<Block> FOX_HEAD_MOUNT = REGISTRY.register("fox_head_mount", () -> new FoxHeadMountBlock());
	public static final RegistryObject<Block> GOAT_HEAD_MOUNT = REGISTRY.register("goat_head_mount", () -> new GoatHeadMountBlock());
	public static final RegistryObject<Block> GRAY_LLAMA_HEAD_MOUNT = REGISTRY.register("gray_llama_head_mount", () -> new GrayllamaheadmountBlock());
	public static final RegistryObject<Block> HOGLIN_HEAD_MOUNT = REGISTRY.register("hoglin_head_mount", () -> new HoglinheadmountBlock());
	public static final RegistryObject<Block> HUSK_HEAD_MOUNT = REGISTRY.register("husk_head_mount", () -> new HuskheadmountBlock());
	public static final RegistryObject<Block> LARGE_EMPTY_HEAD_MOUNT = REGISTRY.register("large_empty_head_mount", () -> new LargeemptyheadmountBlock());
	public static final RegistryObject<Block> PANDA_HEAD_MOUNT = REGISTRY.register("panda_head_mount", () -> new PandaHeadMountBlock());
	public static final RegistryObject<Block> PIG_HEAD_MOUNT = REGISTRY.register("pig_head_mount", () -> new PigHeadMountBlock());
	public static final RegistryObject<Block> PILLAGER_HEAD_MOUNT = REGISTRY.register("pillager_head_mount", () -> new PillagerheadmountBlock());
	public static final RegistryObject<Block> POLARBEAR_HEAD_MOUNT = REGISTRY.register("polarbear_head_mount", () -> new PolarbearHeadMountBlock());
	public static final RegistryObject<Block> SHEEP_HEAD_MOUNT = REGISTRY.register("sheep_head_mount", () -> new SheepHeadMountBlock());
	public static final RegistryObject<Block> SKELETON_HEAD_MOUNT = REGISTRY.register("skeleton_head_mount", () -> new SkeletonheadmountBlock());
	public static final RegistryObject<Block> SNOWY_FOX_HEAD_MOUNT = REGISTRY.register("snowy_fox_head_mount", () -> new SnowyfoxheadmountBlock());
	public static final RegistryObject<Block> SPIDER_HEAD_MOUNT = REGISTRY.register("spider_head_mount", () -> new SpiderheadmountBlock());
	public static final RegistryObject<Block> VILLAGER_HEAD_MOUNT = REGISTRY.register("villager_head_mount", () -> new VillagerHeadMountBlock());
	public static final RegistryObject<Block> WHITE_LLAMA_HEAD_MOUNT = REGISTRY.register("white_llama_head_mount", () -> new WhitellamaheadmountBlock());
	public static final RegistryObject<Block> ZOMBIE_HEAD_MOUNT = REGISTRY.register("zombie_head_mount", () -> new ZombieheadmountBlock());
	public static final RegistryObject<Block> ZOMBIE_VILLAGER_HEAD_MOUNT = REGISTRY.register("zombie_villager_head_mount", () -> new ZombievillagerheadmountBlock());
	public static final RegistryObject<Block> OCELOT_HEAD_MOUNT = REGISTRY.register("ocelot_head_mount", () -> new OcelotheadmountBlock());
	public static final RegistryObject<Block> CANOPY_BLACK = REGISTRY.register("canopy_black", () -> new CanopyblackBlock());
	public static final RegistryObject<Block> CANOPY_BLUE = REGISTRY.register("canopy_blue", () -> new CanopyblueBlock());
	public static final RegistryObject<Block> CANOPY_BROWN = REGISTRY.register("canopy_brown", () -> new CanopybrownBlock());
	public static final RegistryObject<Block> CANOPY_CYAN = REGISTRY.register("canopy_cyan", () -> new CanopycyanBlock());
	public static final RegistryObject<Block> CANOPY_GRAY = REGISTRY.register("canopy_gray", () -> new CanopygrayBlock());
	public static final RegistryObject<Block> CANOPY_GREEN = REGISTRY.register("canopy_green", () -> new CanopygreenBlock());
	public static final RegistryObject<Block> CANOPY_LIGHT_BLUE = REGISTRY.register("canopy_light_blue", () -> new CanopylightblueBlock());
	public static final RegistryObject<Block> CANOPY_LIGHT_GRAY = REGISTRY.register("canopy_light_gray", () -> new CanopylightgrayBlock());
	public static final RegistryObject<Block> CANOPY_LIME = REGISTRY.register("canopy_lime", () -> new CanopylimeBlock());
	public static final RegistryObject<Block> CANOPY_MAGENTA = REGISTRY.register("canopy_magenta", () -> new CanopymagentaBlock());
	public static final RegistryObject<Block> CANOPY_ORANGE = REGISTRY.register("canopy_orange", () -> new CanopyorangeBlock());
	public static final RegistryObject<Block> CANOPY_PINK = REGISTRY.register("canopy_pink", () -> new CanopypinkBlock());
	public static final RegistryObject<Block> CANOPY_PURPLE = REGISTRY.register("canopy_purple", () -> new CanopypurpleBlock());
	public static final RegistryObject<Block> CANOPY_RED = REGISTRY.register("canopy_red", () -> new CanopyredBlock());
	public static final RegistryObject<Block> CANOPY_YELLOW = REGISTRY.register("canopy_yellow", () -> new CanopyyellowBlock());
	public static final RegistryObject<Block> FLOORSTANDING_SIGN = REGISTRY.register("floorstanding_sign", () -> new FloorstandingSignBlock());
	public static final RegistryObject<Block> BUTCHER_STATUE = REGISTRY.register("butcher_statue", () -> new ButcherstatueBlock());
	public static final RegistryObject<Block> DIORITE_BRICK_SLAB = REGISTRY.register("diorite_brick_slab", () -> new DioriteBrickSlabBlock());
	public static final RegistryObject<Block> DIORITE_BRICK_WALL = REGISTRY.register("diorite_brick_wall", () -> new DioriteBrickwallBlock());
	public static final RegistryObject<Block> DIORITE_BRICKS = REGISTRY.register("diorite_bricks", () -> new DioritebricksBlock());
	public static final RegistryObject<Block> DIORITE_BRICK_STAIRS = REGISTRY.register("diorite_brick_stairs", () -> new DioritebrickstairsBlock());
	public static final RegistryObject<Block> ROPE = REGISTRY.register("rope", () -> new RopeBlock());
	public static final RegistryObject<Block> SAND = REGISTRY.register("sand", () -> new SandBlock());
	public static final RegistryObject<Block> ENDER_DRAGON_CARCASS = REGISTRY.register("ender_dragon_carcass", () -> new EnderdragoncarcassBlock());
	public static final RegistryObject<Block> DRAGON_SCALE_BLOCK = REGISTRY.register("dragon_scale_block", () -> new DragonscaleblockBlock());
	public static final RegistryObject<Block> ENDER_DRAGON_CARCASS_HEADLESS = REGISTRY.register("ender_dragon_carcass_headless", () -> new EnderdragoncarcassheadlessBlock());
	public static final RegistryObject<Block> ENDERDRAGONCUT_1 = REGISTRY.register("enderdragoncut_1", () -> new Enderdragoncut1Block());
	public static final RegistryObject<Block> ENDERDRAGONCUT_2 = REGISTRY.register("enderdragoncut_2", () -> new Enderdragoncut2Block());
	public static final RegistryObject<Block> ENDERDRAGONCUT_3 = REGISTRY.register("enderdragoncut_3", () -> new Enderdragoncut3Block());
	public static final RegistryObject<Block> ENDERDRAGONCUT_4 = REGISTRY.register("enderdragoncut_4", () -> new Enderdragoncut4Block());
	public static final RegistryObject<Block> ENDERDRAGONCUT_5 = REGISTRY.register("enderdragoncut_5", () -> new Enderdragoncut5Block());
	public static final RegistryObject<Block> ENDERDRAGONCUT_6 = REGISTRY.register("enderdragoncut_6", () -> new Enderdragoncut6Block());
	public static final RegistryObject<Block> ENDERDRAGONCUT_7 = REGISTRY.register("enderdragoncut_7", () -> new Enderdragoncut7Block());
	public static final RegistryObject<Block> ENDERDRAGONCUT_8 = REGISTRY.register("enderdragoncut_8", () -> new Enderdragoncut8Block());
	public static final RegistryObject<Block> ENDERDRAGONCUT_9 = REGISTRY.register("enderdragoncut_9", () -> new Enderdragoncut9Block());
	public static final RegistryObject<Block> ENDERDRAGONCUT_10 = REGISTRY.register("enderdragoncut_10", () -> new Enderdragoncut10Block());
	public static final RegistryObject<Block> ENDERDRAGONCUT_11 = REGISTRY.register("enderdragoncut_11", () -> new Enderdragoncut11Block());
	public static final RegistryObject<Block> ENDERDRAGONCUT_12 = REGISTRY.register("enderdragoncut_12", () -> new Enderdragoncut12Block());
	public static final RegistryObject<Block> ENDERDRAGONCUT_13 = REGISTRY.register("enderdragoncut_13", () -> new Enderdragoncut13Block());
	public static final RegistryObject<Block> ENDERDRAGONCUT_14 = REGISTRY.register("enderdragoncut_14", () -> new Enderdragoncut14Block());
	public static final RegistryObject<Block> WOODEN_SPIT_ROTISSERIE = REGISTRY.register("wooden_spit_rotisserie", () -> new WoodenspitrotisserieBlock());
	public static final RegistryObject<Block> POLARBEAR_RUG = REGISTRY.register("polarbear_rug", () -> new BearrugBlock());
	public static final RegistryObject<Block> GOAT_RUG = REGISTRY.register("goat_rug", () -> new GoatrugBlock());
	public static final RegistryObject<Block> PANDA_RUG = REGISTRY.register("panda_rug", () -> new PandarugBlock());
	public static final RegistryObject<Block> CASH_REGISTER_BLOCK = REGISTRY.register("cash_register_block", () -> new CashregisterblockBlock());
	public static final RegistryObject<Block> ACACIA_BUTCHER_DISPLAY = REGISTRY.register("acacia_butcher_display", () -> new AcaciabutcherdisplayBlock());
	public static final RegistryObject<Block> BIRCH_BUTCHER_DISPLAY = REGISTRY.register("birch_butcher_display", () -> new BirchbutcherdisplayBlock());
	public static final RegistryObject<Block> CRIMSON_BUTCHER_DISPLAY = REGISTRY.register("crimson_butcher_display", () -> new CrimsonbutcherdisplayBlock());
	public static final RegistryObject<Block> DARK_OAK_BUTCHER_DISPLAY = REGISTRY.register("dark_oak_butcher_display", () -> new DarkoakbutcherdisplayBlock());
	public static final RegistryObject<Block> JUNGLE_BUTCHER_DISPLAY = REGISTRY.register("jungle_butcher_display", () -> new JunglebutcherdisplayBlock());
	public static final RegistryObject<Block> OAK_BUTCHER_DISPLAY = REGISTRY.register("oak_butcher_display", () -> new OakbutcherdisplayBlock());
	public static final RegistryObject<Block> SPRUCE_BUTCHER_DISPLAY = REGISTRY.register("spruce_butcher_display", () -> new SpruceButcherdisplayBlock());
	public static final RegistryObject<Block> WARPED_BUTCHER_DISPLAY = REGISTRY.register("warped_butcher_display", () -> new WarpedbutcherdisplayBlock());
	public static final RegistryObject<Block> ACACIA_COUNTER = REGISTRY.register("acacia_counter", () -> new AcaciacounterBlock());
	public static final RegistryObject<Block> BIRCH_COUNTER = REGISTRY.register("birch_counter", () -> new BirchcounterBlock());
	public static final RegistryObject<Block> CRIMSON_COUNTER = REGISTRY.register("crimson_counter", () -> new CrimsoncounterBlock());
	public static final RegistryObject<Block> DARK_OAK_COUNTER = REGISTRY.register("dark_oak_counter", () -> new DarkoakcounterBlock());
	public static final RegistryObject<Block> JUNGLE_COUNTER = REGISTRY.register("jungle_counter", () -> new JunglecounterBlock());
	public static final RegistryObject<Block> OAK_COUNTER = REGISTRY.register("oak_counter", () -> new OakcounterBlock());
	public static final RegistryObject<Block> SPRUCE_COUNTER = REGISTRY.register("spruce_counter", () -> new SprucecounterBlock());
	public static final RegistryObject<Block> WARPED_COUNTER = REGISTRY.register("warped_counter", () -> new WarpedcounterBlock());
	public static final RegistryObject<Block> BLOOD_SPLATTER = REGISTRY.register("blood_splatter", () -> new BloodsplatterBlock());
	public static final RegistryObject<Block> BONE_BARREL = REGISTRY.register("bone_barrel", () -> new BonebarrelBlock());
	public static final RegistryObject<Block> COD_BARREL = REGISTRY.register("cod_barrel", () -> new CodbarrelBlock());
	public static final RegistryObject<Block> SALMON_BARREL = REGISTRY.register("salmon_barrel", () -> new SalmonbarrelBlock());
	public static final RegistryObject<Block> PINK_AXOLOTL_CARCASS = REGISTRY.register("pink_axolotl_carcass", () -> new PinkaxolotlcarcassBlock());
	public static final RegistryObject<Block> DRAINED_PINK_AXOLOTL_CARCASS = REGISTRY.register("drained_pink_axolotl_carcass", () -> new DrainedpinkaxolotlcarcassBlock());
	public static final RegistryObject<Block> BLUE_AXOLOTL_CARCASS = REGISTRY.register("blue_axolotl_carcass", () -> new BlueaxolotlcarcassBlock());
	public static final RegistryObject<Block> DRAINED_BLUE_AXOLOTL_CARCASS = REGISTRY.register("drained_blue_axolotl_carcass", () -> new DrainedBlueaxolotlcarcassBlock());
	public static final RegistryObject<Block> BROWN_AXOLOTL_CARCASS = REGISTRY.register("brown_axolotl_carcass", () -> new BrownaxolotlcarcassBlock());
	public static final RegistryObject<Block> DRAINED_BROWN_AXOLOTL_CARCASS = REGISTRY.register("drained_brown_axolotl_carcass", () -> new DrainedBrownaxolotlcarcassBlock());
	public static final RegistryObject<Block> CYAN_AXOLOTL_CARCASS = REGISTRY.register("cyan_axolotl_carcass", () -> new CyanaxolotlcarcassBlock());
	public static final RegistryObject<Block> DRAINED_CYAN_AXOLOTL_CARCASS = REGISTRY.register("drained_cyan_axolotl_carcass", () -> new DrainedCyanaxolotlcarcassBlock());
	public static final RegistryObject<Block> GOLD_AXOLOTL_CARCASS = REGISTRY.register("gold_axolotl_carcass", () -> new GoldaxolotlcarcassBlock());
	public static final RegistryObject<Block> DRAINED_GOLD_AXOLOTL_CARCASS = REGISTRY.register("drained_gold_axolotl_carcass", () -> new DrainedGoldaxolotlcarcassBlock());
	public static final RegistryObject<Block> PINK_AXOLOTL_HEAD = REGISTRY.register("pink_axolotl_head", () -> new PinkaxolotlheadBlock());
	public static final RegistryObject<Block> BLUE_AXOLOTL_HEAD = REGISTRY.register("blue_axolotl_head", () -> new BlueaxolotlheadBlock());
	public static final RegistryObject<Block> CYAN_AXOLOTL_HEAD = REGISTRY.register("cyan_axolotl_head", () -> new CyanaxolotlheadBlock());
	public static final RegistryObject<Block> GOLD_AXOLOTL_HEAD = REGISTRY.register("gold_axolotl_head", () -> new GOLDaxolotlheadBlock());
	public static final RegistryObject<Block> BROWN_AXOLOTL_HEAD = REGISTRY.register("brown_axolotl_head", () -> new BrownaxolotlheadBlock());
	public static final RegistryObject<Block> BLUE_AXOLOTL_HEAD_MOUNT = REGISTRY.register("blue_axolotl_head_mount", () -> new BlueaxolotlheadmountBlock());
	public static final RegistryObject<Block> BROWN_AXOLOTL_HEAD_MOUNT = REGISTRY.register("brown_axolotl_head_mount", () -> new BrownaxolotlheadmountBlock());
	public static final RegistryObject<Block> CYAN_AXOLOTL_HEAD_MOUNT = REGISTRY.register("cyan_axolotl_head_mount", () -> new CyanaxolotlheadmountBlock());
	public static final RegistryObject<Block> GOLD_AXOLOTL_HEAD_MOUNT = REGISTRY.register("gold_axolotl_head_mount", () -> new GoldaxolotlheadmountBlock());
	public static final RegistryObject<Block> PINK_AXOLOTL_HEAD_MOUNT = REGISTRY.register("pink_axolotl_head_mount", () -> new PinkaxolotlheadmountBlock());
	public static final RegistryObject<Block> BAT_HEAD_MOUNT = REGISTRY.register("bat_head_mount", () -> new BatheadmountBlock());
	public static final RegistryObject<Block> DONKEY_HEAD_MOUNT = REGISTRY.register("donkey_head_mount", () -> new DonkeyheadmountBlock());
	public static final RegistryObject<Block> MULE_HEAD_MOUNT = REGISTRY.register("mule_head_mount", () -> new MuleheadmountBlock());
	public static final RegistryObject<Block> EVOKER_HEAD_MOUNT = REGISTRY.register("evoker_head_mount", () -> new EvokerHeadMountBlock());
	public static final RegistryObject<Block> VINDICATOR_HEAD_MOUNT = REGISTRY.register("vindicator_head_mount", () -> new VindicatorHeadMountBlock());
	public static final RegistryObject<Block> RED_MOOSHROOM_HEAD_MOUNT = REGISTRY.register("red_mooshroom_head_mount", () -> new RedMooshroomheadmountBlock());
	public static final RegistryObject<Block> BROWN_MOOSHROOM_HEAD_MOUNT = REGISTRY.register("brown_mooshroom_head_mount", () -> new BrownMooshroomheadmountBlock());
	public static final RegistryObject<Block> PIGLIN_HEAD_MOUNT = REGISTRY.register("piglin_head_mount", () -> new PiglinHeadMountBlock());
	public static final RegistryObject<Block> PIGLIN_BRUTE_HEAD_MOUNT = REGISTRY.register("piglin_brute_head_mount", () -> new PiglinbruteHeadMountBlock());
	public static final RegistryObject<Block> ZOMBIFIED_PIGLIN_HEAD_MOUNT = REGISTRY.register("zombified_piglin_head_mount", () -> new ZombifiedPiglinHeadMountBlock());
	public static final RegistryObject<Block> RABBIT_HEAD_MOUNT = REGISTRY.register("rabbit_head_mount", () -> new RabbitHeadMountBlock());
	public static final RegistryObject<Block> STRAY_HEAD_MOUNT = REGISTRY.register("stray_head_mount", () -> new StrayheadmountBlock());
	public static final RegistryObject<Block> TURTLE_HEAD_MOUNT = REGISTRY.register("turtle_head_mount", () -> new TurtleheadmountBlock());
	public static final RegistryObject<Block> WITHER_SKELETON_HEAD_MOUNT = REGISTRY.register("wither_skeleton_head_mount", () -> new WitherskeletonheadmountBlock());
	public static final RegistryObject<Block> HANGING_ENDERMAN_CARCASS = REGISTRY.register("hanging_enderman_carcass", () -> new HangingendermancarcassBlock());
	public static final RegistryObject<Block> ENDERMAN_CARCASS = REGISTRY.register("enderman_carcass", () -> new EndermancarcassBlock());
	public static final RegistryObject<Block> DRAINED_ENDERMAN_CARCASS = REGISTRY.register("drained_enderman_carcass", () -> new DrainedendermancarcassBlock());
	public static final RegistryObject<Block> ENDERMAN_HEAD = REGISTRY.register("enderman_head", () -> new EndermanheadBlock());
	public static final RegistryObject<Block> HANGING_DRAINED_ENDERMAN_CARCASS = REGISTRY.register("hanging_drained_enderman_carcass", () -> new HangingdrainedendermancarcassBlock());
	public static final RegistryObject<Block> ENDERMITE_CARCASS = REGISTRY.register("endermite_carcass", () -> new EndermiteBlock());
	public static final RegistryObject<Block> ENDERMITE_HEAD_MOUNT = REGISTRY.register("endermite_head_mount", () -> new EndermiteheadmountBlock());
	public static final RegistryObject<Block> SILVERFISH_HEAD_MOUNT = REGISTRY.register("silverfish_head_mount", () -> new SilverfishheadmountBlock());
	public static final RegistryObject<Block> ENDERMITE_HEAD = REGISTRY.register("endermite_head", () -> new EndermiteheadBlock());
	public static final RegistryObject<Block> SILVERFISH_HEAD = REGISTRY.register("silverfish_head", () -> new SilverfishheadBlock());
	public static final RegistryObject<Block> SMALL_EMPTY_HEAD_MOUNT = REGISTRY.register("small_empty_head_mount", () -> new SmallemptyheadmountBlock());
	public static final RegistryObject<Block> PHANTOM_CARCASS = REGISTRY.register("phantom_carcass", () -> new PhantomcarcassBlock());
	public static final RegistryObject<Block> DRAINED_PHANTOM_CARCASS = REGISTRY.register("drained_phantom_carcass", () -> new DrainedphantomcarcassBlock());
	public static final RegistryObject<Block> PHANTOM_HEAD = REGISTRY.register("phantom_head", () -> new PhantomheadBlock());
	public static final RegistryObject<Block> PHANTOM_HEAD_MOUNT = REGISTRY.register("phantom_head_mount", () -> new PhantomheadmountBlock());
	public static final RegistryObject<Block> ALL_BLACK_CAT_CARCASS = REGISTRY.register("all_black_cat_carcass", () -> new AllblackcatcarcassBlock());
	public static final RegistryObject<Block> DRAINED_ALL_BLACK_CAT_CARCASS = REGISTRY.register("drained_all_black_cat_carcass", () -> new DrainedallblackcatcarcassBlock());
	public static final RegistryObject<Block> BLACK_CAT_CARCASS = REGISTRY.register("black_cat_carcass", () -> new BlackcatcarcassBlock());
	public static final RegistryObject<Block> DRAINED_BLACK_CAT_CARCASS = REGISTRY.register("drained_black_cat_carcass", () -> new DrainedblackcatcarcassBlock());
	public static final RegistryObject<Block> BRITISH_SHORTHAIR_CAT_CARCASS = REGISTRY.register("british_shorthair_cat_carcass", () -> new BritishshorthaircatcarcassBlock());
	public static final RegistryObject<Block> DRAINED_BRITISH_SHORTHAIR_CAT_CARCASS = REGISTRY.register("drained_british_shorthair_cat_carcass", () -> new DrainedBritishshorthaircatcarcassBlock());
	public static final RegistryObject<Block> CALICO_CAT_CARCASS = REGISTRY.register("calico_cat_carcass", () -> new CalicocatcarcassBlock());
	public static final RegistryObject<Block> DRAINED_CALICO_CAT_CARCASS = REGISTRY.register("drained_calico_cat_carcass", () -> new DrainedCalicocatcarcassBlock());
	public static final RegistryObject<Block> JELLIE_CAT_CARCASS = REGISTRY.register("jellie_cat_carcass", () -> new JelliecatcarcassBlock());
	public static final RegistryObject<Block> DRAINED_JELLIE_CAT_CARCASS = REGISTRY.register("drained_jellie_cat_carcass", () -> new DrainedJelliecatcarcassBlock());
	public static final RegistryObject<Block> PERSIAN_CAT_CARCASS = REGISTRY.register("persian_cat_carcass", () -> new PersiancatcarcassBlock());
	public static final RegistryObject<Block> DRAINED_PERSIAN_CAT_CARCASS = REGISTRY.register("drained_persian_cat_carcass", () -> new DrainedPersiancatcarcassBlock());
	public static final RegistryObject<Block> RAGDOLL_CAT_CARCASS = REGISTRY.register("ragdoll_cat_carcass", () -> new RagdollcatcarcassBlock());
	public static final RegistryObject<Block> DRAINED_RAGDOLL_CAT_CARCASS = REGISTRY.register("drained_ragdoll_cat_carcass", () -> new DrainedRagdollcatcarcassBlock());
	public static final RegistryObject<Block> RED_CAT_CARCASS = REGISTRY.register("red_cat_carcass", () -> new RedcatcarcassBlock());
	public static final RegistryObject<Block> DRAINED_RED_CAT_CARCASS = REGISTRY.register("drained_red_cat_carcass", () -> new DrainedRedcatcarcassBlock());
	public static final RegistryObject<Block> SIAMESE_CAT_CARCASS = REGISTRY.register("siamese_cat_carcass", () -> new SiamesecatcarcassBlock());
	public static final RegistryObject<Block> DRAINED_SIAMESE_CAT_CARCASS = REGISTRY.register("drained_siamese_cat_carcass", () -> new DrainedSiamesecatcarcassBlock());
	public static final RegistryObject<Block> TABBY_CAT_CARCASS = REGISTRY.register("tabby_cat_carcass", () -> new TabbycatcarcassBlock());
	public static final RegistryObject<Block> DRAINED_TABBY_CAT_CARCASS = REGISTRY.register("drained_tabby_cat_carcass", () -> new DrainedTabbycatcarcassBlock());
	public static final RegistryObject<Block> WHITE_CAT_CARCASS = REGISTRY.register("white_cat_carcass", () -> new WhitecatcarcassBlock());
	public static final RegistryObject<Block> DRAINED_WHITE_CAT_CARCASS = REGISTRY.register("drained_white_cat_carcass", () -> new DrainedWhitecatcarcassBlock());
	public static final RegistryObject<Block> BLACK_CAT_HEAD = REGISTRY.register("black_cat_head", () -> new BlackcatheadBlock());
	public static final RegistryObject<Block> ALL_BLACK_CAT_HEAD = REGISTRY.register("all_black_cat_head", () -> new AllblackcatheadBlock());
	public static final RegistryObject<Block> TABBY_CAT_HEAD = REGISTRY.register("tabby_cat_head", () -> new TabbycatheadBlock());
	public static final RegistryObject<Block> RED_CAT_HEAD = REGISTRY.register("red_cat_head", () -> new RedcatheadBlock());
	public static final RegistryObject<Block> SIAMESE_CAT_HEAD = REGISTRY.register("siamese_cat_head", () -> new SiamesecatheadBlock());
	public static final RegistryObject<Block> SHORTHAIR_CAT_HEAD = REGISTRY.register("shorthair_cat_head", () -> new ShorthaircatheadBlock());
	public static final RegistryObject<Block> RAGDOLL_CAT_HEAD = REGISTRY.register("ragdoll_cat_head", () -> new RagdollcatheadBlock());
	public static final RegistryObject<Block> JELLIE_CAT_HEAD = REGISTRY.register("jellie_cat_head", () -> new JelliecatheadBlock());
	public static final RegistryObject<Block> WHITE_CAT_HEAD = REGISTRY.register("white_cat_head", () -> new WhitecatheadBlock());
	public static final RegistryObject<Block> PERSIAN_CAT_HEAD = REGISTRY.register("persian_cat_head", () -> new PersiancatheadBlock());
	public static final RegistryObject<Block> CALICO_CAT_HEAD = REGISTRY.register("calico_cat_head", () -> new CalicocatheadBlock());
	public static final RegistryObject<Block> CAT_CARCASS = REGISTRY.register("cat_carcass", () -> new CatcarcassBlock());
	public static final RegistryObject<Block> ELDER_GUARDIAN_CARCASS = REGISTRY.register("elder_guardian_carcass", () -> new ElderguardiancarcassBlock());
	public static final RegistryObject<Block> WITCH_CORPSE = REGISTRY.register("witch_corpse", () -> new WitchcorpseBlock());
	public static final RegistryObject<Block> DRAINED_WITCH_CORPSE = REGISTRY.register("drained_witch_corpse", () -> new DrainedwitchcorpseBlock());
	public static final RegistryObject<Block> WITCH_HEAD = REGISTRY.register("witch_head", () -> new WitchheadBlock());
	public static final RegistryObject<Block> IRON_GOLEM = REGISTRY.register("iron_golem", () -> new IrongolemBlock());
	public static final RegistryObject<Block> IRON_GOLEM_HEAD = REGISTRY.register("iron_golem_head", () -> new IrongolemheadBlock());
	public static final RegistryObject<Block> IRON_GOLEM_ARMS = REGISTRY.register("iron_golem_arms", () -> new IrongolemarmsBlock());
	public static final RegistryObject<Block> IRON_GOLEM_LEGS = REGISTRY.register("iron_golem_legs", () -> new IrongolemlegsBlock());
	public static final RegistryObject<Block> IRON_GOLEM_BODY = REGISTRY.register("iron_golem_body", () -> new IrongolembodyBlock());
	public static final RegistryObject<Block> REPAIRED_IRON_GOLEM_HEAD = REGISTRY.register("repaired_iron_golem_head", () -> new RepairedIrongolemheadBlock());
	public static final RegistryObject<Block> REPAIRED_IRON_GOLEM_ARMS = REGISTRY.register("repaired_iron_golem_arms", () -> new RepairedIrongolemarmsBlock());
	public static final RegistryObject<Block> REPAIRED_IRON_GOLEM_LEGS = REGISTRY.register("repaired_iron_golem_legs", () -> new RepairedIrongolemlegsBlock());
	public static final RegistryObject<Block> REPAIRED_IRON_GOLEM_BODY = REGISTRY.register("repaired_iron_golem_body", () -> new RepairedIrongolembodyBlock());
	public static final RegistryObject<Block> ALL_BLACK_CAT_HEAD_MOUNT = REGISTRY.register("all_black_cat_head_mount", () -> new AllblackcatheadmountBlock());
	public static final RegistryObject<Block> BLACK_CAT_HEAD_MOUNT = REGISTRY.register("black_cat_head_mount", () -> new BlackcatheadmountBlock());
	public static final RegistryObject<Block> TABBY_CAT_HEAD_MOUNT = REGISTRY.register("tabby_cat_head_mount", () -> new TabbycatheadmountBlock());
	public static final RegistryObject<Block> RED_CAT_HEAD_MOUNT = REGISTRY.register("red_cat_head_mount", () -> new RedcatheadmountBlock());
	public static final RegistryObject<Block> SIAMESE_CAT_HEAD_MOUNT = REGISTRY.register("siamese_cat_head_mount", () -> new SiamesecatheadmountBlock());
	public static final RegistryObject<Block> SHORTHAIR_CAT_HEAD_MOUNT = REGISTRY.register("shorthair_cat_head_mount", () -> new ShorthaircatheadmountBlock());
	public static final RegistryObject<Block> RAGDOLL_CAT_HEAD_MOUNT = REGISTRY.register("ragdoll_cat_head_mount", () -> new RagdollcatheadmountBlock());
	public static final RegistryObject<Block> JELLIE_CAT_HEAD_MOUNT = REGISTRY.register("jellie_cat_head_mount", () -> new JelliecatheadmountBlock());
	public static final RegistryObject<Block> WHITE_CAT_HEAD_MOUNT = REGISTRY.register("white_cat_head_mount", () -> new WhitecatheadmountBlock());
	public static final RegistryObject<Block> PERSIAN_CAT_HEAD_MOUNT = REGISTRY.register("persian_cat_head_mount", () -> new PersiancatheadmountBlock());
	public static final RegistryObject<Block> CALICO_CAT_HEAD_MOUNT = REGISTRY.register("calico_cat_head_mount", () -> new CalicocatheadmountBlock());
	public static final RegistryObject<Block> IRON_GOLEM_HEAD_MOUNT = REGISTRY.register("iron_golem_head_mount", () -> new IrongolemheadmountBlock());
	public static final RegistryObject<Block> REPAIRED_IRON_GOLEM_HEAD_MOUNT = REGISTRY.register("repaired_iron_golem_head_mount", () -> new RepairedirongolemheadmountBlock());
	public static final RegistryObject<Block> WITCH_HEAD_MOUNT = REGISTRY.register("witch_head_mount", () -> new WitchheadmountBlock());
	public static final RegistryObject<Block> WITHER_CARCASS = REGISTRY.register("wither_carcass", () -> new WithercarcassBlock());
	public static final RegistryObject<Block> ZOGLIN_CARCASS = REGISTRY.register("zoglin_carcass", () -> new ZoglincarcassBlock());
	public static final RegistryObject<Block> ZOGLIN_HEAD = REGISTRY.register("zoglin_head", () -> new ZoglinheadBlock());
	public static final RegistryObject<Block> DRAINED_ZOGLIN_CARCASS = REGISTRY.register("drained_zoglin_carcass", () -> new DrainedzoglincarcassBlock());
	public static final RegistryObject<Block> ZOGLIN_HEAD_MOUNT = REGISTRY.register("zoglin_head_mount", () -> new ZoglinheadmountBlock());
	public static final RegistryObject<Block> WOLF_CARCASS = REGISTRY.register("wolf_carcass", () -> new WolfcarcassBlock());
	public static final RegistryObject<Block> WOLF_HEAD = REGISTRY.register("wolf_head", () -> new WolfheadBlock());
	public static final RegistryObject<Block> DRAINED_WOLF_CARCASS = REGISTRY.register("drained_wolf_carcass", () -> new DrainedWolfcarcassBlock());
	public static final RegistryObject<Block> WOLF_HEAD_MOUNT = REGISTRY.register("wolf_head_mount", () -> new WolfheadmountBlock());
	public static final RegistryObject<Block> SKELETON_HORSE_CARCASS = REGISTRY.register("skeleton_horse_carcass", () -> new SkeletonhorsecarcassBlock());
	public static final RegistryObject<Block> SKELETON_HORSE_HEAD = REGISTRY.register("skeleton_horse_head", () -> new SkeletonhorseheadBlock());
	public static final RegistryObject<Block> SKELETON_HORSE_HEAD_MOUNT = REGISTRY.register("skeleton_horse_head_mount", () -> new SkeletonhorseheadmountBlock());
	public static final RegistryObject<Block> WARDEN_CARCASS = REGISTRY.register("warden_carcass", () -> new WardencarcassBlock());
	public static final RegistryObject<Block> WARDEN_HEAD = REGISTRY.register("warden_head", () -> new WardenheadBlock());
	public static final RegistryObject<Block> ZOMBIE_HORSE_CARCASS = REGISTRY.register("zombie_horse_carcass", () -> new ZombiehorsecarcassBlock());
	public static final RegistryObject<Block> ZOMBIE_HORSE_HEAD = REGISTRY.register("zombie_horse_head", () -> new ZombiehorseheadBlock());
	public static final RegistryObject<Block> DRAINED_ZOMBIE_HORSE_CARCASS = REGISTRY.register("drained_zombie_horse_carcass", () -> new DrainedZombiehorsecarcassBlock());
	public static final RegistryObject<Block> ZOMBIE_HORSE_HEAD_MOUNT = REGISTRY.register("zombie_horse_head_mount", () -> new ZombiehorseheadmountBlock());
	public static final RegistryObject<Block> SPIKE_TRAP = REGISTRY.register("spike_trap", () -> new SpiketrapBlock());
	public static final RegistryObject<Block> BRAIN = REGISTRY.register("brain", () -> new BrainBlock());
	public static final RegistryObject<Block> RAW_SAUSAGES = REGISTRY.register("raw_sausages", () -> new RawsausagesBlock());
	public static final RegistryObject<Block> COOKED_SAUSAGES = REGISTRY.register("cooked_sausages", () -> new CookedsausagesBlock());
	public static final RegistryObject<Block> RAW_BLOOD_SAUSAGES = REGISTRY.register("raw_blood_sausages", () -> new RawbloodsausagesBlock());
	public static final RegistryObject<Block> COOKED_BLOOD_SAUSAGES = REGISTRY.register("cooked_blood_sausages", () -> new CookedbloodsausagesBlock());
	public static final RegistryObject<Block> BEE_CARCASS = REGISTRY.register("bee_carcass", () -> new BeecarcassBlock());
	public static final RegistryObject<Block> BEE_HEAD = REGISTRY.register("bee_head", () -> new BeeheadBlock());
	public static final RegistryObject<Block> SNIFFER_CARCASS_BLOCK = REGISTRY.register("sniffer_carcass_block", () -> new SniffercarcassblockBlock());
	public static final RegistryObject<Block> DRAINED_SNIFFER_CARCASS_BLOCK = REGISTRY.register("drained_sniffer_carcass_block", () -> new DrainedsniffercarcassblockBlock());
	public static final RegistryObject<Block> SNIFFER_HEAD = REGISTRY.register("sniffer_head", () -> new SnifferheadBlock());
	public static final RegistryObject<Block> ENDER_DRAGON_HEAD_MOUNT = REGISTRY.register("ender_dragon_head_mount", () -> new EnderDragonHeadMountBlock());
	public static final RegistryObject<Block> EMPTY_DRAGON_TRIMMED_HEAD_MOUNT = REGISTRY.register("empty_dragon_trimmed_head_mount", () -> new EmptydragontrimmedheadmountBlock());
	public static final RegistryObject<Block> TRIMMED_ENDER_DRAGON_HEAD_MOUNT = REGISTRY.register("trimmed_ender_dragon_head_mount", () -> new TrimmedEnderDragonHeadMountBlock());
	public static final RegistryObject<Block> REPAIRED_IRONGOLEM = REGISTRY.register("repaired_irongolem", () -> new RepairedIrongolemBlock());
	public static final RegistryObject<Block> REGULAR_BLACK_HORSE_CARCASS = REGISTRY.register("regular_black_horse_carcass", () -> new RegularblackhorsecarcassBlock());
	public static final RegistryObject<Block> BLACK_HORSE_HEAD = REGISTRY.register("black_horse_head", () -> new BlackhorseheadBlock());
	public static final RegistryObject<Block> DRAINED_REGULAR_BLACK_HORSE_CARCASS = REGISTRY.register("drained_regular_black_horse_carcass", () -> new DrainedRegularblackhorsecarcassBlock());
	public static final RegistryObject<Block> BROWN_HORSE_HEAD = REGISTRY.register("brown_horse_head", () -> new BrownhorseheadBlock());
	public static final RegistryObject<Block> REGULAR_BROWN_HORSE_CARCASS = REGISTRY.register("regular_brown_horse_carcass", () -> new RegularBrownhorsecarcassBlock());
	public static final RegistryObject<Block> DRAINED_REGULAR_BROWN_HORSE_CARCASS = REGISTRY.register("drained_regular_brown_horse_carcass", () -> new DrainedRegularBrownhorsecarcassBlock());
	public static final RegistryObject<Block> CHESTNUT_HORSE_HEAD = REGISTRY.register("chestnut_horse_head", () -> new ChestnuthorseheadBlock());
	public static final RegistryObject<Block> REGULAR_CHESTNUT_HORSE_CARCASS = REGISTRY.register("regular_chestnut_horse_carcass", () -> new RegularChestnuthorsecarcassBlock());
	public static final RegistryObject<Block> DRAINED_REGULAR_CHESTNUT_HORSE_CARCASS = REGISTRY.register("drained_regular_chestnut_horse_carcass", () -> new DrainedRegularChestnuthorsecarcassBlock());
	public static final RegistryObject<Block> CREAMY_HORSE_HEAD = REGISTRY.register("creamy_horse_head", () -> new CreamyhorseheadBlock());
	public static final RegistryObject<Block> REGULAR_CREAMY_HORSE_CARCASS = REGISTRY.register("regular_creamy_horse_carcass", () -> new RegularCreamyhorsecarcassBlock());
	public static final RegistryObject<Block> DRAINED_REGULAR_CREAMY_HORSE_CARCASS = REGISTRY.register("drained_regular_creamy_horse_carcass", () -> new DrainedRegularCreamyhorsecarcassBlock());
	public static final RegistryObject<Block> DARK_BROWN_HORSE_HEAD = REGISTRY.register("dark_brown_horse_head", () -> new DarkbrownhorseheadBlock());
	public static final RegistryObject<Block> REGULAR_DARK_BROWN_HORSE_CARCASS = REGISTRY.register("regular_dark_brown_horse_carcass", () -> new RegularDarkbrownhorsecarcassBlock());
	public static final RegistryObject<Block> DRAINED_REGULAR_DARK_BROWN_HORSE_CARCASS = REGISTRY.register("drained_regular_dark_brown_horse_carcass", () -> new DrainedRegularDarkbrownhorsecarcassBlock());
	public static final RegistryObject<Block> GRAY_HORSE_HEAD = REGISTRY.register("gray_horse_head", () -> new GrayhorseheadBlock());
	public static final RegistryObject<Block> REGULAR_GRAY_HORSE_CARCASS = REGISTRY.register("regular_gray_horse_carcass", () -> new RegularGrayhorsecarcassBlock());
	public static final RegistryObject<Block> WHITE_HORSE_HEAD = REGISTRY.register("white_horse_head", () -> new WhitehorseheadBlock());
	public static final RegistryObject<Block> REGULAR_WHITE_HORSE_CARCASS = REGISTRY.register("regular_white_horse_carcass", () -> new RegularWhitehorsecarcassBlock());
	public static final RegistryObject<Block> DRAINED_GRAY_HORSE_CARCASS = REGISTRY.register("drained_gray_horse_carcass", () -> new DrainedGrayhorsecarcassBlock());
	public static final RegistryObject<Block> DRAINED_WHITE_HORSE_CARCASS = REGISTRY.register("drained_white_horse_carcass", () -> new DrainedWhitehorsecarcassBlock());
	public static final RegistryObject<Block> PLASTIC_SHEET = REGISTRY.register("plastic_sheet", () -> new PlasticsheetBlock());
	public static final RegistryObject<Block> PLASTIC_SHEET_CORNER = REGISTRY.register("plastic_sheet_corner", () -> new PlasticsheetcornerBlock());
	public static final RegistryObject<Block> CLING_FILM = REGISTRY.register("cling_film", () -> new ClingfilmBlock());
	public static final RegistryObject<Block> PHOTOS = REGISTRY.register("photos", () -> new PhotosBlock());
	public static final RegistryObject<Block> INFECTED_BLOOD = REGISTRY.register("infected_blood", () -> new InfectedBloodBlock());
	public static final RegistryObject<Block> SULFUR_ORE = REGISTRY.register("sulfur_ore", () -> new SulfuroreBlock());
	public static final RegistryObject<Block> DEEPSLATE_SULFUR_ORE = REGISTRY.register("deepslate_sulfur_ore", () -> new DeepslatesulfuroreBlock());
	public static final RegistryObject<Block> BLACK_HORSE_HEAD_MOUNT = REGISTRY.register("black_horse_head_mount", () -> new BlackhorseheadmountBlock());
	public static final RegistryObject<Block> BROWN_HORSE_HEAD_MOUNT = REGISTRY.register("brown_horse_head_mount", () -> new BrownhorseheadmountBlock());
	public static final RegistryObject<Block> CHESTNUT_HORSE_HEAD_MOUNT = REGISTRY.register("chestnut_horse_head_mount", () -> new ChestnuthorseheadmountBlock());
	public static final RegistryObject<Block> CREAMY_HORSE_HEAD_MOUNT = REGISTRY.register("creamy_horse_head_mount", () -> new CreamyhorseheadmountBlock());
	public static final RegistryObject<Block> DARK_BROWN_HORSE_HEAD_MOUNT = REGISTRY.register("dark_brown_horse_head_mount", () -> new DarkbrownhorseheadmountBlock());
	public static final RegistryObject<Block> GRAY_HORSE_HEAD_MOUNT = REGISTRY.register("gray_horse_head_mount", () -> new GrayhorseheadmountBlock());
	public static final RegistryObject<Block> WHITE_HORSE_HEAD_MOUNT = REGISTRY.register("white_horse_head_mount", () -> new WhitehorseheadmountBlock());
	public static final RegistryObject<Block> PESTLE_AND_MORTAR = REGISTRY.register("pestle_and_mortar", () -> new PestleandmortarBlock());
	public static final RegistryObject<Block> EMPTY_WARDEN_TRIMMED_HEAD_MOUNT = REGISTRY.register("empty_warden_trimmed_head_mount", () -> new EmptywardentrimmedheadmountBlock());
	public static final RegistryObject<Block> WARDEN_HEAD_MOUNT = REGISTRY.register("warden_head_mount", () -> new WardenHeadMountBlock());
	public static final RegistryObject<Block> TRIMMED_WARDEN_HEAD_MOUNT = REGISTRY.register("trimmed_warden_head_mount", () -> new TrimmedwardenHeadMountBlock());
	public static final RegistryObject<Block> AXOLOTL_SKELETON = REGISTRY.register("axolotl_skeleton", () -> new AxolotlskeletonBlock());
	public static final RegistryObject<Block> BAT_SKELETON = REGISTRY.register("bat_skeleton", () -> new BatskeletonBlock());
	public static final RegistryObject<Block> MOOSHROOM_SKELETON = REGISTRY.register("mooshroom_skeleton", () -> new MooshroomskeletonBlock());
	public static final RegistryObject<Block> CAMEL_SKELETON = REGISTRY.register("camel_skeleton", () -> new CamelskeletonBlock());
	public static final RegistryObject<Block> CAT_SKELETON = REGISTRY.register("cat_skeleton", () -> new CatskeletonBlock());
	public static final RegistryObject<Block> CHICKEN_SKELETON = REGISTRY.register("chicken_skeleton", () -> new ChickenskeletonBlock());
	public static final RegistryObject<Block> FISH_SKELETON = REGISTRY.register("fish_skeleton", () -> new FishskeletonBlock());
	public static final RegistryObject<Block> COW_SKELETON = REGISTRY.register("cow_skeleton", () -> new CowskeletonBlock());
	public static final RegistryObject<Block> CREEPER_SKELETON = REGISTRY.register("creeper_skeleton", () -> new CreeperskeletonBlock());
	public static final RegistryObject<Block> DOLPHIN_SKELETON = REGISTRY.register("dolphin_skeleton", () -> new DolphinskeletonBlock());
	public static final RegistryObject<Block> DONKEY_SKELETON = REGISTRY.register("donkey_skeleton", () -> new DonkeyskeletonBlock());
	public static final RegistryObject<Block> SKELETON = REGISTRY.register("skeleton", () -> new SkeletonBlock());
	public static final RegistryObject<Block> FOX_SKELETON = REGISTRY.register("fox_skeleton", () -> new FoxskeletonBlock());
	public static final RegistryObject<Block> GOAT_SKELETON = REGISTRY.register("goat_skeleton", () -> new GoatskeletonBlock());
	public static final RegistryObject<Block> HOGLIN_SKELETON = REGISTRY.register("hoglin_skeleton", () -> new HoglinskeletonBlock());
	public static final RegistryObject<Block> LLAMA_SKELETON = REGISTRY.register("llama_skeleton", () -> new LlamaskeletonBlock());
	public static final RegistryObject<Block> MULE_SKELETON = REGISTRY.register("mule_skeleton", () -> new MuleskeletonBlock());
	public static final RegistryObject<Block> OCELOT_SKELETON = REGISTRY.register("ocelot_skeleton", () -> new OcelotskeletonBlock());
	public static final RegistryObject<Block> PANDA_SKELETON = REGISTRY.register("panda_skeleton", () -> new PandaskeletonBlock());
	public static final RegistryObject<Block> PHANTOM_SKELETON = REGISTRY.register("phantom_skeleton", () -> new PhantomskeletonBlock());
	public static final RegistryObject<Block> PIG_SKELETON = REGISTRY.register("pig_skeleton", () -> new PigskeletonBlock());
	public static final RegistryObject<Block> PIGLIN_SKELETON = REGISTRY.register("piglin_skeleton", () -> new PiglinskeletonBlock());
	public static final RegistryObject<Block> POLARBEAR_SKELETON = REGISTRY.register("polarbear_skeleton", () -> new PolarbearskeletonBlock());
	public static final RegistryObject<Block> SHEEP_SKELETON = REGISTRY.register("sheep_skeleton", () -> new SheepskeletonBlock());
	public static final RegistryObject<Block> WOLF_SKELETON = REGISTRY.register("wolf_skeleton", () -> new WolfskeletonBlock());
	public static final RegistryObject<Block> PLAYERCORPSE = REGISTRY.register("playercorpse", () -> new PlayercorpseBlock());
	public static final RegistryObject<Block> DRAINEDPLAYERCORPSE = REGISTRY.register("drainedplayercorpse", () -> new DrainedplayercorpseBlock());
	public static final RegistryObject<Block> JAR = REGISTRY.register("jar", () -> new JarBlock());
	public static final RegistryObject<Block> RAVAGER_HEAD = REGISTRY.register("ravager_head", () -> new RavagerheadBlock());
	public static final RegistryObject<Block> RAVAGER = REGISTRY.register("ravager", () -> new RavagerBlock());
	public static final RegistryObject<Block> RAVAGER_HEAD_MOUNT = REGISTRY.register("ravager_head_mount", () -> new RavagerHeadMountBlock());

	// Start of user code block custom blocks
	// End of user code block custom blocks
	@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
	public static class BlocksClientSideHandler {
		@SubscribeEvent
		public static void blockColorLoad(RegisterColorHandlersEvent.Block event) {
			BasinBlock.blockColorLoad(event);
		}
	}
}