/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.butchery.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.client.event.RegisterColorHandlersEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.api.distmarker.Dist;

import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.Block;

import net.mcreator.butchery.block.ZombifiedPiglinHeadMountBlock;
import net.mcreator.butchery.block.ZombievillagerheadmountBlock;
import net.mcreator.butchery.block.ZombievillagerheadBlock;
import net.mcreator.butchery.block.ZombievillagercorpseBlock;
import net.mcreator.butchery.block.ZombiepiglinheadBlock;
import net.mcreator.butchery.block.ZombiepiglincorpseBlock;
import net.mcreator.butchery.block.ZombiehorseheadmountBlock;
import net.mcreator.butchery.block.ZombiehorseheadBlock;
import net.mcreator.butchery.block.ZombiehorsecarcassBlock;
import net.mcreator.butchery.block.ZombieheadmountBlock;
import net.mcreator.butchery.block.ZombiecorpseBlock;
import net.mcreator.butchery.block.ZoglinheadmountBlock;
import net.mcreator.butchery.block.ZoglinheadBlock;
import net.mcreator.butchery.block.ZoglincarcassBlock;
import net.mcreator.butchery.block.WoodenspitrotisserieBlock;
import net.mcreator.butchery.block.WolfskeletonBlock;
import net.mcreator.butchery.block.WolfheadmountBlock;
import net.mcreator.butchery.block.WolfheadBlock;
import net.mcreator.butchery.block.WolfcarcassBlock;
import net.mcreator.butchery.block.WitherskeletonheadmountBlock;
import net.mcreator.butchery.block.WitherskeletoncorpseBlock;
import net.mcreator.butchery.block.WithercarcassBlock;
import net.mcreator.butchery.block.WitchheadmountBlock;
import net.mcreator.butchery.block.WitchheadBlock;
import net.mcreator.butchery.block.WitchcorpseBlock;
import net.mcreator.butchery.block.WhitellamaheadmountBlock;
import net.mcreator.butchery.block.WhitellamaheadBlock;
import net.mcreator.butchery.block.WhitehorseheadmountBlock;
import net.mcreator.butchery.block.WhitehorseheadBlock;
import net.mcreator.butchery.block.WhitecatheadmountBlock;
import net.mcreator.butchery.block.WhitecatheadBlock;
import net.mcreator.butchery.block.WhitecatcarcassBlock;
import net.mcreator.butchery.block.WhiteLlamaCarcassBlock;
import net.mcreator.butchery.block.WarpedcounterBlock;
import net.mcreator.butchery.block.WarpedbutcherstableBlock;
import net.mcreator.butchery.block.WarpedbutcherdisplayBlock;
import net.mcreator.butchery.block.WardenheadBlock;
import net.mcreator.butchery.block.WardencarcassBlock;
import net.mcreator.butchery.block.WardenHeadMountBlock;
import net.mcreator.butchery.block.VindicatorheadBlock;
import net.mcreator.butchery.block.VindicatorcorpseBlock;
import net.mcreator.butchery.block.VindicatorHeadMountBlock;
import net.mcreator.butchery.block.VillagerheadBlock;
import net.mcreator.butchery.block.VillagercorpseBlock;
import net.mcreator.butchery.block.VillagerHeadMountBlock;
import net.mcreator.butchery.block.TurtleheadmountBlock;
import net.mcreator.butchery.block.TurtleheadBlock;
import net.mcreator.butchery.block.TurtlecarcassBlock;
import net.mcreator.butchery.block.TrimmedwardenHeadMountBlock;
import net.mcreator.butchery.block.TrimmedEnderDragonHeadMountBlock;
import net.mcreator.butchery.block.TaxidermytableBlock;
import net.mcreator.butchery.block.TabbycatheadmountBlock;
import net.mcreator.butchery.block.TabbycatheadBlock;
import net.mcreator.butchery.block.TabbycatcarcassBlock;
import net.mcreator.butchery.block.SulfuroreBlock;
import net.mcreator.butchery.block.StridercarcassBlock;
import net.mcreator.butchery.block.StrayheadmountBlock;
import net.mcreator.butchery.block.StrayheadBlock;
import net.mcreator.butchery.block.StraycorpseBlock;
import net.mcreator.butchery.block.SquidheadBlock;
import net.mcreator.butchery.block.SquidcarcassBlock;
import net.mcreator.butchery.block.SprucecounterBlock;
import net.mcreator.butchery.block.SprucebutcherstableBlock;
import net.mcreator.butchery.block.SpruceButcherdisplayBlock;
import net.mcreator.butchery.block.SpiketrapBlock;
import net.mcreator.butchery.block.SpiderheadmountBlock;
import net.mcreator.butchery.block.SpiderheadBlock;
import net.mcreator.butchery.block.SpidercarcassBlock;
import net.mcreator.butchery.block.SnowyfoxheadmountBlock;
import net.mcreator.butchery.block.SnowfoxheadBlock;
import net.mcreator.butchery.block.SnowfoxcarcassBlock;
import net.mcreator.butchery.block.SnifferheadBlock;
import net.mcreator.butchery.block.SniffercarcassblockBlock;
import net.mcreator.butchery.block.SmallslimecarcassBlock;
import net.mcreator.butchery.block.SmallemptyheadmountBlock;
import net.mcreator.butchery.block.SkinrackBlock;
import net.mcreator.butchery.block.SkeletonhorseheadmountBlock;
import net.mcreator.butchery.block.SkeletonhorseheadBlock;
import net.mcreator.butchery.block.SkeletonhorsecarcassBlock;
import net.mcreator.butchery.block.SkeletonheadmountBlock;
import net.mcreator.butchery.block.SkeletoncorpseBlock;
import net.mcreator.butchery.block.SkeletonBlock;
import net.mcreator.butchery.block.SilverfishheadmountBlock;
import net.mcreator.butchery.block.SilverfishheadBlock;
import net.mcreator.butchery.block.SilverfishcarcassBlock;
import net.mcreator.butchery.block.SiamesecatheadmountBlock;
import net.mcreator.butchery.block.SiamesecatheadBlock;
import net.mcreator.butchery.block.SiamesecatcarcassBlock;
import net.mcreator.butchery.block.ShulkercarcassBlock;
import net.mcreator.butchery.block.ShorthaircatheadmountBlock;
import net.mcreator.butchery.block.ShorthaircatheadBlock;
import net.mcreator.butchery.block.SheepskeletonBlock;
import net.mcreator.butchery.block.SheepheadBlock;
import net.mcreator.butchery.block.SheepcarcassBlock;
import net.mcreator.butchery.block.SheepHeadMountBlock;
import net.mcreator.butchery.block.SandBlock;
import net.mcreator.butchery.block.SaltformationtipBlock;
import net.mcreator.butchery.block.SaltformationmiddleBlock;
import net.mcreator.butchery.block.SaltformationfrustumBlock;
import net.mcreator.butchery.block.SaltformationbaseBlock;
import net.mcreator.butchery.block.SaltblockBlock;
import net.mcreator.butchery.block.SalmoncarcassBlock;
import net.mcreator.butchery.block.SalmonbarrelBlock;
import net.mcreator.butchery.block.RopeBlock;
import net.mcreator.butchery.block.RepairedirongolemheadmountBlock;
import net.mcreator.butchery.block.RepairedIrongolemlegsBlock;
import net.mcreator.butchery.block.RepairedIrongolemheadBlock;
import net.mcreator.butchery.block.RepairedIrongolembodyBlock;
import net.mcreator.butchery.block.RepairedIrongolemarmsBlock;
import net.mcreator.butchery.block.RepairedIrongolemBlock;
import net.mcreator.butchery.block.RegularblackhorsecarcassBlock;
import net.mcreator.butchery.block.RegularWhitehorsecarcassBlock;
import net.mcreator.butchery.block.RegularGrayhorsecarcassBlock;
import net.mcreator.butchery.block.RegularDarkbrownhorsecarcassBlock;
import net.mcreator.butchery.block.RegularCreamyhorsecarcassBlock;
import net.mcreator.butchery.block.RegularChestnuthorsecarcassBlock;
import net.mcreator.butchery.block.RegularBrownhorsecarcassBlock;
import net.mcreator.butchery.block.RedmooshroomheadBlock;
import net.mcreator.butchery.block.RedmooshroomcarcassBlock;
import net.mcreator.butchery.block.RedcatheadmountBlock;
import net.mcreator.butchery.block.RedcatheadBlock;
import net.mcreator.butchery.block.RedcatcarcassBlock;
import net.mcreator.butchery.block.RedMooshroomheadmountBlock;
import net.mcreator.butchery.block.RawsausagesBlock;
import net.mcreator.butchery.block.RawbloodsausagesBlock;
import net.mcreator.butchery.block.RavagerheadBlock;
import net.mcreator.butchery.block.RavagerHeadMountBlock;
import net.mcreator.butchery.block.RavagerBlock;
import net.mcreator.butchery.block.RagdollcatheadmountBlock;
import net.mcreator.butchery.block.RagdollcatheadBlock;
import net.mcreator.butchery.block.RagdollcatcarcassBlock;
import net.mcreator.butchery.block.RabbitheadBlock;
import net.mcreator.butchery.block.RabbitcarcassBlock;
import net.mcreator.butchery.block.RabbitHeadMountBlock;
import net.mcreator.butchery.block.PufferfishBlock;
import net.mcreator.butchery.block.PolarbearskeletonBlock;
import net.mcreator.butchery.block.PolarbearheadBlock;
import net.mcreator.butchery.block.PolarbearcarcassBlock;
import net.mcreator.butchery.block.PolarbearHeadMountBlock;
import net.mcreator.butchery.block.PlayercorpseBlock;
import net.mcreator.butchery.block.PlasticsheetcornerBlock;
import net.mcreator.butchery.block.PlasticsheetBlock;
import net.mcreator.butchery.block.PinkaxolotlheadmountBlock;
import net.mcreator.butchery.block.PinkaxolotlheadBlock;
import net.mcreator.butchery.block.PinkaxolotlcarcassBlock;
import net.mcreator.butchery.block.PillagerheadmountBlock;
import net.mcreator.butchery.block.PillagerheadBlock;
import net.mcreator.butchery.block.PillagercorpseBlock;
import net.mcreator.butchery.block.PigskeletonBlock;
import net.mcreator.butchery.block.PiglinskeletonBlock;
import net.mcreator.butchery.block.PiglincorpseBlock;
import net.mcreator.butchery.block.PiglinbruteheadBlock;
import net.mcreator.butchery.block.PiglinbrutecorpseBlock;
import net.mcreator.butchery.block.PiglinbruteHeadMountBlock;
import net.mcreator.butchery.block.PiglinHeadMountBlock;
import net.mcreator.butchery.block.PigheadBlock;
import net.mcreator.butchery.block.PigcarcassBlock;
import net.mcreator.butchery.block.PigHeadMountBlock;
import net.mcreator.butchery.block.PhotosBlock;
import net.mcreator.butchery.block.PhantomskeletonBlock;
import net.mcreator.butchery.block.PhantomheadmountBlock;
import net.mcreator.butchery.block.PhantomheadBlock;
import net.mcreator.butchery.block.PhantomcarcassBlock;
import net.mcreator.butchery.block.PestleandmortarBlock;
import net.mcreator.butchery.block.PersiancatheadmountBlock;
import net.mcreator.butchery.block.PersiancatheadBlock;
import net.mcreator.butchery.block.PersiancatcarcassBlock;
import net.mcreator.butchery.block.PandaskeletonBlock;
import net.mcreator.butchery.block.PandarugBlock;
import net.mcreator.butchery.block.PandaheadBlock;
import net.mcreator.butchery.block.PandacarcassBlock;
import net.mcreator.butchery.block.PandaHeadMountBlock;
import net.mcreator.butchery.block.OrangefrogcarcassBlock;
import net.mcreator.butchery.block.OcelotskeletonBlock;
import net.mcreator.butchery.block.OcelotheadmountBlock;
import net.mcreator.butchery.block.OcelotheadBlock;
import net.mcreator.butchery.block.OcelotcarcassBlock;
import net.mcreator.butchery.block.OakcounterBlock;
import net.mcreator.butchery.block.OakbutcherstableBlock;
import net.mcreator.butchery.block.OakbutcherdisplayBlock;
import net.mcreator.butchery.block.MuleskeletonBlock;
import net.mcreator.butchery.block.MuleheadmountBlock;
import net.mcreator.butchery.block.MuleheadBlock;
import net.mcreator.butchery.block.MulecarcassBlock;
import net.mcreator.butchery.block.MooshroomskeletonBlock;
import net.mcreator.butchery.block.MetaltrayBlock;
import net.mcreator.butchery.block.MetalbutcherstableBlock;
import net.mcreator.butchery.block.MediumslimecarcassBlock;
import net.mcreator.butchery.block.MediummagmacubecarcassBlock;
import net.mcreator.butchery.block.MeatgrinderBlock;
import net.mcreator.butchery.block.MangrovebutcherstableBlock;
import net.mcreator.butchery.block.MagmacubecarcassBlock;
import net.mcreator.butchery.block.LlamaskeletonBlock;
import net.mcreator.butchery.block.LargeemptyheadmountBlock;
import net.mcreator.butchery.block.JunglecounterBlock;
import net.mcreator.butchery.block.JunglebutcherstableBlock;
import net.mcreator.butchery.block.JunglebutcherdisplayBlock;
import net.mcreator.butchery.block.JelliecatheadmountBlock;
import net.mcreator.butchery.block.JelliecatheadBlock;
import net.mcreator.butchery.block.JelliecatcarcassBlock;
import net.mcreator.butchery.block.JarBlock;
import net.mcreator.butchery.block.IrongolemlegsBlock;
import net.mcreator.butchery.block.IrongolemheadmountBlock;
import net.mcreator.butchery.block.IrongolemheadBlock;
import net.mcreator.butchery.block.IrongolembodyBlock;
import net.mcreator.butchery.block.IrongolemarmsBlock;
import net.mcreator.butchery.block.IrongolemBlock;
import net.mcreator.butchery.block.InfectedBloodBlock;
import net.mcreator.butchery.block.HuskheadmountBlock;
import net.mcreator.butchery.block.HuskheadBlock;
import net.mcreator.butchery.block.HuskcorpseBlock;
import net.mcreator.butchery.block.HookBlock;
import net.mcreator.butchery.block.HoglinskeletonBlock;
import net.mcreator.butchery.block.HoglinheadmountBlock;
import net.mcreator.butchery.block.HoglinheadBlock;
import net.mcreator.butchery.block.HoglincarcassBlock;
import net.mcreator.butchery.block.HangingendermancarcassBlock;
import net.mcreator.butchery.block.HangingdrainedendermancarcassBlock;
import net.mcreator.butchery.block.GuardiancarcassBlock;
import net.mcreator.butchery.block.GreenfrogcarcassBlock;
import net.mcreator.butchery.block.GrayllamaheadmountBlock;
import net.mcreator.butchery.block.GrayllamaheadBlock;
import net.mcreator.butchery.block.GrayllamacarcassBlock;
import net.mcreator.butchery.block.GrayhorseheadmountBlock;
import net.mcreator.butchery.block.GrayhorseheadBlock;
import net.mcreator.butchery.block.GrayfrogcarcassBlock;
import net.mcreator.butchery.block.GoldaxolotlheadmountBlock;
import net.mcreator.butchery.block.GoldaxolotlcarcassBlock;
import net.mcreator.butchery.block.GoatskeletonBlock;
import net.mcreator.butchery.block.GoatrugBlock;
import net.mcreator.butchery.block.GoatheadBlock;
import net.mcreator.butchery.block.GoatcarcassBlock;
import net.mcreator.butchery.block.GoatHeadMountBlock;
import net.mcreator.butchery.block.GlowsquidheadBlock;
import net.mcreator.butchery.block.GlowsquidcarcassBlock;
import net.mcreator.butchery.block.GOLDaxolotlheadBlock;
import net.mcreator.butchery.block.FreezerBlock;
import net.mcreator.butchery.block.FoxskeletonBlock;
import net.mcreator.butchery.block.FoxheadBlock;
import net.mcreator.butchery.block.FoxcarcassBlock;
import net.mcreator.butchery.block.FoxHeadMountBlock;
import net.mcreator.butchery.block.FloorstandingSignBlock;
import net.mcreator.butchery.block.FishskeletonBlock;
import net.mcreator.butchery.block.EvokerheadBlock;
import net.mcreator.butchery.block.EvokercorpseBlock;
import net.mcreator.butchery.block.EvokerHeadMountBlock;
import net.mcreator.butchery.block.EndermiteheadmountBlock;
import net.mcreator.butchery.block.EndermiteheadBlock;
import net.mcreator.butchery.block.EndermiteBlock;
import net.mcreator.butchery.block.EndermanheadmountBlock;
import net.mcreator.butchery.block.EndermanheadBlock;
import net.mcreator.butchery.block.EndermancarcassBlock;
import net.mcreator.butchery.block.Enderdragoncut9Block;
import net.mcreator.butchery.block.Enderdragoncut8Block;
import net.mcreator.butchery.block.Enderdragoncut7Block;
import net.mcreator.butchery.block.Enderdragoncut6Block;
import net.mcreator.butchery.block.Enderdragoncut5Block;
import net.mcreator.butchery.block.Enderdragoncut4Block;
import net.mcreator.butchery.block.Enderdragoncut3Block;
import net.mcreator.butchery.block.Enderdragoncut2Block;
import net.mcreator.butchery.block.Enderdragoncut1Block;
import net.mcreator.butchery.block.Enderdragoncut14Block;
import net.mcreator.butchery.block.Enderdragoncut13Block;
import net.mcreator.butchery.block.Enderdragoncut12Block;
import net.mcreator.butchery.block.Enderdragoncut11Block;
import net.mcreator.butchery.block.Enderdragoncut10Block;
import net.mcreator.butchery.block.EnderdragoncarcassheadlessBlock;
import net.mcreator.butchery.block.EnderdragoncarcassBlock;
import net.mcreator.butchery.block.EnderDragonHeadMountBlock;
import net.mcreator.butchery.block.EmptywardentrimmedheadmountBlock;
import net.mcreator.butchery.block.EmptyturtleshellBlock;
import net.mcreator.butchery.block.EmptyheadmountBlock;
import net.mcreator.butchery.block.EmptydragontrimmedheadmountBlock;
import net.mcreator.butchery.block.ElderguardiancarcassBlock;
import net.mcreator.butchery.block.DrownedheadmountBlock;
import net.mcreator.butchery.block.DrownedheadBlock;
import net.mcreator.butchery.block.DrownedcorpseBlock;
import net.mcreator.butchery.block.DrainedzombievillagerBlock;
import net.mcreator.butchery.block.DrainedzombiecorpseBlock;
import net.mcreator.butchery.block.DrainedzoglincarcassBlock;
import net.mcreator.butchery.block.DrainedwitchcorpseBlock;
import net.mcreator.butchery.block.DrainedvillagerBlock;
import net.mcreator.butchery.block.DrainedstridercarcassBlock;
import net.mcreator.butchery.block.DrainedsniffercarcassblockBlock;
import net.mcreator.butchery.block.DrainedredmooshroomcarcassBlock;
import net.mcreator.butchery.block.DrainedrabbitcarcassBlock;
import net.mcreator.butchery.block.DrainedplayercorpseBlock;
import net.mcreator.butchery.block.DrainedpinkaxolotlcarcassBlock;
import net.mcreator.butchery.block.DrainedpiglincorpseBlock;
import net.mcreator.butchery.block.DrainedpigcarcassBlock;
import net.mcreator.butchery.block.DrainedphantomcarcassBlock;
import net.mcreator.butchery.block.DrainedpandacarcassBlock;
import net.mcreator.butchery.block.DrainedorangefrogcarcassBlock;
import net.mcreator.butchery.block.DrainedocelotcarcassBlock;
import net.mcreator.butchery.block.DrainedmulecarcassBlock;
import net.mcreator.butchery.block.DrainedhuskcorpseBlock;
import net.mcreator.butchery.block.DrainedhoglincarcassBlock;
import net.mcreator.butchery.block.DrainedguardiancarcassBlock;
import net.mcreator.butchery.block.DrainedgreenfrogcarcassBlock;
import net.mcreator.butchery.block.DrainedgrayfrogcarcassBlock;
import net.mcreator.butchery.block.DrainedgoatcarcassBlock;
import net.mcreator.butchery.block.DrainedfoxcarcassBlock;
import net.mcreator.butchery.block.DrainedevokercorpseBlock;
import net.mcreator.butchery.block.DrainedendermancarcassBlock;
import net.mcreator.butchery.block.DraineddrownedcorpseBlock;
import net.mcreator.butchery.block.DraineddonkeycarcassBlock;
import net.mcreator.butchery.block.DraineddolphincarcassBlock;
import net.mcreator.butchery.block.DrainedcreepercarcassBlock;
import net.mcreator.butchery.block.DrainedcowcarcassBlock;
import net.mcreator.butchery.block.DrainedchickencarcassBlock;
import net.mcreator.butchery.block.DrainedcamelcarcassBlock;
import net.mcreator.butchery.block.DrainedbrownmooshroomcarcassBlock;
import net.mcreator.butchery.block.DrainedbrownllamacarcassBlock;
import net.mcreator.butchery.block.DrainedblackcatcarcassBlock;
import net.mcreator.butchery.block.DrainedbatcarcassBlock;
import net.mcreator.butchery.block.DrainedallblackcatcarcassBlock;
import net.mcreator.butchery.block.DrainedZombiepiglincorpseBlock;
import net.mcreator.butchery.block.DrainedZombiehorsecarcassBlock;
import net.mcreator.butchery.block.DrainedWolfcarcassBlock;
import net.mcreator.butchery.block.DrainedWhitellamacarcassBlock;
import net.mcreator.butchery.block.DrainedWhitehorsecarcassBlock;
import net.mcreator.butchery.block.DrainedWhitecatcarcassBlock;
import net.mcreator.butchery.block.DrainedVindicatorcorpseBlock;
import net.mcreator.butchery.block.DrainedTurtlecarcassBlock;
import net.mcreator.butchery.block.DrainedTabbycatcarcassBlock;
import net.mcreator.butchery.block.DrainedSnowfoxcarcassBlock;
import net.mcreator.butchery.block.DrainedSiamesecatcarcassBlock;
import net.mcreator.butchery.block.DrainedSheepcarcassBlock;
import net.mcreator.butchery.block.DrainedRegularblackhorsecarcassBlock;
import net.mcreator.butchery.block.DrainedRegularDarkbrownhorsecarcassBlock;
import net.mcreator.butchery.block.DrainedRegularCreamyhorsecarcassBlock;
import net.mcreator.butchery.block.DrainedRegularChestnuthorsecarcassBlock;
import net.mcreator.butchery.block.DrainedRegularBrownhorsecarcassBlock;
import net.mcreator.butchery.block.DrainedRedcatcarcassBlock;
import net.mcreator.butchery.block.DrainedRagdollcatcarcassBlock;
import net.mcreator.butchery.block.DrainedPolarbearcarcassBlock;
import net.mcreator.butchery.block.DrainedPillagercorpseBlock;
import net.mcreator.butchery.block.DrainedPiglinbrutecorpseBlock;
import net.mcreator.butchery.block.DrainedPersiancatcarcassBlock;
import net.mcreator.butchery.block.DrainedJelliecatcarcassBlock;
import net.mcreator.butchery.block.DrainedGrayllamacarcassBlock;
import net.mcreator.butchery.block.DrainedGrayhorsecarcassBlock;
import net.mcreator.butchery.block.DrainedGoldaxolotlcarcassBlock;
import net.mcreator.butchery.block.DrainedCyanaxolotlcarcassBlock;
import net.mcreator.butchery.block.DrainedCreamyllamacarcassBlock;
import net.mcreator.butchery.block.DrainedCalicocatcarcassBlock;
import net.mcreator.butchery.block.DrainedBrownaxolotlcarcassBlock;
import net.mcreator.butchery.block.DrainedBritishshorthaircatcarcassBlock;
import net.mcreator.butchery.block.DrainedBlueaxolotlcarcassBlock;
import net.mcreator.butchery.block.DragonscaleblockBlock;
import net.mcreator.butchery.block.DonkeyskeletonBlock;
import net.mcreator.butchery.block.DonkeyheadmountBlock;
import net.mcreator.butchery.block.DonkeyheadBlock;
import net.mcreator.butchery.block.DonkeycarcassBlock;
import net.mcreator.butchery.block.DolphinskeletonBlock;
import net.mcreator.butchery.block.DolphinheadmountBlock;
import net.mcreator.butchery.block.DolphinheadBlock;
import net.mcreator.butchery.block.DolphincarcassBlock;
import net.mcreator.butchery.block.DioritebrickstairsBlock;
import net.mcreator.butchery.block.DioritebricksBlock;
import net.mcreator.butchery.block.DioriteBrickwallBlock;
import net.mcreator.butchery.block.DioriteBrickSlabBlock;
import net.mcreator.butchery.block.DeepslatesulfuroreBlock;
import net.mcreator.butchery.block.DarkoakcounterBlock;
import net.mcreator.butchery.block.DarkoakbutcherstableBlock;
import net.mcreator.butchery.block.DarkoakbutcherdisplayBlock;
import net.mcreator.butchery.block.DarkbrownhorseheadmountBlock;
import net.mcreator.butchery.block.DarkbrownhorseheadBlock;
import net.mcreator.butchery.block.CyanaxolotlheadmountBlock;
import net.mcreator.butchery.block.CyanaxolotlheadBlock;
import net.mcreator.butchery.block.CyanaxolotlcarcassBlock;
import net.mcreator.butchery.block.CrimsoncounterBlock;
import net.mcreator.butchery.block.CrimsonbutcherstableBlock;
import net.mcreator.butchery.block.CrimsonbutcherdisplayBlock;
import net.mcreator.butchery.block.CreeperskeletonBlock;
import net.mcreator.butchery.block.CreeperheadmountBlock;
import net.mcreator.butchery.block.CreepercarcassBlock;
import net.mcreator.butchery.block.CreamyllamaheadmountBlock;
import net.mcreator.butchery.block.CreamyllamaheadBlock;
import net.mcreator.butchery.block.CreamyllamacarcassBlock;
import net.mcreator.butchery.block.CreamyhorseheadmountBlock;
import net.mcreator.butchery.block.CreamyhorseheadBlock;
import net.mcreator.butchery.block.CowskeletonBlock;
import net.mcreator.butchery.block.CowheadmountBlock;
import net.mcreator.butchery.block.CowheadBlock;
import net.mcreator.butchery.block.CowcarcassBlock;
import net.mcreator.butchery.block.CookedsausagesBlock;
import net.mcreator.butchery.block.CookedbloodsausagesBlock;
import net.mcreator.butchery.block.CodcarcassBlock;
import net.mcreator.butchery.block.CodbarrelBlock;
import net.mcreator.butchery.block.ClingfilmBlock;
import net.mcreator.butchery.block.ChickenskeletonBlock;
import net.mcreator.butchery.block.ChickenheadmountBlock;
import net.mcreator.butchery.block.ChickenheadBlock;
import net.mcreator.butchery.block.ChickencarcassBlock;
import net.mcreator.butchery.block.ChestnuthorseheadmountBlock;
import net.mcreator.butchery.block.ChestnuthorseheadBlock;
import net.mcreator.butchery.block.CavespiderheadmountBlock;
import net.mcreator.butchery.block.CavespiderheadBlock;
import net.mcreator.butchery.block.CavespidercarcassBlock;
import net.mcreator.butchery.block.CatskeletonBlock;
import net.mcreator.butchery.block.CatcarcassBlock;
import net.mcreator.butchery.block.CashregisterblockBlock;
import net.mcreator.butchery.block.CanopyyellowBlock;
import net.mcreator.butchery.block.CanopyredBlock;
import net.mcreator.butchery.block.CanopypurpleBlock;
import net.mcreator.butchery.block.CanopypinkBlock;
import net.mcreator.butchery.block.CanopyorangeBlock;
import net.mcreator.butchery.block.CanopymagentaBlock;
import net.mcreator.butchery.block.CanopylimeBlock;
import net.mcreator.butchery.block.CanopylightgrayBlock;
import net.mcreator.butchery.block.CanopylightblueBlock;
import net.mcreator.butchery.block.CanopygreenBlock;
import net.mcreator.butchery.block.CanopygrayBlock;
import net.mcreator.butchery.block.CanopycyanBlock;
import net.mcreator.butchery.block.CanopybrownBlock;
import net.mcreator.butchery.block.CanopyblueBlock;
import net.mcreator.butchery.block.CanopyblackBlock;
import net.mcreator.butchery.block.CamelskeletonBlock;
import net.mcreator.butchery.block.CamelheadmountBlock;
import net.mcreator.butchery.block.CamelheadBlock;
import net.mcreator.butchery.block.CamelcarcassBlock;
import net.mcreator.butchery.block.CalicocatheadmountBlock;
import net.mcreator.butchery.block.CalicocatheadBlock;
import net.mcreator.butchery.block.CalicocatcarcassBlock;
import net.mcreator.butchery.block.ButcherstatueBlock;
import net.mcreator.butchery.block.BrownmooshroomheadBlock;
import net.mcreator.butchery.block.BrownmooshroomcarcassBlock;
import net.mcreator.butchery.block.BrownllamaheadmountBlock;
import net.mcreator.butchery.block.BrownllamaheadBlock;
import net.mcreator.butchery.block.BrownllamacarcassBlock;
import net.mcreator.butchery.block.BrownhorseheadmountBlock;
import net.mcreator.butchery.block.BrownhorseheadBlock;
import net.mcreator.butchery.block.BrownaxolotlheadmountBlock;
import net.mcreator.butchery.block.BrownaxolotlheadBlock;
import net.mcreator.butchery.block.BrownaxolotlcarcassBlock;
import net.mcreator.butchery.block.BrownMooshroomheadmountBlock;
import net.mcreator.butchery.block.BritishshorthaircatcarcassBlock;
import net.mcreator.butchery.block.BrainBlock;
import net.mcreator.butchery.block.BonebarrelBlock;
import net.mcreator.butchery.block.BlueaxolotlheadmountBlock;
import net.mcreator.butchery.block.BlueaxolotlheadBlock;
import net.mcreator.butchery.block.BlueaxolotlcarcassBlock;
import net.mcreator.butchery.block.BloodsplatterBlock;
import net.mcreator.butchery.block.BloodpuddleBlock;
import net.mcreator.butchery.block.BloodgrateBlock;
import net.mcreator.butchery.block.BloodBlock;
import net.mcreator.butchery.block.BlackhorseheadmountBlock;
import net.mcreator.butchery.block.BlackhorseheadBlock;
import net.mcreator.butchery.block.BlackcatheadmountBlock;
import net.mcreator.butchery.block.BlackcatheadBlock;
import net.mcreator.butchery.block.BlackcatcarcassBlock;
import net.mcreator.butchery.block.BirchcounterBlock;
import net.mcreator.butchery.block.BirchbutcherstableBlock;
import net.mcreator.butchery.block.BirchbutcherdisplayBlock;
import net.mcreator.butchery.block.BeeheadBlock;
import net.mcreator.butchery.block.BeecarcassBlock;
import net.mcreator.butchery.block.BearrugBlock;
import net.mcreator.butchery.block.BatskeletonBlock;
import net.mcreator.butchery.block.BatheadmountBlock;
import net.mcreator.butchery.block.BatheadBlock;
import net.mcreator.butchery.block.BatcarcassBlock;
import net.mcreator.butchery.block.BasinBlock;
import net.mcreator.butchery.block.AxolotlskeletonBlock;
import net.mcreator.butchery.block.AllblackcatheadmountBlock;
import net.mcreator.butchery.block.AllblackcatheadBlock;
import net.mcreator.butchery.block.AllblackcatcarcassBlock;
import net.mcreator.butchery.block.AcaciacounterBlock;
import net.mcreator.butchery.block.AcaciabutcherstableBlock;
import net.mcreator.butchery.block.AcaciabutcherdisplayBlock;
import net.mcreator.butchery.ButcheryMod;

import java.util.function.Function;

public class ButcheryModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(ButcheryMod.MODID);
	public static final DeferredBlock<Block> OAK_BUTCHERS_TABLE = register("oak_butchers_table", OakbutcherstableBlock::new);
	public static final DeferredBlock<Block> ACACIA_BUTCHERS_TABLE = register("acacia_butchers_table", AcaciabutcherstableBlock::new);
	public static final DeferredBlock<Block> BIRCH_BUTCHERS_TABLE = register("birch_butchers_table", BirchbutcherstableBlock::new);
	public static final DeferredBlock<Block> CRIMSON_BUTCHERS_TABLE = register("crimson_butchers_table", CrimsonbutcherstableBlock::new);
	public static final DeferredBlock<Block> DARK_OAK_BUTCHERS_TABLE = register("dark_oak_butchers_table", DarkoakbutcherstableBlock::new);
	public static final DeferredBlock<Block> JUNGLE_BUTCHERS_TABLE = register("jungle_butchers_table", JunglebutcherstableBlock::new);
	public static final DeferredBlock<Block> MANGROVE_BUTCHERS_TABLE = register("mangrove_butchers_table", MangrovebutcherstableBlock::new);
	public static final DeferredBlock<Block> SPRUCE_BUTCHERS_TABLE = register("spruce_butchers_table", SprucebutcherstableBlock::new);
	public static final DeferredBlock<Block> WARPED_BUTCHERS_TABLE = register("warped_butchers_table", WarpedbutcherstableBlock::new);
	public static final DeferredBlock<Block> HOOK = register("hook", HookBlock::new);
	public static final DeferredBlock<Block> METAL_BUTCHERS_TABLE = register("metal_butchers_table", MetalbutcherstableBlock::new);
	public static final DeferredBlock<Block> BLOOD_GRATE = register("blood_grate", BloodgrateBlock::new);
	public static final DeferredBlock<Block> BLOOD = register("blood", BloodBlock::new);
	public static final DeferredBlock<Block> MEAT_GRINDER = register("meat_grinder", MeatgrinderBlock::new);
	public static final DeferredBlock<Block> SKIN_RACK = register("skin_rack", SkinrackBlock::new);
	public static final DeferredBlock<Block> SALT_BLOCK = register("salt_block", SaltblockBlock::new);
	public static final DeferredBlock<Block> SALT_FORMATION_TIP = register("salt_formation_tip", SaltformationtipBlock::new);
	public static final DeferredBlock<Block> SALT_FORMATION_BASE = register("salt_formation_base", SaltformationbaseBlock::new);
	public static final DeferredBlock<Block> SALT_FORMATION_MIDDLE = register("salt_formation_middle", SaltformationmiddleBlock::new);
	public static final DeferredBlock<Block> SALT_FORMATION_FRUSTUM = register("salt_formation_frustum", SaltformationfrustumBlock::new);
	public static final DeferredBlock<Block> BASIN = register("basin", BasinBlock::new);
	public static final DeferredBlock<Block> BLOOD_PUDDLE = register("blood_puddle", BloodpuddleBlock::new);
	public static final DeferredBlock<Block> PIG_CARCASS = register("pig_carcass", PigcarcassBlock::new);
	public static final DeferredBlock<Block> PIG_HEAD = register("pig_head", PigheadBlock::new);
	public static final DeferredBlock<Block> DRAINED_PIG_CARCASS = register("drained_pig_carcass", DrainedpigcarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_COW_CARCASS = register("drained_cow_carcass", DrainedcowcarcassBlock::new);
	public static final DeferredBlock<Block> COW_CARCASS = register("cow_carcass", CowcarcassBlock::new);
	public static final DeferredBlock<Block> COW_HEAD = register("cow_head", CowheadBlock::new);
	public static final DeferredBlock<Block> SHEEP_CARCASS = register("sheep_carcass", SheepcarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_SHEEP_CARCASS = register("drained_sheep_carcass", DrainedSheepcarcassBlock::new);
	public static final DeferredBlock<Block> SHEEP_HEAD = register("sheep_head", SheepheadBlock::new);
	public static final DeferredBlock<Block> CHICKEN_CARCASS = register("chicken_carcass", ChickencarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_CHICKEN_CARCASS = register("drained_chicken_carcass", DrainedchickencarcassBlock::new);
	public static final DeferredBlock<Block> CHICKEN_HEAD = register("chicken_head", ChickenheadBlock::new);
	public static final DeferredBlock<Block> BAT_CARCASS = register("bat_carcass", BatcarcassBlock::new);
	public static final DeferredBlock<Block> BAT_HEAD = register("bat_head", BatheadBlock::new);
	public static final DeferredBlock<Block> DRAINED_BAT_CARCASS = register("drained_bat_carcass", DrainedbatcarcassBlock::new);
	public static final DeferredBlock<Block> DOLPHIN_CARCASS = register("dolphin_carcass", DolphincarcassBlock::new);
	public static final DeferredBlock<Block> DOLPHIN_HEAD = register("dolphin_head", DolphinheadBlock::new);
	public static final DeferredBlock<Block> DRAINED_DOLPHIN_CARCASS = register("drained_dolphin_carcass", DraineddolphincarcassBlock::new);
	public static final DeferredBlock<Block> GLOW_SQUID_CARCASS = register("glow_squid_carcass", GlowsquidcarcassBlock::new);
	public static final DeferredBlock<Block> GLOW_SQUID_HEAD = register("glow_squid_head", GlowsquidheadBlock::new);
	public static final DeferredBlock<Block> SQUID_CARCASS = register("squid_carcass", SquidcarcassBlock::new);
	public static final DeferredBlock<Block> SQUID_HEAD = register("squid_head", SquidheadBlock::new);
	public static final DeferredBlock<Block> GOAT_CARCASS = register("goat_carcass", GoatcarcassBlock::new);
	public static final DeferredBlock<Block> GOAT_HEAD = register("goat_head", GoatheadBlock::new);
	public static final DeferredBlock<Block> DRAINED_GOAT_CARCASS = register("drained_goat_carcass", DrainedgoatcarcassBlock::new);
	public static final DeferredBlock<Block> RED_MOOSHROOM_CARCASS = register("red_mooshroom_carcass", RedmooshroomcarcassBlock::new);
	public static final DeferredBlock<Block> RED_MOOSHROOM_HEAD = register("red_mooshroom_head", RedmooshroomheadBlock::new);
	public static final DeferredBlock<Block> DRAINED_RED_MOOSHROOM_CARCASS = register("drained_red_mooshroom_carcass", DrainedredmooshroomcarcassBlock::new);
	public static final DeferredBlock<Block> BROWN_MOOSHROOM_CARCASS = register("brown_mooshroom_carcass", BrownmooshroomcarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_BROWN_MOOSHROOM_CARCASS = register("drained_brown_mooshroom_carcass", DrainedbrownmooshroomcarcassBlock::new);
	public static final DeferredBlock<Block> BROWN_MOOSHROOM_HEAD = register("brown_mooshroom_head", BrownmooshroomheadBlock::new);
	public static final DeferredBlock<Block> OCELOT_CARCASS = register("ocelot_carcass", OcelotcarcassBlock::new);
	public static final DeferredBlock<Block> OCELOT_HEAD = register("ocelot_head", OcelotheadBlock::new);
	public static final DeferredBlock<Block> DRAINED_OCELOT_CARCASS = register("drained_ocelot_carcass", DrainedocelotcarcassBlock::new);
	public static final DeferredBlock<Block> CAMEL_CARCASS = register("camel_carcass", CamelcarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_CAMEL_CARCASS = register("drained_camel_carcass", DrainedcamelcarcassBlock::new);
	public static final DeferredBlock<Block> CAVE_SPIDER_CARCASS = register("cave_spider_carcass", CavespidercarcassBlock::new);
	public static final DeferredBlock<Block> CAVE_SPIDER_HEAD = register("cave_spider_head", CavespiderheadBlock::new);
	public static final DeferredBlock<Block> SPIDER_CARCASS = register("spider_carcass", SpidercarcassBlock::new);
	public static final DeferredBlock<Block> SPIDER_HEAD = register("spider_head", SpiderheadBlock::new);
	public static final DeferredBlock<Block> CAMEL_HEAD = register("camel_head", CamelheadBlock::new);
	public static final DeferredBlock<Block> COD_CARCASS = register("cod_carcass", CodcarcassBlock::new);
	public static final DeferredBlock<Block> SALMON_CARCASS = register("salmon_carcass", SalmoncarcassBlock::new);
	public static final DeferredBlock<Block> CREEPER_CARCASS = register("creeper_carcass", CreepercarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_CREEPER_CARCASS = register("drained_creeper_carcass", DrainedcreepercarcassBlock::new);
	public static final DeferredBlock<Block> DONKEY_CARCASS = register("donkey_carcass", DonkeycarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_DONKEY_CARCASS = register("drained_donkey_carcass", DraineddonkeycarcassBlock::new);
	public static final DeferredBlock<Block> DONKEY_HEAD = register("donkey_head", DonkeyheadBlock::new);
	public static final DeferredBlock<Block> MULE_CARCASS = register("mule_carcass", MulecarcassBlock::new);
	public static final DeferredBlock<Block> MULE_HEAD = register("mule_head", MuleheadBlock::new);
	public static final DeferredBlock<Block> DRAINED_MULE_CARCASS = register("drained_mule_carcass", DrainedmulecarcassBlock::new);
	public static final DeferredBlock<Block> DROWNED_CORPSE = register("drowned_corpse", DrownedcorpseBlock::new);
	public static final DeferredBlock<Block> DROWNED_HEAD = register("drowned_head", DrownedheadBlock::new);
	public static final DeferredBlock<Block> DRAINED_DROWNED_CORPSE = register("drained_drowned_corpse", DraineddrownedcorpseBlock::new);
	public static final DeferredBlock<Block> DRAINED_HUSK_CORPSE = register("drained_husk_corpse", DrainedhuskcorpseBlock::new);
	public static final DeferredBlock<Block> HUSK_CORPSE = register("husk_corpse", HuskcorpseBlock::new);
	public static final DeferredBlock<Block> HUSK_HEAD = register("husk_head", HuskheadBlock::new);
	public static final DeferredBlock<Block> ZOMBIE_CORPSE = register("zombie_corpse", ZombiecorpseBlock::new);
	public static final DeferredBlock<Block> DRAINED_ZOMBIE_CORPSE = register("drained_zombie_corpse", DrainedzombiecorpseBlock::new);
	public static final DeferredBlock<Block> EVOKER_CORPSE = register("evoker_corpse", EvokercorpseBlock::new);
	public static final DeferredBlock<Block> EVOKER_HEAD = register("evoker_head", EvokerheadBlock::new);
	public static final DeferredBlock<Block> FOX_CARCASS = register("fox_carcass", FoxcarcassBlock::new);
	public static final DeferredBlock<Block> FOX_HEAD = register("fox_head", FoxheadBlock::new);
	public static final DeferredBlock<Block> DRAINED_FOX_CARCASS = register("drained_fox_carcass", DrainedfoxcarcassBlock::new);
	public static final DeferredBlock<Block> SNOW_FOX_CARCASS = register("snow_fox_carcass", SnowfoxcarcassBlock::new);
	public static final DeferredBlock<Block> SNOW_FOX_HEAD = register("snow_fox_head", SnowfoxheadBlock::new);
	public static final DeferredBlock<Block> DRAINED_SNOWFOX_CARCASS = register("drained_snowfox_carcass", DrainedSnowfoxcarcassBlock::new);
	public static final DeferredBlock<Block> GUARDIAN_CARCASS = register("guardian_carcass", GuardiancarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_GUARDIAN_CARCASS = register("drained_guardian_carcass", DrainedguardiancarcassBlock::new);
	public static final DeferredBlock<Block> HOGLIN_CARCASS = register("hoglin_carcass", HoglincarcassBlock::new);
	public static final DeferredBlock<Block> HOGLIN_HEAD = register("hoglin_head", HoglinheadBlock::new);
	public static final DeferredBlock<Block> DRAINED_HOGLIN_CARCASS = register("drained_hoglin_carcass", DrainedhoglincarcassBlock::new);
	public static final DeferredBlock<Block> PANDA_CARCASS = register("panda_carcass", PandacarcassBlock::new);
	public static final DeferredBlock<Block> PANDA_HEAD = register("panda_head", PandaheadBlock::new);
	public static final DeferredBlock<Block> DRAINED_PANDA_CARCASS = register("drained_panda_carcass", DrainedpandacarcassBlock::new);
	public static final DeferredBlock<Block> PIGLIN_CORPSE = register("piglin_corpse", PiglincorpseBlock::new);
	public static final DeferredBlock<Block> DRAINED_PIGLIN_CORPSE = register("drained_piglin_corpse", DrainedpiglincorpseBlock::new);
	public static final DeferredBlock<Block> PIGLIN_BRUTE_CORPSE = register("piglin_brute_corpse", PiglinbrutecorpseBlock::new);
	public static final DeferredBlock<Block> PIGLIN_BRUTE_HEAD = register("piglin_brute_head", PiglinbruteheadBlock::new);
	public static final DeferredBlock<Block> DRAINED_PIGLIN_BRUTE_CORPSE = register("drained_piglin_brute_corpse", DrainedPiglinbrutecorpseBlock::new);
	public static final DeferredBlock<Block> DRAINED_EVOKER_CORPSE = register("drained_evoker_corpse", DrainedevokercorpseBlock::new);
	public static final DeferredBlock<Block> PILLAGER_CORPSE = register("pillager_corpse", PillagercorpseBlock::new);
	public static final DeferredBlock<Block> PILLAGER_HEAD = register("pillager_head", PillagerheadBlock::new);
	public static final DeferredBlock<Block> DRAINED_PILLAGER_CORPSE = register("drained_pillager_corpse", DrainedPillagercorpseBlock::new);
	public static final DeferredBlock<Block> VINDICATOR_CORPSE = register("vindicator_corpse", VindicatorcorpseBlock::new);
	public static final DeferredBlock<Block> VINDICATOR_HEAD = register("vindicator_head", VindicatorheadBlock::new);
	public static final DeferredBlock<Block> DRAINED_VINDICATOR_CORPSE = register("drained_vindicator_corpse", DrainedVindicatorcorpseBlock::new);
	public static final DeferredBlock<Block> POLAR_BEAR_CARCASS = register("polar_bear_carcass", PolarbearcarcassBlock::new);
	public static final DeferredBlock<Block> POLAR_BEAR_HEAD = register("polar_bear_head", PolarbearheadBlock::new);
	public static final DeferredBlock<Block> DRAINED_POLAR_BEAR_CARCASS = register("drained_polar_bear_carcass", DrainedPolarbearcarcassBlock::new);
	public static final DeferredBlock<Block> PUFFERFISH = register("pufferfish", PufferfishBlock::new);
	public static final DeferredBlock<Block> RABBIT_CARCASS = register("rabbit_carcass", RabbitcarcassBlock::new);
	public static final DeferredBlock<Block> RABBIT_HEAD = register("rabbit_head", RabbitheadBlock::new);
	public static final DeferredBlock<Block> DRAINED_RABBIT_CARCASS = register("drained_rabbit_carcass", DrainedrabbitcarcassBlock::new);
	public static final DeferredBlock<Block> SHULKER_CARCASS = register("shulker_carcass", ShulkercarcassBlock::new);
	public static final DeferredBlock<Block> SILVERFISH_CARCASS = register("silverfish_carcass", SilverfishcarcassBlock::new);
	public static final DeferredBlock<Block> SKELETON_CORPSE = register("skeleton_corpse", SkeletoncorpseBlock::new);
	public static final DeferredBlock<Block> STRAY_CORPSE = register("stray_corpse", StraycorpseBlock::new);
	public static final DeferredBlock<Block> STRAY_HEAD = register("stray_head", StrayheadBlock::new);
	public static final DeferredBlock<Block> MEDIUM_SLIME_CARCASS = register("medium_slime_carcass", MediumslimecarcassBlock::new);
	public static final DeferredBlock<Block> SMALL_SLIME_CARCASS = register("small_slime_carcass", SmallslimecarcassBlock::new);
	public static final DeferredBlock<Block> MEDIUM_MAGMA_CUBE_CARCASS = register("medium_magma_cube_carcass", MediummagmacubecarcassBlock::new);
	public static final DeferredBlock<Block> MAGMA_CUBE_CARCASS = register("magma_cube_carcass", MagmacubecarcassBlock::new);
	public static final DeferredBlock<Block> STRIDER_CARCASS = register("strider_carcass", StridercarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_STRIDER_CARCASS = register("drained_strider_carcass", DrainedstridercarcassBlock::new);
	public static final DeferredBlock<Block> VILLAGER_CORPSE = register("villager_corpse", VillagercorpseBlock::new);
	public static final DeferredBlock<Block> VILLAGER_HEAD = register("villager_head", VillagerheadBlock::new);
	public static final DeferredBlock<Block> DRAINED_VILLAGER = register("drained_villager", DrainedvillagerBlock::new);
	public static final DeferredBlock<Block> ZOMBIE_VILLAGER_CORPSE = register("zombie_villager_corpse", ZombievillagercorpseBlock::new);
	public static final DeferredBlock<Block> ZOMBIE_VILLAGER_HEAD = register("zombie_villager_head", ZombievillagerheadBlock::new);
	public static final DeferredBlock<Block> DRAINED_ZOMBIE_VILLAGER = register("drained_zombie_villager", DrainedzombievillagerBlock::new);
	public static final DeferredBlock<Block> ZOMBIFIED_PIGLIN_CORPSE = register("zombified_piglin_corpse", ZombiepiglincorpseBlock::new);
	public static final DeferredBlock<Block> DRAINED_ZOMBIFIED_PIGLIN_CORPSE = register("drained_zombified_piglin_corpse", DrainedZombiepiglincorpseBlock::new);
	public static final DeferredBlock<Block> ZOMBIFIED_PIGLIN_HEAD = register("zombified_piglin_head", ZombiepiglinheadBlock::new);
	public static final DeferredBlock<Block> WITHER_SKELETON_CORPSE = register("wither_skeleton_corpse", WitherskeletoncorpseBlock::new);
	public static final DeferredBlock<Block> TURTLE_CARCASS = register("turtle_carcass", TurtlecarcassBlock::new);
	public static final DeferredBlock<Block> TURTLE_HEAD = register("turtle_head", TurtleheadBlock::new);
	public static final DeferredBlock<Block> DRAINED_TURTLE_CARCASS = register("drained_turtle_carcass", DrainedTurtlecarcassBlock::new);
	public static final DeferredBlock<Block> EMPTY_TURTLE_SHELL = register("empty_turtle_shell", EmptyturtleshellBlock::new);
	public static final DeferredBlock<Block> METAL_TRAY = register("metal_tray", MetaltrayBlock::new);
	public static final DeferredBlock<Block> GRAY_FROG_CARCASS = register("gray_frog_carcass", GrayfrogcarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_GRAY_FROG_CARCASS = register("drained_gray_frog_carcass", DrainedgrayfrogcarcassBlock::new);
	public static final DeferredBlock<Block> GREEN_FROG_CARCASS = register("green_frog_carcass", GreenfrogcarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_GREEN_FROG_CARCASS = register("drained_green_frog_carcass", DrainedgreenfrogcarcassBlock::new);
	public static final DeferredBlock<Block> ORANGE_FROG_CARCASS = register("orange_frog_carcass", OrangefrogcarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_ORANGE_FROG_CARCASS = register("drained_orange_frog_carcass", DrainedorangefrogcarcassBlock::new);
	public static final DeferredBlock<Block> BROWN_LLAMA_CARCASS = register("brown_llama_carcass", BrownllamacarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_BROWN_LLAMA_CARCASS = register("drained_brown_llama_carcass", DrainedbrownllamacarcassBlock::new);
	public static final DeferredBlock<Block> BROWN_LLAMA_HEAD = register("brown_llama_head", BrownllamaheadBlock::new);
	public static final DeferredBlock<Block> CREAMY_LLAMA_CARCASS = register("creamy_llama_carcass", CreamyllamacarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_CREAMY_LLAMA_CARCASS = register("drained_creamy_llama_carcass", DrainedCreamyllamacarcassBlock::new);
	public static final DeferredBlock<Block> CREAMY_LLAMA_HEAD = register("creamy_llama_head", CreamyllamaheadBlock::new);
	public static final DeferredBlock<Block> GRAY_LLAMA_CARCASS = register("gray_llama_carcass", GrayllamacarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_GRAY_LLAMA_CARCASS = register("drained_gray_llama_carcass", DrainedGrayllamacarcassBlock::new);
	public static final DeferredBlock<Block> GRAY_LLAMA_HEAD = register("gray_llama_head", GrayllamaheadBlock::new);
	public static final DeferredBlock<Block> DRAINED_WHITE_LLAMA_CARCASS = register("drained_white_llama_carcass", DrainedWhitellamacarcassBlock::new);
	public static final DeferredBlock<Block> WHITE_LLAMA_HEAD = register("white_llama_head", WhitellamaheadBlock::new);
	public static final DeferredBlock<Block> WHITE_LLAMA_CARCASS = register("white_llama_carcass", WhiteLlamaCarcassBlock::new);
	public static final DeferredBlock<Block> FREEZER = register("freezer", FreezerBlock::new);
	public static final DeferredBlock<Block> TAXIDERMY_TABLE = register("taxidermy_table", TaxidermytableBlock::new);
	public static final DeferredBlock<Block> BROWN_LLAMA_HEAD_MOUNT = register("brown_llama_head_mount", BrownllamaheadmountBlock::new);
	public static final DeferredBlock<Block> CAMEL_HEAD_MOUNT = register("camel_head_mount", CamelheadmountBlock::new);
	public static final DeferredBlock<Block> CAVE_SPIDER_HEAD_MOUNT = register("cave_spider_head_mount", CavespiderheadmountBlock::new);
	public static final DeferredBlock<Block> CHICKEN_HEAD_MOUNT = register("chicken_head_mount", ChickenheadmountBlock::new);
	public static final DeferredBlock<Block> COW_HEAD_MOUNT = register("cow_head_mount", CowheadmountBlock::new);
	public static final DeferredBlock<Block> CREAMY_LLAMA_HEAD_MOUNT = register("creamy_llama_head_mount", CreamyllamaheadmountBlock::new);
	public static final DeferredBlock<Block> CREEPER_HEAD_MOUNT = register("creeper_head_mount", CreeperheadmountBlock::new);
	public static final DeferredBlock<Block> DOLPHIN_HEAD_MOUNT = register("dolphin_head_mount", DolphinheadmountBlock::new);
	public static final DeferredBlock<Block> DROWNED_HEAD_MOUNT = register("drowned_head_mount", DrownedheadmountBlock::new);
	public static final DeferredBlock<Block> EMPTY_HEAD_MOUNT = register("empty_head_mount", EmptyheadmountBlock::new);
	public static final DeferredBlock<Block> ENDERMAN_HEAD_MOUNT = register("enderman_head_mount", EndermanheadmountBlock::new);
	public static final DeferredBlock<Block> FOX_HEAD_MOUNT = register("fox_head_mount", FoxHeadMountBlock::new);
	public static final DeferredBlock<Block> GOAT_HEAD_MOUNT = register("goat_head_mount", GoatHeadMountBlock::new);
	public static final DeferredBlock<Block> GRAY_LLAMA_HEAD_MOUNT = register("gray_llama_head_mount", GrayllamaheadmountBlock::new);
	public static final DeferredBlock<Block> HOGLIN_HEAD_MOUNT = register("hoglin_head_mount", HoglinheadmountBlock::new);
	public static final DeferredBlock<Block> HUSK_HEAD_MOUNT = register("husk_head_mount", HuskheadmountBlock::new);
	public static final DeferredBlock<Block> LARGE_EMPTY_HEAD_MOUNT = register("large_empty_head_mount", LargeemptyheadmountBlock::new);
	public static final DeferredBlock<Block> PANDA_HEAD_MOUNT = register("panda_head_mount", PandaHeadMountBlock::new);
	public static final DeferredBlock<Block> PIG_HEAD_MOUNT = register("pig_head_mount", PigHeadMountBlock::new);
	public static final DeferredBlock<Block> PILLAGER_HEAD_MOUNT = register("pillager_head_mount", PillagerheadmountBlock::new);
	public static final DeferredBlock<Block> POLARBEAR_HEAD_MOUNT = register("polarbear_head_mount", PolarbearHeadMountBlock::new);
	public static final DeferredBlock<Block> SHEEP_HEAD_MOUNT = register("sheep_head_mount", SheepHeadMountBlock::new);
	public static final DeferredBlock<Block> SKELETON_HEAD_MOUNT = register("skeleton_head_mount", SkeletonheadmountBlock::new);
	public static final DeferredBlock<Block> SNOWY_FOX_HEAD_MOUNT = register("snowy_fox_head_mount", SnowyfoxheadmountBlock::new);
	public static final DeferredBlock<Block> SPIDER_HEAD_MOUNT = register("spider_head_mount", SpiderheadmountBlock::new);
	public static final DeferredBlock<Block> VILLAGER_HEAD_MOUNT = register("villager_head_mount", VillagerHeadMountBlock::new);
	public static final DeferredBlock<Block> WHITE_LLAMA_HEAD_MOUNT = register("white_llama_head_mount", WhitellamaheadmountBlock::new);
	public static final DeferredBlock<Block> ZOMBIE_HEAD_MOUNT = register("zombie_head_mount", ZombieheadmountBlock::new);
	public static final DeferredBlock<Block> ZOMBIE_VILLAGER_HEAD_MOUNT = register("zombie_villager_head_mount", ZombievillagerheadmountBlock::new);
	public static final DeferredBlock<Block> OCELOT_HEAD_MOUNT = register("ocelot_head_mount", OcelotheadmountBlock::new);
	public static final DeferredBlock<Block> CANOPY_BLACK = register("canopy_black", CanopyblackBlock::new);
	public static final DeferredBlock<Block> CANOPY_BLUE = register("canopy_blue", CanopyblueBlock::new);
	public static final DeferredBlock<Block> CANOPY_BROWN = register("canopy_brown", CanopybrownBlock::new);
	public static final DeferredBlock<Block> CANOPY_CYAN = register("canopy_cyan", CanopycyanBlock::new);
	public static final DeferredBlock<Block> CANOPY_GRAY = register("canopy_gray", CanopygrayBlock::new);
	public static final DeferredBlock<Block> CANOPY_GREEN = register("canopy_green", CanopygreenBlock::new);
	public static final DeferredBlock<Block> CANOPY_LIGHT_BLUE = register("canopy_light_blue", CanopylightblueBlock::new);
	public static final DeferredBlock<Block> CANOPY_LIGHT_GRAY = register("canopy_light_gray", CanopylightgrayBlock::new);
	public static final DeferredBlock<Block> CANOPY_LIME = register("canopy_lime", CanopylimeBlock::new);
	public static final DeferredBlock<Block> CANOPY_MAGENTA = register("canopy_magenta", CanopymagentaBlock::new);
	public static final DeferredBlock<Block> CANOPY_ORANGE = register("canopy_orange", CanopyorangeBlock::new);
	public static final DeferredBlock<Block> CANOPY_PINK = register("canopy_pink", CanopypinkBlock::new);
	public static final DeferredBlock<Block> CANOPY_PURPLE = register("canopy_purple", CanopypurpleBlock::new);
	public static final DeferredBlock<Block> CANOPY_RED = register("canopy_red", CanopyredBlock::new);
	public static final DeferredBlock<Block> CANOPY_YELLOW = register("canopy_yellow", CanopyyellowBlock::new);
	public static final DeferredBlock<Block> FLOORSTANDING_SIGN = register("floorstanding_sign", FloorstandingSignBlock::new);
	public static final DeferredBlock<Block> BUTCHER_STATUE = register("butcher_statue", ButcherstatueBlock::new);
	public static final DeferredBlock<Block> DIORITE_BRICK_SLAB = register("diorite_brick_slab", DioriteBrickSlabBlock::new);
	public static final DeferredBlock<Block> DIORITE_BRICK_WALL = register("diorite_brick_wall", DioriteBrickwallBlock::new);
	public static final DeferredBlock<Block> DIORITE_BRICKS = register("diorite_bricks", DioritebricksBlock::new);
	public static final DeferredBlock<Block> DIORITE_BRICK_STAIRS = register("diorite_brick_stairs", DioritebrickstairsBlock::new);
	public static final DeferredBlock<Block> ROPE = register("rope", RopeBlock::new);
	public static final DeferredBlock<Block> SAND = register("sand", SandBlock::new);
	public static final DeferredBlock<Block> ENDER_DRAGON_CARCASS = register("ender_dragon_carcass", EnderdragoncarcassBlock::new);
	public static final DeferredBlock<Block> DRAGON_SCALE_BLOCK = register("dragon_scale_block", DragonscaleblockBlock::new);
	public static final DeferredBlock<Block> ENDER_DRAGON_CARCASS_HEADLESS = register("ender_dragon_carcass_headless", EnderdragoncarcassheadlessBlock::new);
	public static final DeferredBlock<Block> ENDERDRAGONCUT_1 = register("enderdragoncut_1", Enderdragoncut1Block::new);
	public static final DeferredBlock<Block> ENDERDRAGONCUT_2 = register("enderdragoncut_2", Enderdragoncut2Block::new);
	public static final DeferredBlock<Block> ENDERDRAGONCUT_3 = register("enderdragoncut_3", Enderdragoncut3Block::new);
	public static final DeferredBlock<Block> ENDERDRAGONCUT_4 = register("enderdragoncut_4", Enderdragoncut4Block::new);
	public static final DeferredBlock<Block> ENDERDRAGONCUT_5 = register("enderdragoncut_5", Enderdragoncut5Block::new);
	public static final DeferredBlock<Block> ENDERDRAGONCUT_6 = register("enderdragoncut_6", Enderdragoncut6Block::new);
	public static final DeferredBlock<Block> ENDERDRAGONCUT_7 = register("enderdragoncut_7", Enderdragoncut7Block::new);
	public static final DeferredBlock<Block> ENDERDRAGONCUT_8 = register("enderdragoncut_8", Enderdragoncut8Block::new);
	public static final DeferredBlock<Block> ENDERDRAGONCUT_9 = register("enderdragoncut_9", Enderdragoncut9Block::new);
	public static final DeferredBlock<Block> ENDERDRAGONCUT_10 = register("enderdragoncut_10", Enderdragoncut10Block::new);
	public static final DeferredBlock<Block> ENDERDRAGONCUT_11 = register("enderdragoncut_11", Enderdragoncut11Block::new);
	public static final DeferredBlock<Block> ENDERDRAGONCUT_12 = register("enderdragoncut_12", Enderdragoncut12Block::new);
	public static final DeferredBlock<Block> ENDERDRAGONCUT_13 = register("enderdragoncut_13", Enderdragoncut13Block::new);
	public static final DeferredBlock<Block> ENDERDRAGONCUT_14 = register("enderdragoncut_14", Enderdragoncut14Block::new);
	public static final DeferredBlock<Block> WOODEN_SPIT_ROTISSERIE = register("wooden_spit_rotisserie", WoodenspitrotisserieBlock::new);
	public static final DeferredBlock<Block> POLARBEAR_RUG = register("polarbear_rug", BearrugBlock::new);
	public static final DeferredBlock<Block> GOAT_RUG = register("goat_rug", GoatrugBlock::new);
	public static final DeferredBlock<Block> PANDA_RUG = register("panda_rug", PandarugBlock::new);
	public static final DeferredBlock<Block> CASH_REGISTER_BLOCK = register("cash_register_block", CashregisterblockBlock::new);
	public static final DeferredBlock<Block> ACACIA_BUTCHER_DISPLAY = register("acacia_butcher_display", AcaciabutcherdisplayBlock::new);
	public static final DeferredBlock<Block> BIRCH_BUTCHER_DISPLAY = register("birch_butcher_display", BirchbutcherdisplayBlock::new);
	public static final DeferredBlock<Block> CRIMSON_BUTCHER_DISPLAY = register("crimson_butcher_display", CrimsonbutcherdisplayBlock::new);
	public static final DeferredBlock<Block> DARK_OAK_BUTCHER_DISPLAY = register("dark_oak_butcher_display", DarkoakbutcherdisplayBlock::new);
	public static final DeferredBlock<Block> JUNGLE_BUTCHER_DISPLAY = register("jungle_butcher_display", JunglebutcherdisplayBlock::new);
	public static final DeferredBlock<Block> OAK_BUTCHER_DISPLAY = register("oak_butcher_display", OakbutcherdisplayBlock::new);
	public static final DeferredBlock<Block> SPRUCE_BUTCHER_DISPLAY = register("spruce_butcher_display", SpruceButcherdisplayBlock::new);
	public static final DeferredBlock<Block> WARPED_BUTCHER_DISPLAY = register("warped_butcher_display", WarpedbutcherdisplayBlock::new);
	public static final DeferredBlock<Block> ACACIA_COUNTER = register("acacia_counter", AcaciacounterBlock::new);
	public static final DeferredBlock<Block> BIRCH_COUNTER = register("birch_counter", BirchcounterBlock::new);
	public static final DeferredBlock<Block> CRIMSON_COUNTER = register("crimson_counter", CrimsoncounterBlock::new);
	public static final DeferredBlock<Block> DARK_OAK_COUNTER = register("dark_oak_counter", DarkoakcounterBlock::new);
	public static final DeferredBlock<Block> JUNGLE_COUNTER = register("jungle_counter", JunglecounterBlock::new);
	public static final DeferredBlock<Block> OAK_COUNTER = register("oak_counter", OakcounterBlock::new);
	public static final DeferredBlock<Block> SPRUCE_COUNTER = register("spruce_counter", SprucecounterBlock::new);
	public static final DeferredBlock<Block> WARPED_COUNTER = register("warped_counter", WarpedcounterBlock::new);
	public static final DeferredBlock<Block> BLOOD_SPLATTER = register("blood_splatter", BloodsplatterBlock::new);
	public static final DeferredBlock<Block> BONE_BARREL = register("bone_barrel", BonebarrelBlock::new);
	public static final DeferredBlock<Block> COD_BARREL = register("cod_barrel", CodbarrelBlock::new);
	public static final DeferredBlock<Block> SALMON_BARREL = register("salmon_barrel", SalmonbarrelBlock::new);
	public static final DeferredBlock<Block> PINK_AXOLOTL_CARCASS = register("pink_axolotl_carcass", PinkaxolotlcarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_PINK_AXOLOTL_CARCASS = register("drained_pink_axolotl_carcass", DrainedpinkaxolotlcarcassBlock::new);
	public static final DeferredBlock<Block> BLUE_AXOLOTL_CARCASS = register("blue_axolotl_carcass", BlueaxolotlcarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_BLUE_AXOLOTL_CARCASS = register("drained_blue_axolotl_carcass", DrainedBlueaxolotlcarcassBlock::new);
	public static final DeferredBlock<Block> BROWN_AXOLOTL_CARCASS = register("brown_axolotl_carcass", BrownaxolotlcarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_BROWN_AXOLOTL_CARCASS = register("drained_brown_axolotl_carcass", DrainedBrownaxolotlcarcassBlock::new);
	public static final DeferredBlock<Block> CYAN_AXOLOTL_CARCASS = register("cyan_axolotl_carcass", CyanaxolotlcarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_CYAN_AXOLOTL_CARCASS = register("drained_cyan_axolotl_carcass", DrainedCyanaxolotlcarcassBlock::new);
	public static final DeferredBlock<Block> GOLD_AXOLOTL_CARCASS = register("gold_axolotl_carcass", GoldaxolotlcarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_GOLD_AXOLOTL_CARCASS = register("drained_gold_axolotl_carcass", DrainedGoldaxolotlcarcassBlock::new);
	public static final DeferredBlock<Block> PINK_AXOLOTL_HEAD = register("pink_axolotl_head", PinkaxolotlheadBlock::new);
	public static final DeferredBlock<Block> BLUE_AXOLOTL_HEAD = register("blue_axolotl_head", BlueaxolotlheadBlock::new);
	public static final DeferredBlock<Block> CYAN_AXOLOTL_HEAD = register("cyan_axolotl_head", CyanaxolotlheadBlock::new);
	public static final DeferredBlock<Block> GOLD_AXOLOTL_HEAD = register("gold_axolotl_head", GOLDaxolotlheadBlock::new);
	public static final DeferredBlock<Block> BROWN_AXOLOTL_HEAD = register("brown_axolotl_head", BrownaxolotlheadBlock::new);
	public static final DeferredBlock<Block> BLUE_AXOLOTL_HEAD_MOUNT = register("blue_axolotl_head_mount", BlueaxolotlheadmountBlock::new);
	public static final DeferredBlock<Block> BROWN_AXOLOTL_HEAD_MOUNT = register("brown_axolotl_head_mount", BrownaxolotlheadmountBlock::new);
	public static final DeferredBlock<Block> CYAN_AXOLOTL_HEAD_MOUNT = register("cyan_axolotl_head_mount", CyanaxolotlheadmountBlock::new);
	public static final DeferredBlock<Block> GOLD_AXOLOTL_HEAD_MOUNT = register("gold_axolotl_head_mount", GoldaxolotlheadmountBlock::new);
	public static final DeferredBlock<Block> PINK_AXOLOTL_HEAD_MOUNT = register("pink_axolotl_head_mount", PinkaxolotlheadmountBlock::new);
	public static final DeferredBlock<Block> BAT_HEAD_MOUNT = register("bat_head_mount", BatheadmountBlock::new);
	public static final DeferredBlock<Block> DONKEY_HEAD_MOUNT = register("donkey_head_mount", DonkeyheadmountBlock::new);
	public static final DeferredBlock<Block> MULE_HEAD_MOUNT = register("mule_head_mount", MuleheadmountBlock::new);
	public static final DeferredBlock<Block> EVOKER_HEAD_MOUNT = register("evoker_head_mount", EvokerHeadMountBlock::new);
	public static final DeferredBlock<Block> VINDICATOR_HEAD_MOUNT = register("vindicator_head_mount", VindicatorHeadMountBlock::new);
	public static final DeferredBlock<Block> RED_MOOSHROOM_HEAD_MOUNT = register("red_mooshroom_head_mount", RedMooshroomheadmountBlock::new);
	public static final DeferredBlock<Block> BROWN_MOOSHROOM_HEAD_MOUNT = register("brown_mooshroom_head_mount", BrownMooshroomheadmountBlock::new);
	public static final DeferredBlock<Block> PIGLIN_HEAD_MOUNT = register("piglin_head_mount", PiglinHeadMountBlock::new);
	public static final DeferredBlock<Block> PIGLIN_BRUTE_HEAD_MOUNT = register("piglin_brute_head_mount", PiglinbruteHeadMountBlock::new);
	public static final DeferredBlock<Block> ZOMBIFIED_PIGLIN_HEAD_MOUNT = register("zombified_piglin_head_mount", ZombifiedPiglinHeadMountBlock::new);
	public static final DeferredBlock<Block> RABBIT_HEAD_MOUNT = register("rabbit_head_mount", RabbitHeadMountBlock::new);
	public static final DeferredBlock<Block> STRAY_HEAD_MOUNT = register("stray_head_mount", StrayheadmountBlock::new);
	public static final DeferredBlock<Block> TURTLE_HEAD_MOUNT = register("turtle_head_mount", TurtleheadmountBlock::new);
	public static final DeferredBlock<Block> WITHER_SKELETON_HEAD_MOUNT = register("wither_skeleton_head_mount", WitherskeletonheadmountBlock::new);
	public static final DeferredBlock<Block> HANGING_ENDERMAN_CARCASS = register("hanging_enderman_carcass", HangingendermancarcassBlock::new);
	public static final DeferredBlock<Block> ENDERMAN_CARCASS = register("enderman_carcass", EndermancarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_ENDERMAN_CARCASS = register("drained_enderman_carcass", DrainedendermancarcassBlock::new);
	public static final DeferredBlock<Block> ENDERMAN_HEAD = register("enderman_head", EndermanheadBlock::new);
	public static final DeferredBlock<Block> HANGING_DRAINED_ENDERMAN_CARCASS = register("hanging_drained_enderman_carcass", HangingdrainedendermancarcassBlock::new);
	public static final DeferredBlock<Block> ENDERMITE_CARCASS = register("endermite_carcass", EndermiteBlock::new);
	public static final DeferredBlock<Block> ENDERMITE_HEAD_MOUNT = register("endermite_head_mount", EndermiteheadmountBlock::new);
	public static final DeferredBlock<Block> SILVERFISH_HEAD_MOUNT = register("silverfish_head_mount", SilverfishheadmountBlock::new);
	public static final DeferredBlock<Block> ENDERMITE_HEAD = register("endermite_head", EndermiteheadBlock::new);
	public static final DeferredBlock<Block> SILVERFISH_HEAD = register("silverfish_head", SilverfishheadBlock::new);
	public static final DeferredBlock<Block> SMALL_EMPTY_HEAD_MOUNT = register("small_empty_head_mount", SmallemptyheadmountBlock::new);
	public static final DeferredBlock<Block> PHANTOM_CARCASS = register("phantom_carcass", PhantomcarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_PHANTOM_CARCASS = register("drained_phantom_carcass", DrainedphantomcarcassBlock::new);
	public static final DeferredBlock<Block> PHANTOM_HEAD = register("phantom_head", PhantomheadBlock::new);
	public static final DeferredBlock<Block> PHANTOM_HEAD_MOUNT = register("phantom_head_mount", PhantomheadmountBlock::new);
	public static final DeferredBlock<Block> ALL_BLACK_CAT_CARCASS = register("all_black_cat_carcass", AllblackcatcarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_ALL_BLACK_CAT_CARCASS = register("drained_all_black_cat_carcass", DrainedallblackcatcarcassBlock::new);
	public static final DeferredBlock<Block> BLACK_CAT_CARCASS = register("black_cat_carcass", BlackcatcarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_BLACK_CAT_CARCASS = register("drained_black_cat_carcass", DrainedblackcatcarcassBlock::new);
	public static final DeferredBlock<Block> BRITISH_SHORTHAIR_CAT_CARCASS = register("british_shorthair_cat_carcass", BritishshorthaircatcarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_BRITISH_SHORTHAIR_CAT_CARCASS = register("drained_british_shorthair_cat_carcass", DrainedBritishshorthaircatcarcassBlock::new);
	public static final DeferredBlock<Block> CALICO_CAT_CARCASS = register("calico_cat_carcass", CalicocatcarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_CALICO_CAT_CARCASS = register("drained_calico_cat_carcass", DrainedCalicocatcarcassBlock::new);
	public static final DeferredBlock<Block> JELLIE_CAT_CARCASS = register("jellie_cat_carcass", JelliecatcarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_JELLIE_CAT_CARCASS = register("drained_jellie_cat_carcass", DrainedJelliecatcarcassBlock::new);
	public static final DeferredBlock<Block> PERSIAN_CAT_CARCASS = register("persian_cat_carcass", PersiancatcarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_PERSIAN_CAT_CARCASS = register("drained_persian_cat_carcass", DrainedPersiancatcarcassBlock::new);
	public static final DeferredBlock<Block> RAGDOLL_CAT_CARCASS = register("ragdoll_cat_carcass", RagdollcatcarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_RAGDOLL_CAT_CARCASS = register("drained_ragdoll_cat_carcass", DrainedRagdollcatcarcassBlock::new);
	public static final DeferredBlock<Block> RED_CAT_CARCASS = register("red_cat_carcass", RedcatcarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_RED_CAT_CARCASS = register("drained_red_cat_carcass", DrainedRedcatcarcassBlock::new);
	public static final DeferredBlock<Block> SIAMESE_CAT_CARCASS = register("siamese_cat_carcass", SiamesecatcarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_SIAMESE_CAT_CARCASS = register("drained_siamese_cat_carcass", DrainedSiamesecatcarcassBlock::new);
	public static final DeferredBlock<Block> TABBY_CAT_CARCASS = register("tabby_cat_carcass", TabbycatcarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_TABBY_CAT_CARCASS = register("drained_tabby_cat_carcass", DrainedTabbycatcarcassBlock::new);
	public static final DeferredBlock<Block> WHITE_CAT_CARCASS = register("white_cat_carcass", WhitecatcarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_WHITE_CAT_CARCASS = register("drained_white_cat_carcass", DrainedWhitecatcarcassBlock::new);
	public static final DeferredBlock<Block> BLACK_CAT_HEAD = register("black_cat_head", BlackcatheadBlock::new);
	public static final DeferredBlock<Block> ALL_BLACK_CAT_HEAD = register("all_black_cat_head", AllblackcatheadBlock::new);
	public static final DeferredBlock<Block> TABBY_CAT_HEAD = register("tabby_cat_head", TabbycatheadBlock::new);
	public static final DeferredBlock<Block> RED_CAT_HEAD = register("red_cat_head", RedcatheadBlock::new);
	public static final DeferredBlock<Block> SIAMESE_CAT_HEAD = register("siamese_cat_head", SiamesecatheadBlock::new);
	public static final DeferredBlock<Block> SHORTHAIR_CAT_HEAD = register("shorthair_cat_head", ShorthaircatheadBlock::new);
	public static final DeferredBlock<Block> RAGDOLL_CAT_HEAD = register("ragdoll_cat_head", RagdollcatheadBlock::new);
	public static final DeferredBlock<Block> JELLIE_CAT_HEAD = register("jellie_cat_head", JelliecatheadBlock::new);
	public static final DeferredBlock<Block> WHITE_CAT_HEAD = register("white_cat_head", WhitecatheadBlock::new);
	public static final DeferredBlock<Block> PERSIAN_CAT_HEAD = register("persian_cat_head", PersiancatheadBlock::new);
	public static final DeferredBlock<Block> CALICO_CAT_HEAD = register("calico_cat_head", CalicocatheadBlock::new);
	public static final DeferredBlock<Block> CAT_CARCASS = register("cat_carcass", CatcarcassBlock::new);
	public static final DeferredBlock<Block> ELDER_GUARDIAN_CARCASS = register("elder_guardian_carcass", ElderguardiancarcassBlock::new);
	public static final DeferredBlock<Block> WITCH_CORPSE = register("witch_corpse", WitchcorpseBlock::new);
	public static final DeferredBlock<Block> DRAINED_WITCH_CORPSE = register("drained_witch_corpse", DrainedwitchcorpseBlock::new);
	public static final DeferredBlock<Block> WITCH_HEAD = register("witch_head", WitchheadBlock::new);
	public static final DeferredBlock<Block> IRON_GOLEM = register("iron_golem", IrongolemBlock::new);
	public static final DeferredBlock<Block> IRON_GOLEM_HEAD = register("iron_golem_head", IrongolemheadBlock::new);
	public static final DeferredBlock<Block> IRON_GOLEM_ARMS = register("iron_golem_arms", IrongolemarmsBlock::new);
	public static final DeferredBlock<Block> IRON_GOLEM_LEGS = register("iron_golem_legs", IrongolemlegsBlock::new);
	public static final DeferredBlock<Block> IRON_GOLEM_BODY = register("iron_golem_body", IrongolembodyBlock::new);
	public static final DeferredBlock<Block> REPAIRED_IRON_GOLEM_HEAD = register("repaired_iron_golem_head", RepairedIrongolemheadBlock::new);
	public static final DeferredBlock<Block> REPAIRED_IRON_GOLEM_ARMS = register("repaired_iron_golem_arms", RepairedIrongolemarmsBlock::new);
	public static final DeferredBlock<Block> REPAIRED_IRON_GOLEM_LEGS = register("repaired_iron_golem_legs", RepairedIrongolemlegsBlock::new);
	public static final DeferredBlock<Block> REPAIRED_IRON_GOLEM_BODY = register("repaired_iron_golem_body", RepairedIrongolembodyBlock::new);
	public static final DeferredBlock<Block> ALL_BLACK_CAT_HEAD_MOUNT = register("all_black_cat_head_mount", AllblackcatheadmountBlock::new);
	public static final DeferredBlock<Block> BLACK_CAT_HEAD_MOUNT = register("black_cat_head_mount", BlackcatheadmountBlock::new);
	public static final DeferredBlock<Block> TABBY_CAT_HEAD_MOUNT = register("tabby_cat_head_mount", TabbycatheadmountBlock::new);
	public static final DeferredBlock<Block> RED_CAT_HEAD_MOUNT = register("red_cat_head_mount", RedcatheadmountBlock::new);
	public static final DeferredBlock<Block> SIAMESE_CAT_HEAD_MOUNT = register("siamese_cat_head_mount", SiamesecatheadmountBlock::new);
	public static final DeferredBlock<Block> SHORTHAIR_CAT_HEAD_MOUNT = register("shorthair_cat_head_mount", ShorthaircatheadmountBlock::new);
	public static final DeferredBlock<Block> RAGDOLL_CAT_HEAD_MOUNT = register("ragdoll_cat_head_mount", RagdollcatheadmountBlock::new);
	public static final DeferredBlock<Block> JELLIE_CAT_HEAD_MOUNT = register("jellie_cat_head_mount", JelliecatheadmountBlock::new);
	public static final DeferredBlock<Block> WHITE_CAT_HEAD_MOUNT = register("white_cat_head_mount", WhitecatheadmountBlock::new);
	public static final DeferredBlock<Block> PERSIAN_CAT_HEAD_MOUNT = register("persian_cat_head_mount", PersiancatheadmountBlock::new);
	public static final DeferredBlock<Block> CALICO_CAT_HEAD_MOUNT = register("calico_cat_head_mount", CalicocatheadmountBlock::new);
	public static final DeferredBlock<Block> IRON_GOLEM_HEAD_MOUNT = register("iron_golem_head_mount", IrongolemheadmountBlock::new);
	public static final DeferredBlock<Block> REPAIRED_IRON_GOLEM_HEAD_MOUNT = register("repaired_iron_golem_head_mount", RepairedirongolemheadmountBlock::new);
	public static final DeferredBlock<Block> WITCH_HEAD_MOUNT = register("witch_head_mount", WitchheadmountBlock::new);
	public static final DeferredBlock<Block> WITHER_CARCASS = register("wither_carcass", WithercarcassBlock::new);
	public static final DeferredBlock<Block> ZOGLIN_CARCASS = register("zoglin_carcass", ZoglincarcassBlock::new);
	public static final DeferredBlock<Block> ZOGLIN_HEAD = register("zoglin_head", ZoglinheadBlock::new);
	public static final DeferredBlock<Block> DRAINED_ZOGLIN_CARCASS = register("drained_zoglin_carcass", DrainedzoglincarcassBlock::new);
	public static final DeferredBlock<Block> ZOGLIN_HEAD_MOUNT = register("zoglin_head_mount", ZoglinheadmountBlock::new);
	public static final DeferredBlock<Block> WOLF_CARCASS = register("wolf_carcass", WolfcarcassBlock::new);
	public static final DeferredBlock<Block> WOLF_HEAD = register("wolf_head", WolfheadBlock::new);
	public static final DeferredBlock<Block> DRAINED_WOLF_CARCASS = register("drained_wolf_carcass", DrainedWolfcarcassBlock::new);
	public static final DeferredBlock<Block> WOLF_HEAD_MOUNT = register("wolf_head_mount", WolfheadmountBlock::new);
	public static final DeferredBlock<Block> SKELETON_HORSE_CARCASS = register("skeleton_horse_carcass", SkeletonhorsecarcassBlock::new);
	public static final DeferredBlock<Block> SKELETON_HORSE_HEAD = register("skeleton_horse_head", SkeletonhorseheadBlock::new);
	public static final DeferredBlock<Block> SKELETON_HORSE_HEAD_MOUNT = register("skeleton_horse_head_mount", SkeletonhorseheadmountBlock::new);
	public static final DeferredBlock<Block> WARDEN_CARCASS = register("warden_carcass", WardencarcassBlock::new);
	public static final DeferredBlock<Block> WARDEN_HEAD = register("warden_head", WardenheadBlock::new);
	public static final DeferredBlock<Block> ZOMBIE_HORSE_CARCASS = register("zombie_horse_carcass", ZombiehorsecarcassBlock::new);
	public static final DeferredBlock<Block> ZOMBIE_HORSE_HEAD = register("zombie_horse_head", ZombiehorseheadBlock::new);
	public static final DeferredBlock<Block> DRAINED_ZOMBIE_HORSE_CARCASS = register("drained_zombie_horse_carcass", DrainedZombiehorsecarcassBlock::new);
	public static final DeferredBlock<Block> ZOMBIE_HORSE_HEAD_MOUNT = register("zombie_horse_head_mount", ZombiehorseheadmountBlock::new);
	public static final DeferredBlock<Block> SPIKE_TRAP = register("spike_trap", SpiketrapBlock::new);
	public static final DeferredBlock<Block> BRAIN = register("brain", BrainBlock::new);
	public static final DeferredBlock<Block> RAW_SAUSAGES = register("raw_sausages", RawsausagesBlock::new);
	public static final DeferredBlock<Block> COOKED_SAUSAGES = register("cooked_sausages", CookedsausagesBlock::new);
	public static final DeferredBlock<Block> RAW_BLOOD_SAUSAGES = register("raw_blood_sausages", RawbloodsausagesBlock::new);
	public static final DeferredBlock<Block> COOKED_BLOOD_SAUSAGES = register("cooked_blood_sausages", CookedbloodsausagesBlock::new);
	public static final DeferredBlock<Block> BEE_CARCASS = register("bee_carcass", BeecarcassBlock::new);
	public static final DeferredBlock<Block> BEE_HEAD = register("bee_head", BeeheadBlock::new);
	public static final DeferredBlock<Block> SNIFFER_CARCASS_BLOCK = register("sniffer_carcass_block", SniffercarcassblockBlock::new);
	public static final DeferredBlock<Block> DRAINED_SNIFFER_CARCASS_BLOCK = register("drained_sniffer_carcass_block", DrainedsniffercarcassblockBlock::new);
	public static final DeferredBlock<Block> SNIFFER_HEAD = register("sniffer_head", SnifferheadBlock::new);
	public static final DeferredBlock<Block> ENDER_DRAGON_HEAD_MOUNT = register("ender_dragon_head_mount", EnderDragonHeadMountBlock::new);
	public static final DeferredBlock<Block> EMPTY_DRAGON_TRIMMED_HEAD_MOUNT = register("empty_dragon_trimmed_head_mount", EmptydragontrimmedheadmountBlock::new);
	public static final DeferredBlock<Block> TRIMMED_ENDER_DRAGON_HEAD_MOUNT = register("trimmed_ender_dragon_head_mount", TrimmedEnderDragonHeadMountBlock::new);
	public static final DeferredBlock<Block> REPAIRED_IRONGOLEM = register("repaired_irongolem", RepairedIrongolemBlock::new);
	public static final DeferredBlock<Block> REGULAR_BLACK_HORSE_CARCASS = register("regular_black_horse_carcass", RegularblackhorsecarcassBlock::new);
	public static final DeferredBlock<Block> BLACK_HORSE_HEAD = register("black_horse_head", BlackhorseheadBlock::new);
	public static final DeferredBlock<Block> DRAINED_REGULAR_BLACK_HORSE_CARCASS = register("drained_regular_black_horse_carcass", DrainedRegularblackhorsecarcassBlock::new);
	public static final DeferredBlock<Block> BROWN_HORSE_HEAD = register("brown_horse_head", BrownhorseheadBlock::new);
	public static final DeferredBlock<Block> REGULAR_BROWN_HORSE_CARCASS = register("regular_brown_horse_carcass", RegularBrownhorsecarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_REGULAR_BROWN_HORSE_CARCASS = register("drained_regular_brown_horse_carcass", DrainedRegularBrownhorsecarcassBlock::new);
	public static final DeferredBlock<Block> CHESTNUT_HORSE_HEAD = register("chestnut_horse_head", ChestnuthorseheadBlock::new);
	public static final DeferredBlock<Block> REGULAR_CHESTNUT_HORSE_CARCASS = register("regular_chestnut_horse_carcass", RegularChestnuthorsecarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_REGULAR_CHESTNUT_HORSE_CARCASS = register("drained_regular_chestnut_horse_carcass", DrainedRegularChestnuthorsecarcassBlock::new);
	public static final DeferredBlock<Block> CREAMY_HORSE_HEAD = register("creamy_horse_head", CreamyhorseheadBlock::new);
	public static final DeferredBlock<Block> REGULAR_CREAMY_HORSE_CARCASS = register("regular_creamy_horse_carcass", RegularCreamyhorsecarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_REGULAR_CREAMY_HORSE_CARCASS = register("drained_regular_creamy_horse_carcass", DrainedRegularCreamyhorsecarcassBlock::new);
	public static final DeferredBlock<Block> DARK_BROWN_HORSE_HEAD = register("dark_brown_horse_head", DarkbrownhorseheadBlock::new);
	public static final DeferredBlock<Block> REGULAR_DARK_BROWN_HORSE_CARCASS = register("regular_dark_brown_horse_carcass", RegularDarkbrownhorsecarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_REGULAR_DARK_BROWN_HORSE_CARCASS = register("drained_regular_dark_brown_horse_carcass", DrainedRegularDarkbrownhorsecarcassBlock::new);
	public static final DeferredBlock<Block> GRAY_HORSE_HEAD = register("gray_horse_head", GrayhorseheadBlock::new);
	public static final DeferredBlock<Block> REGULAR_GRAY_HORSE_CARCASS = register("regular_gray_horse_carcass", RegularGrayhorsecarcassBlock::new);
	public static final DeferredBlock<Block> WHITE_HORSE_HEAD = register("white_horse_head", WhitehorseheadBlock::new);
	public static final DeferredBlock<Block> REGULAR_WHITE_HORSE_CARCASS = register("regular_white_horse_carcass", RegularWhitehorsecarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_GRAY_HORSE_CARCASS = register("drained_gray_horse_carcass", DrainedGrayhorsecarcassBlock::new);
	public static final DeferredBlock<Block> DRAINED_WHITE_HORSE_CARCASS = register("drained_white_horse_carcass", DrainedWhitehorsecarcassBlock::new);
	public static final DeferredBlock<Block> PLASTIC_SHEET = register("plastic_sheet", PlasticsheetBlock::new);
	public static final DeferredBlock<Block> PLASTIC_SHEET_CORNER = register("plastic_sheet_corner", PlasticsheetcornerBlock::new);
	public static final DeferredBlock<Block> CLING_FILM = register("cling_film", ClingfilmBlock::new);
	public static final DeferredBlock<Block> PHOTOS = register("photos", PhotosBlock::new);
	public static final DeferredBlock<Block> INFECTED_BLOOD = register("infected_blood", InfectedBloodBlock::new);
	public static final DeferredBlock<Block> SULFUR_ORE = register("sulfur_ore", SulfuroreBlock::new);
	public static final DeferredBlock<Block> DEEPSLATE_SULFUR_ORE = register("deepslate_sulfur_ore", DeepslatesulfuroreBlock::new);
	public static final DeferredBlock<Block> BLACK_HORSE_HEAD_MOUNT = register("black_horse_head_mount", BlackhorseheadmountBlock::new);
	public static final DeferredBlock<Block> BROWN_HORSE_HEAD_MOUNT = register("brown_horse_head_mount", BrownhorseheadmountBlock::new);
	public static final DeferredBlock<Block> CHESTNUT_HORSE_HEAD_MOUNT = register("chestnut_horse_head_mount", ChestnuthorseheadmountBlock::new);
	public static final DeferredBlock<Block> CREAMY_HORSE_HEAD_MOUNT = register("creamy_horse_head_mount", CreamyhorseheadmountBlock::new);
	public static final DeferredBlock<Block> DARK_BROWN_HORSE_HEAD_MOUNT = register("dark_brown_horse_head_mount", DarkbrownhorseheadmountBlock::new);
	public static final DeferredBlock<Block> GRAY_HORSE_HEAD_MOUNT = register("gray_horse_head_mount", GrayhorseheadmountBlock::new);
	public static final DeferredBlock<Block> WHITE_HORSE_HEAD_MOUNT = register("white_horse_head_mount", WhitehorseheadmountBlock::new);
	public static final DeferredBlock<Block> PESTLE_AND_MORTAR = register("pestle_and_mortar", PestleandmortarBlock::new);
	public static final DeferredBlock<Block> EMPTY_WARDEN_TRIMMED_HEAD_MOUNT = register("empty_warden_trimmed_head_mount", EmptywardentrimmedheadmountBlock::new);
	public static final DeferredBlock<Block> WARDEN_HEAD_MOUNT = register("warden_head_mount", WardenHeadMountBlock::new);
	public static final DeferredBlock<Block> TRIMMED_WARDEN_HEAD_MOUNT = register("trimmed_warden_head_mount", TrimmedwardenHeadMountBlock::new);
	public static final DeferredBlock<Block> AXOLOTL_SKELETON = register("axolotl_skeleton", AxolotlskeletonBlock::new);
	public static final DeferredBlock<Block> BAT_SKELETON = register("bat_skeleton", BatskeletonBlock::new);
	public static final DeferredBlock<Block> MOOSHROOM_SKELETON = register("mooshroom_skeleton", MooshroomskeletonBlock::new);
	public static final DeferredBlock<Block> CAMEL_SKELETON = register("camel_skeleton", CamelskeletonBlock::new);
	public static final DeferredBlock<Block> CAT_SKELETON = register("cat_skeleton", CatskeletonBlock::new);
	public static final DeferredBlock<Block> CHICKEN_SKELETON = register("chicken_skeleton", ChickenskeletonBlock::new);
	public static final DeferredBlock<Block> FISH_SKELETON = register("fish_skeleton", FishskeletonBlock::new);
	public static final DeferredBlock<Block> COW_SKELETON = register("cow_skeleton", CowskeletonBlock::new);
	public static final DeferredBlock<Block> CREEPER_SKELETON = register("creeper_skeleton", CreeperskeletonBlock::new);
	public static final DeferredBlock<Block> DOLPHIN_SKELETON = register("dolphin_skeleton", DolphinskeletonBlock::new);
	public static final DeferredBlock<Block> DONKEY_SKELETON = register("donkey_skeleton", DonkeyskeletonBlock::new);
	public static final DeferredBlock<Block> SKELETON = register("skeleton", SkeletonBlock::new);
	public static final DeferredBlock<Block> FOX_SKELETON = register("fox_skeleton", FoxskeletonBlock::new);
	public static final DeferredBlock<Block> GOAT_SKELETON = register("goat_skeleton", GoatskeletonBlock::new);
	public static final DeferredBlock<Block> HOGLIN_SKELETON = register("hoglin_skeleton", HoglinskeletonBlock::new);
	public static final DeferredBlock<Block> LLAMA_SKELETON = register("llama_skeleton", LlamaskeletonBlock::new);
	public static final DeferredBlock<Block> MULE_SKELETON = register("mule_skeleton", MuleskeletonBlock::new);
	public static final DeferredBlock<Block> OCELOT_SKELETON = register("ocelot_skeleton", OcelotskeletonBlock::new);
	public static final DeferredBlock<Block> PANDA_SKELETON = register("panda_skeleton", PandaskeletonBlock::new);
	public static final DeferredBlock<Block> PHANTOM_SKELETON = register("phantom_skeleton", PhantomskeletonBlock::new);
	public static final DeferredBlock<Block> PIG_SKELETON = register("pig_skeleton", PigskeletonBlock::new);
	public static final DeferredBlock<Block> PIGLIN_SKELETON = register("piglin_skeleton", PiglinskeletonBlock::new);
	public static final DeferredBlock<Block> POLARBEAR_SKELETON = register("polarbear_skeleton", PolarbearskeletonBlock::new);
	public static final DeferredBlock<Block> SHEEP_SKELETON = register("sheep_skeleton", SheepskeletonBlock::new);
	public static final DeferredBlock<Block> WOLF_SKELETON = register("wolf_skeleton", WolfskeletonBlock::new);
	public static final DeferredBlock<Block> PLAYERCORPSE = register("playercorpse", PlayercorpseBlock::new);
	public static final DeferredBlock<Block> DRAINEDPLAYERCORPSE = register("drainedplayercorpse", DrainedplayercorpseBlock::new);
	public static final DeferredBlock<Block> JAR = register("jar", JarBlock::new);
	public static final DeferredBlock<Block> RAVAGER_HEAD = register("ravager_head", RavagerheadBlock::new);
	public static final DeferredBlock<Block> RAVAGER = register("ravager", RavagerBlock::new);
	public static final DeferredBlock<Block> RAVAGER_HEAD_MOUNT = register("ravager_head_mount", RavagerHeadMountBlock::new);

	// Start of user code block custom blocks
	// End of user code block custom blocks
	private static <B extends Block> DeferredBlock<B> register(String name, Function<BlockBehaviour.Properties, ? extends B> supplier) {
		return REGISTRY.registerBlock(name, supplier, BlockBehaviour.Properties.of());
	}

	@EventBusSubscriber(bus = EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
	public static class BlocksClientSideHandler {
		@SubscribeEvent
		public static void blockColorLoad(RegisterColorHandlersEvent.Block event) {
			BasinBlock.blockColorLoad(event);
		}
	}
}